// All game prompts mirrored from src/constants/

const LIE_DETECTOR_PROMPTS = [
  "Name two things you lost recently",
  "Share two things you forgot this week",
  "Name two things on your to-do list right now",
  "Share two things you did today",
  "Name two things you checked on your phone today",
  "Share two things you did this morning",
  "Name two things you did last night",
  "Share two things you ate recently",
  "Name two tasks you've been putting off",
  "Share two things you haven't finished yet",
  "Name two things you said you'd do but didn't",
  "Share two chores you avoid",
  "Name two assignments you delayed",
  "Name two things that distract you easily",
  "Share two things you can focus on for a long time",
  "Name two apps you open too often",
  "Share two things you get distracted by on your phone",
  "Name two mistakes you made recently",
  "Share two things you forgot to do recently",
  "Name two things you had to double-check recently",
  "Share two things you got wrong recently",
  "Name two things you always carry",
  "Share two things in your bag right now",
  "Name two things on your desk",
  "Share two things you use every day",
  "Name two things you always keep nearby",
  "Name two things you talked about recently",
  "Share two things you avoid talking about",
  "Name two things you say a lot",
  "Share two things you said today",
  "Name two things you regret saying recently",
  "Name two things you do every day",
  "Share two things you always do before bed",
  "Name two things you do when you wake up",
  "Share two things you do out of habit",
  "Name two things that stress you out",
  "Share two things that help you relax",
  "Name two things that annoy you",
  "Share two things that make you excited",
  "Name two things you decided recently",
  "Share two things you chose quickly",
  "Name two things you couldn't decide on",
  "Share two things you changed your mind about",
  "Name two things you did this week",
  "Share two things you finished recently",
  "Share two things you started recently",
  "Name two things you worked on recently",
  "Share two things you avoided at school or work",
  "Name two things you completed at school or work",
  "Share two things you struggled with recently",
  "Name two shows you watched recently",
  "Share two songs you listened to recently",
  "Name two games you played recently",
  "Share two videos you watched recently",
  "Name two things you bought recently",
  "Share two things you want to buy",
  "Name two places you went recently",
  "Share two places you want to go",
  "Name two people you talked to today",
  "Share two people you texted recently",
  "Name two things you Googled recently",
  "Share two things you searched online",
  "Name two notifications you got today",
  "Share two apps you used today",
  "Name two things you drank recently",
  "Share two snacks you ate recently",
  "Name two things in your room",
  "Share two things on your bed",
  "Name two things in your fridge",
  "Share two things in your backpack",
  "Name two things you wore recently",
  "Share two outfits you like",
  "Name two things you always bring with you",
  "Share two things you forgot to bring recently",
  "Name two things you cleaned recently",
  "Share two things you need to clean",
  "Name two things you organized recently",
  "Share two things that are messy right now",
  "Name two things you charged recently",
  "Share two things that are low battery",
  "Name two things you fixed recently",
  "Share two things that are broken",
  "Name two things you opened today",
  "Share two tabs you have open right now",
  "Name two things you saved recently",
  "Share two things you deleted recently",
  "Name two things you screenshot recently",
  "Share two things in your camera roll",
  "Name two things you posted recently",
  "Share two things you almost posted",
  "Name two things you laughed at recently",
  "Share two things that made you smile",
  "Name two things that made you mad recently",
  "Share two things that stressed you out today",
  "Name two things you ignored recently",
  "Share two messages you didn't reply to",
  "Name two things you replied to quickly",
  "Share two things you delayed responding to",
  "Name two things you bookmarked recently",
  "Share two things you forgot about completely",
  "Name two things you remembered late",
  "Share two things you realized recently",
  "Name two things you learned recently",
  "Share two random facts you learned",
  "Name two things you tried recently",
  "Share two things you want to try",
  "Name two things you started but didn't finish",
  "Share two things you finished recently",
  "Name two things you skipped recently",
  "Share two things you never skip",
  "Name two things you rushed today",
  "Share two things you took your time on",
  "Name two things you checked twice",
  "Share two things you didn't check",
  "Name two things you overpaid for",
  "Share two things that were worth it",
  "Name two things you wasted time on",
  "Share two things you used your time well on",
  "Name two things you clicked on",
  "Share two things you ignored online",
  "Name two things you read recently",
  "Share two things you didn't read fully",
  "Name two things you listened to today",
  "Share two sounds you heard recently",
  "Name two things you noticed today",
  "Share two things you missed earlier",
  "Name two things you planned recently",
  "Share two things you didn't plan",
  "Name two things you scheduled",
  "Share two things you forgot to schedule",
  "Name two things you canceled",
  "Share two things you rescheduled",
  "Name two things you agreed to",
  "Share two things you said no to",
  "Name two things you said yes to",
  "Share two things you regret agreeing to",
  "Name two things you enjoy doing alone",
  "Share two things you prefer doing with others",
  "Name two things you avoid doing",
  "Share two things you don't mind doing",
  "Name two things you do when bored",
  "Share two things you do when stressed",
  "Name two things you do to relax",
  "Share two things you do to stay busy",
  "Name two things you repeat often",
  "Share two things you rarely repeat",
  "Name two things you talk about a lot",
  "Share two things you don't like talking about",
  "Name two things you bring up often",
  "Share two things you avoid bringing up",
  "Name two things you notice first",
  "Share two things you usually overlook",
  "Name two things you assume sometimes",
  "Share two things you question",
  "Name two things you worry about",
  "Share two things you don't worry about",
  "Name two things you get impatient with",
  "Share two things you're patient with",
  "Name two things you overreact to",
  "Share two things you stay calm about",
  "Name two things you hesitate on",
  "Share two things you act on quickly",
  "Name two things you change your mind on",
  "Share two things you stick with",
  "Name two things you second guess",
  "Share two things you trust your gut on",
  "Name two things you avoid thinking about",
  "Share two things you think about a lot",
  "Name two things you put off until later",
  "Share two things you deal with right away",
  "Name two things you overdo",
  "Share two things you don't do enough",
  "Name two things you forget to do",
  "Share two things you always make sure to do",
  "Name two things you skip sometimes",
  "Share two things you never skip",
  "Name two things you keep simple",
  "Share two things you make complicated",
  "Name two things you mess up sometimes",
  "Share two things you usually get right",
  "Name two things you go back and check",
  "Share two things you don't double check",
  "Name two things you rush decisions on",
  "Share two things you take your time deciding",
  "Name two things you forget quickly",
  "Share two things you remember for a long time",
  "Name two things you bring up again later",
  "Share two things you move on from quickly",
  "Name two things you rely on others for",
  "Share two things you handle yourself",
  "Name two things you avoid responsibility for",
  "Share two things you take responsibility for",
  "Name two things you overestimate",
  "Share two things you underestimate",
  "Name two things you get wrong",
  "Share two things you usually get right",
  "Name two things you overcomplicate",
  "Share two things you keep straightforward",
  "Name two things you ignore",
  "Share two things you pay attention to",
  "Name two things you delay",
  "Share two things you don't delay",
  "Name two things you forget about people",
  "Share two things you remember about people",
  "Name two things you assume about people",
  "Share two things you don't assume about people",
  "Name two things you overthink in conversations",
  "Share two things you say without thinking",
  "Name two things you repeat in conversations",
  "Share two things you don't repeat in conversations",
  "Name two things you avoid saying",
  "Share two things you say openly",
  "Name two things you keep to yourself",
  "Share two things you share easily",
  "Name two things you overexplain",
  "Share two things you keep short",
  "Name two things you forget mid-conversation",
  "Share two things you follow through on in conversations",
  "Name two things you lose interest in",
  "Share two things you stay interested in",
  "Name two things you go back to",
  "Share two things you leave behind",
  "Name two things you avoid starting",
  "Share two things you start easily",
  "Name two things you stop halfway",
  "Share two things you always finish",
  "Name two things you get distracted from",
  "Share two things you stay locked in on",
  "Name two things you forget to respond to",
  "Share two things you respond to quickly",
  "Name two things you check too often",
  "Share two things you forget to check",
  "Name two things you overcommit to",
  "Share two things you set limits on",
  "Name two things you think about later",
  "Share two things you think about right away",
  "Name two things you avoid deciding on",
  "Share two things you decide on quickly",
];

const TALENT_SHOW_PROMPTS = [
  'Do a stand-up joke about lettuce',
  'Imitate a celebrity accepting an award',
  'Act like you just won the lottery',
  'Pretend you are a dramatic weather reporter',
  'Perform a fake commercial for toothpaste',
  'Make up a song about socks',
  'Do your best evil villain laugh',
  'Pretend you are a magician whose trick just failed',
  'Narrate your life like a nature documentary',
  'Do an impression of a robot learning to dance',
  'Pretend you are a chef describing plain water',
  'Act out a job interview for the position of professional napper',
  'Perform a movie trailer for the most boring film ever made',
  'Convince the group a potato is the most exciting thing on Earth',
  'Do your best impression of a toddler explaining quantum physics',
  'Act out waking up late on the most important day of your life',
  'Perform a dramatic reading of a fast food menu',
  'Do a motivational speech about tying your shoes',
  'Imitate a GPS giving directions in a haunted house',
  'Act like you are a sports commentator for someone eating a sandwich',
  'Pretend to be a pirate who is deathly afraid of water',
  'Do your best impression of a sleepwalking chef',
  'Perform a news segment about a missing sock',
  'Act out a contestant on a cooking show who accidentally made soup instead of cake',
];

const TALENT_SHOW_TIEBREAK_PROMPTS = [
  'Beatbox for 10 seconds',
  'Do your best chicken impression',
  'Say the alphabet backwards as fast as you can',
  'Air guitar to a song only you can hear',
  'Do the most dramatic shocked face and hold it',
  'Pretend to be a statue slowly coming to life',
  'Do your best ninja move in slow motion',
  'Imitate a phone that just ran out of battery',
  'Act out a sneeze in extreme slow motion',
  'Make the sound of a dial-up modem connecting',
  'Do your best T-Rex impression',
  'Mime pulling an extremely heavy object across the room',
];

const TALENT_SHOW_FINAL_PROMPTS = [
  'Attempt a breakdance routine while saying words that rhyme with "cat"',
  'Perform opera about the last meal you ate',
  'Act out a slow-motion car crash using only your body and sound effects',
  'Pretend you are fighting a giant invisible spider — for the full 30 seconds',
  'Imitate a broken robot trying to propose marriage',
  'Act out what happens when a toddler accidentally becomes president',
  'Perform a dramatic death scene from eating slightly-too-cold pizza',
  'Do your best impression of a drunk penguin trying to ice skate',
  'Pretend you are a superhero whose only power is being excessively enthusiastic',
  'Host a cooking show where the only ingredient is imaginary air',
  'Give a motivational speech as a deeply disappointed potato',
  'Act out a first-date disaster in fast forward then slow motion',
  'Imitate a fitness influencer who has never exercised before in their life',
  'Perform a Shakespearean tragedy about missing the bus',
];

const STAND_OUT_PROMPTS = [
  { id: 'so_e51', text: 'Name a type of sandwich bread', difficulty: 'easy' },
  { id: 'so_e52', text: 'Name a smoothie ingredient', difficulty: 'easy' },
  { id: 'so_e53', text: 'Name something you wear in winter', difficulty: 'easy' },
  { id: 'so_e54', text: 'Name something you bring to the beach', difficulty: 'easy' },
  { id: 'so_e55', text: 'Name something found in a fridge', difficulty: 'easy' },
  { id: 'so_e56', text: 'Name a type of pizza crust', difficulty: 'easy' },
  { id: 'so_e57', text: 'Name an ice cream topping', difficulty: 'easy' },
  { id: 'so_e58', text: 'Name something spicy', difficulty: 'easy' },
  { id: 'so_e59', text: 'Name a type of soup', difficulty: 'easy' },
  { id: 'so_e60', text: 'Name something crunchy', difficulty: 'easy' },
  { id: 'so_e61', text: 'Name something you do before bed', difficulty: 'easy' },
  { id: 'so_e62', text: 'Name something you do after waking up', difficulty: 'easy' },
  { id: 'so_e63', text: 'Name something in your bathroom', difficulty: 'easy' },
  { id: 'so_e64', text: 'Name something in your kitchen', difficulty: 'easy' },
  { id: 'so_e65', text: 'Name something in your living room', difficulty: 'easy' },
  { id: 'so_e66', text: 'Name something you sit on', difficulty: 'easy' },
  { id: 'so_e67', text: 'Name something you plug in', difficulty: 'easy' },
  { id: 'so_e68', text: 'Name something that lights up', difficulty: 'easy' },
  { id: 'so_e69', text: 'Name something you throw away', difficulty: 'easy' },
  { id: 'so_e70', text: 'Name something you recycle', difficulty: 'easy' },
  { id: 'so_e71', text: 'Name something you do at a party', difficulty: 'easy' },
  { id: 'so_e72', text: 'Name something you do at school', difficulty: 'easy' },
  { id: 'so_e73', text: 'Name something you do on vacation', difficulty: 'easy' },
  { id: 'so_e74', text: 'Name something you do in summer', difficulty: 'easy' },
  { id: 'so_e75', text: 'Name something you do in winter', difficulty: 'easy' },
  { id: 'so_e76', text: 'Name something you do when bored', difficulty: 'easy' },
  { id: 'so_e77', text: 'Name something you do when tired', difficulty: 'easy' },
  { id: 'so_e78', text: 'Name something you do when sick', difficulty: 'easy' },
  { id: 'so_e79', text: 'Name something you do when happy', difficulty: 'easy' },
  { id: 'so_e80', text: 'Name something you do when stressed', difficulty: 'easy' },
  { id: 'so_e81', text: 'Name something you eat with your hands', difficulty: 'easy' },
  { id: 'so_e82', text: 'Name something you drink cold', difficulty: 'easy' },
  { id: 'so_e83', text: 'Name something you drink hot', difficulty: 'easy' },
  { id: 'so_e84', text: 'Name something sweet', difficulty: 'easy' },
  { id: 'so_e85', text: 'Name something salty', difficulty: 'easy' },
  { id: 'so_e86', text: 'Name something sour', difficulty: 'easy' },
  { id: 'so_e87', text: 'Name something bitter', difficulty: 'easy' },
  { id: 'so_e88', text: 'Name something soft', difficulty: 'easy' },
  { id: 'so_e89', text: 'Name something hard', difficulty: 'easy' },
  { id: 'so_e90', text: 'Name something chewy', difficulty: 'easy' },
  { id: 'so_e91', text: 'Name something in a backpack', difficulty: 'easy' },
  { id: 'so_e92', text: 'Name something in a locker', difficulty: 'easy' },
  { id: 'so_e93', text: 'Name something in a car', difficulty: 'easy' },
  { id: 'so_e94', text: 'Name something in a garage', difficulty: 'easy' },
  { id: 'so_e95', text: 'Name something in a park', difficulty: 'easy' },
  { id: 'so_e96', text: 'Name something at a gym', difficulty: 'easy' },
  { id: 'so_e97', text: 'Name something at a restaurant', difficulty: 'easy' },
  { id: 'so_e98', text: 'Name something at a movie theater', difficulty: 'easy' },
  { id: 'so_e99', text: 'Name something at a concert', difficulty: 'easy' },
  { id: 'so_e100', text: 'Name something at a stadium', difficulty: 'easy' },
  { id: 'so_e101', text: 'Name a board game piece', difficulty: 'easy' },
  { id: 'so_e102', text: 'Name a type of bag', difficulty: 'easy' },
  { id: 'so_e103', text: 'Name a type of candy bar', difficulty: 'easy' },
  { id: 'so_e104', text: 'Name a type of chip flavor', difficulty: 'easy' },
  { id: 'so_e105', text: 'Name a breakfast drink', difficulty: 'easy' },
  { id: 'so_e106', text: 'Name a kind of taco filling', difficulty: 'easy' },
  { id: 'so_e107', text: 'Name a type of noodle', difficulty: 'easy' },
  { id: 'so_e108', text: 'Name a kind of dipping sauce', difficulty: 'easy' },
  { id: 'so_e109', text: 'Name something on a pizza', difficulty: 'easy' },
  { id: 'so_e110', text: 'Name a flavor of gum', difficulty: 'easy' },
  { id: 'so_e111', text: 'Name a type of cookie', difficulty: 'easy' },
  { id: 'so_e112', text: 'Name a type of cake', difficulty: 'easy' },
  { id: 'so_e113', text: 'Name a donut flavor', difficulty: 'easy' },
  { id: 'so_e114', text: 'Name a milkshake flavor', difficulty: 'easy' },
  { id: 'so_e115', text: 'Name a cereal topping', difficulty: 'easy' },
  { id: 'so_e116', text: 'Name something in a vending machine', difficulty: 'easy' },
  { id: 'so_e117', text: 'Name something in a lunchbox', difficulty: 'easy' },
  { id: 'so_e118', text: 'Name something served at a barbecue', difficulty: 'easy' },
  { id: 'so_e119', text: 'Name something you\'d find at a carnival', difficulty: 'easy' },
  { id: 'so_e120', text: 'Name something sold at a food truck', difficulty: 'easy' },
  { id: 'so_e121', text: 'Name an animal at a zoo', difficulty: 'easy' },
  { id: 'so_e122', text: 'Name a farm animal', difficulty: 'easy' },
  { id: 'so_e123', text: 'Name a sea creature', difficulty: 'easy' },
  { id: 'so_e124', text: 'Name a jungle animal', difficulty: 'easy' },
  { id: 'so_e125', text: 'Name a pet store animal', difficulty: 'easy' },
  { id: 'so_e126', text: 'Name something with feathers', difficulty: 'easy' },
  { id: 'so_e127', text: 'Name something with fur', difficulty: 'easy' },
  { id: 'so_e128', text: 'Name something with scales', difficulty: 'easy' },
  { id: 'so_e129', text: 'Name an animal that hops', difficulty: 'easy' },
  { id: 'so_e130', text: 'Name an animal that swims', difficulty: 'easy' },
  { id: 'so_e131', text: 'Name something in the sky', difficulty: 'easy' },
  { id: 'so_e132', text: 'Name something at the bottom of the ocean', difficulty: 'easy' },
  { id: 'so_e133', text: 'Name something in a forest', difficulty: 'easy' },
  { id: 'so_e134', text: 'Name something in the desert', difficulty: 'easy' },
  { id: 'so_e135', text: 'Name something near a river', difficulty: 'easy' },
  { id: 'so_e136', text: 'Name a kind of tree', difficulty: 'easy' },
  { id: 'so_e137', text: 'Name a flower color', difficulty: 'easy' },
  { id: 'so_e138', text: 'Name a weather condition', difficulty: 'easy' },
  { id: 'so_e139', text: 'Name something seen during a storm', difficulty: 'easy' },
  { id: 'so_e140', text: 'Name something seen at night', difficulty: 'easy' },
  { id: 'so_e141', text: 'Name a school subject', difficulty: 'easy' },
  { id: 'so_e142', text: 'Name a classroom supply', difficulty: 'easy' },
  { id: 'so_e143', text: 'Name something written with', difficulty: 'easy' },
  { id: 'so_e144', text: 'Name something erased', difficulty: 'easy' },
  { id: 'so_e145', text: 'Name something you read', difficulty: 'easy' },
  { id: 'so_e146', text: 'Name something you study for', difficulty: 'easy' },
  { id: 'so_e147', text: 'Name something on a test', difficulty: 'easy' },
  { id: 'so_e148', text: 'Name a reason to raise your hand', difficulty: 'easy' },
  { id: 'so_e149', text: 'Name something in a science lab', difficulty: 'easy' },
  { id: 'so_e150', text: 'Name something in math class', difficulty: 'easy' },
  { id: 'so_e151', text: 'Name an app on a phone', difficulty: 'easy' },
  { id: 'so_e152', text: 'Name a thing you use a charger for', difficulty: 'easy' },
  { id: 'so_e153', text: 'Name something with a screen', difficulty: 'easy' },
  { id: 'so_e154', text: 'Name something with buttons', difficulty: 'easy' },
  { id: 'so_e155', text: 'Name something with a camera', difficulty: 'easy' },
  { id: 'so_e156', text: 'Name something you can text on', difficulty: 'easy' },
  { id: 'so_e157', text: 'Name something you can game on', difficulty: 'easy' },
  { id: 'so_e158', text: 'Name something you can stream on', difficulty: 'easy' },
  { id: 'so_e159', text: 'Name something you wear on your wrist', difficulty: 'easy' },
  { id: 'so_e160', text: 'Name something that buzzes', difficulty: 'easy' },
  { id: 'so_e161', text: 'Name a sport played indoors', difficulty: 'easy' },
  { id: 'so_e162', text: 'Name a sport played outdoors', difficulty: 'easy' },
  { id: 'so_e163', text: 'Name something used in basketball', difficulty: 'easy' },
  { id: 'so_e164', text: 'Name something used in soccer', difficulty: 'easy' },
  { id: 'so_e165', text: 'Name something used in baseball', difficulty: 'easy' },
  { id: 'so_e166', text: 'Name something used in tennis', difficulty: 'easy' },
  { id: 'so_e167', text: 'Name something used in football', difficulty: 'easy' },
  { id: 'so_e168', text: 'Name something used in golf', difficulty: 'easy' },
  { id: 'so_e169', text: 'Name something worn by an athlete', difficulty: 'easy' },
  { id: 'so_e170', text: 'Name something seen in a locker room', difficulty: 'easy' },
  { id: 'so_e171', text: 'Name something at an amusement park', difficulty: 'easy' },
  { id: 'so_e172', text: 'Name something at an arcade', difficulty: 'easy' },
  { id: 'so_e173', text: 'Name something at a sleepover', difficulty: 'easy' },
  { id: 'so_e174', text: 'Name something at a birthday party', difficulty: 'easy' },
  { id: 'so_e175', text: 'Name something at a wedding', difficulty: 'easy' },
  { id: 'so_e176', text: 'Name something at a mall', difficulty: 'easy' },
  { id: 'so_e177', text: 'Name something at a grocery store', difficulty: 'easy' },
  { id: 'so_e178', text: 'Name something at a gas station', difficulty: 'easy' },
  { id: 'so_e179', text: 'Name something at an airport', difficulty: 'easy' },
  { id: 'so_e180', text: 'Name something at a hotel', difficulty: 'easy' },
  { id: 'so_e181', text: 'Name a type of shoe', difficulty: 'easy' },
  { id: 'so_e182', text: 'Name a type of jacket', difficulty: 'easy' },
  { id: 'so_e183', text: 'Name a type of hat', difficulty: 'easy' },
  { id: 'so_e184', text: 'Name a type of necklace', difficulty: 'easy' },
  { id: 'so_e185', text: 'Name a type of hairstyle', difficulty: 'easy' },
  { id: 'so_e186', text: 'Name something worn in summer', difficulty: 'easy' },
  { id: 'so_e187', text: 'Name something worn in the rain', difficulty: 'easy' },
  { id: 'so_e188', text: 'Name something worn to sleep', difficulty: 'easy' },
  { id: 'so_e189', text: 'Name something worn to a party', difficulty: 'easy' },
  { id: 'so_e190', text: 'Name something worn at the gym', difficulty: 'easy' },
  { id: 'so_e191', text: 'Name a musical instrument', difficulty: 'easy' },
  { id: 'so_e192', text: 'Name something in a band', difficulty: 'easy' },
  { id: 'so_e193', text: 'Name something on a stage', difficulty: 'easy' },
  { id: 'so_e194', text: 'Name something in a song', difficulty: 'easy' },
  { id: 'so_e195', text: 'Name something a DJ uses', difficulty: 'easy' },
  { id: 'so_e196', text: 'Name something a singer holds', difficulty: 'easy' },
  { id: 'so_e197', text: 'Name something that has strings', difficulty: 'easy' },
  { id: 'so_e198', text: 'Name something that has keys', difficulty: 'easy' },
  { id: 'so_e199', text: 'Name something that has speakers', difficulty: 'easy' },
  { id: 'so_e200', text: 'Name something that plays music', difficulty: 'easy' },
  { id: 'so_e201', text: 'Name a superhero power', difficulty: 'easy' },
  { id: 'so_e202', text: 'Name a fantasy creature', difficulty: 'easy' },
  { id: 'so_e203', text: 'Name something in outer space', difficulty: 'easy' },
  { id: 'so_e204', text: 'Name something in a video game', difficulty: 'easy' },
  { id: 'so_e205', text: 'Name something in a treasure chest', difficulty: 'easy' },
  { id: 'so_e206', text: 'Name something a pirate has', difficulty: 'easy' },
  { id: 'so_e207', text: 'Name something a wizard uses', difficulty: 'easy' },
  { id: 'so_e208', text: 'Name something a knight wears', difficulty: 'easy' },
  { id: 'so_e209', text: 'Name something a dragon could protect', difficulty: 'easy' },
  { id: 'so_e210', text: 'Name something found in a castle', difficulty: 'easy' },
  { id: 'so_e211', text: 'Name something made of wood', difficulty: 'easy' },
  { id: 'so_e212', text: 'Name something made of glass', difficulty: 'easy' },
  { id: 'so_e213', text: 'Name something made of metal', difficulty: 'easy' },
  { id: 'so_e214', text: 'Name something made of plastic', difficulty: 'easy' },
  { id: 'so_e215', text: 'Name something made of paper', difficulty: 'easy' },
  { id: 'so_e216', text: 'Name something that folds', difficulty: 'easy' },
  { id: 'so_e217', text: 'Name something that rolls', difficulty: 'easy' },
  { id: 'so_e218', text: 'Name something that bounces', difficulty: 'easy' },
  { id: 'so_e219', text: 'Name something that spins', difficulty: 'easy' },
  { id: 'so_e220', text: 'Name something that melts', difficulty: 'easy' },
  { id: 'so_e221', text: 'Name something you can win', difficulty: 'easy' },
  { id: 'so_e222', text: 'Name something you can lose', difficulty: 'easy' },
  { id: 'so_e223', text: 'Name something you can share', difficulty: 'easy' },
  { id: 'so_e224', text: 'Name something you can hide', difficulty: 'easy' },
  { id: 'so_e225', text: 'Name something you can collect', difficulty: 'easy' },
  { id: 'so_e226', text: 'Name something you can trade', difficulty: 'easy' },
  { id: 'so_e227', text: 'Name something you can upgrade', difficulty: 'easy' },
  { id: 'so_e228', text: 'Name something you can repair', difficulty: 'easy' },
  { id: 'so_e229', text: 'Name something you can customize', difficulty: 'easy' },
  { id: 'so_e230', text: 'Name something you can decorate', difficulty: 'easy' },
  { id: 'so_e231', text: 'Name something that smells good', difficulty: 'easy' },
  { id: 'so_e232', text: 'Name something that smells bad', difficulty: 'easy' },
  { id: 'so_e233', text: 'Name something that tastes fresh', difficulty: 'easy' },
  { id: 'so_e234', text: 'Name something that tastes bland', difficulty: 'easy' },
  { id: 'so_e235', text: 'Name something that feels smooth', difficulty: 'easy' },
  { id: 'so_e236', text: 'Name something that feels rough', difficulty: 'easy' },
  { id: 'so_e237', text: 'Name something that feels sticky', difficulty: 'easy' },
  { id: 'so_e238', text: 'Name something that feels slippery', difficulty: 'easy' },
  { id: 'so_e239', text: 'Name something that feels fuzzy', difficulty: 'easy' },
  { id: 'so_e240', text: 'Name something that feels sharp', difficulty: 'easy' },
  { id: 'so_e241', text: 'Name something that moves fast', difficulty: 'easy' },
  { id: 'so_e242', text: 'Name something that moves slow', difficulty: 'easy' },
  { id: 'so_e243', text: 'Name something that makes noise', difficulty: 'easy' },
  { id: 'so_e244', text: 'Name something that is silent', difficulty: 'easy' },
  { id: 'so_e245', text: 'Name something that is bright', difficulty: 'easy' },
  { id: 'so_e246', text: 'Name something that is dark', difficulty: 'easy' },
  { id: 'so_e247', text: 'Name something that is heavy', difficulty: 'easy' },
  { id: 'so_e248', text: 'Name something that is light', difficulty: 'easy' },
  { id: 'so_e249', text: 'Name something that is expensive', difficulty: 'easy' },
  { id: 'so_e250', text: 'Name something that is rare', difficulty: 'easy' },
  { id: 'so_h51', text: 'Name a fruit with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h52', text: 'Name a country with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h53', text: 'Name a U.S. state starting with A', difficulty: 'hard' },
  { id: 'so_h54', text: 'Name a word ending in ly', difficulty: 'hard' },
  { id: 'so_h55', text: 'Name a word with double letters', difficulty: 'hard' },
  { id: 'so_h56', text: 'Name a number divisible by 7', difficulty: 'hard' },
  { id: 'so_h57', text: 'Name a number between 30 and 40', difficulty: 'hard' },
  { id: 'so_h58', text: 'Name a word with 3 syllables', difficulty: 'hard' },
  { id: 'so_h59', text: 'Name a word starting with un', difficulty: 'hard' },
  { id: 'so_h60', text: 'Name a word ending in ment', difficulty: 'hard' },
  { id: 'so_h61', text: 'Name a bird that cannot fly', difficulty: 'hard' },
  { id: 'so_h62', text: 'Name a planet with rings', difficulty: 'hard' },
  { id: 'so_h63', text: 'Name a chess piece that is not a pawn', difficulty: 'hard' },
  { id: 'so_h64', text: 'Name a Greek letter after alpha', difficulty: 'hard' },
  { id: 'so_h65', text: 'Name a programming language starting with C', difficulty: 'hard' },
  { id: 'so_h66', text: 'Name a unit of length', difficulty: 'hard' },
  { id: 'so_h67', text: 'Name a unit of weight', difficulty: 'hard' },
  { id: 'so_h68', text: 'Name a type of triangle with equal sides', difficulty: 'hard' },
  { id: 'so_h69', text: 'Name a polygon with 8 sides', difficulty: 'hard' },
  { id: 'so_h70', text: 'Name a shape with 3 sides', difficulty: 'hard' },
  { id: 'so_h71', text: 'Name a country ending in ia', difficulty: 'hard' },
  { id: 'so_h72', text: 'Name a word that rhymes with blue', difficulty: 'hard' },
  { id: 'so_h73', text: 'Name a word with 4 vowels', difficulty: 'hard' },
  { id: 'so_h74', text: 'Name a number divisible by 11', difficulty: 'hard' },
  { id: 'so_h75', text: 'Name a fruit starting with B', difficulty: 'hard' },
  { id: 'so_h76', text: 'Name a country starting with D', difficulty: 'hard' },
  { id: 'so_h77', text: 'Name a U.S. state starting with N', difficulty: 'hard' },
  { id: 'so_h78', text: 'Name a word ending with tion', difficulty: 'hard' },
  { id: 'so_h79', text: 'Name a word with exactly 7 letters', difficulty: 'hard' },
  { id: 'so_h80', text: 'Name a number between 90 and 100', difficulty: 'hard' },
  { id: 'so_h81', text: 'Name a type of triangle with no equal sides', difficulty: 'hard' },
  { id: 'so_h82', text: 'Name a word starting with pre', difficulty: 'hard' },
  { id: 'so_h83', text: 'Name a word ending with est', difficulty: 'hard' },
  { id: 'so_h84', text: 'Name a number divisible by 9', difficulty: 'hard' },
  { id: 'so_h85', text: 'Name a number between 200 and 210', difficulty: 'hard' },
  { id: 'so_h86', text: 'Name a word with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h87', text: 'Name a word starting with tri', difficulty: 'hard' },
  { id: 'so_h88', text: 'Name a word containing ph', difficulty: 'hard' },
  { id: 'so_h89', text: 'Name a word ending with ize', difficulty: 'hard' },
  { id: 'so_h90', text: 'Name a word starting with ex', difficulty: 'hard' },
  { id: 'so_h91', text: 'Name a word with exactly 2 vowels', difficulty: 'hard' },
  { id: 'so_h92', text: 'Name a word with exactly 3 consonants', difficulty: 'hard' },
  { id: 'so_h93', text: 'Name a number divisible by 4', difficulty: 'hard' },
  { id: 'so_h94', text: 'Name a number between 60 and 70', difficulty: 'hard' },
  { id: 'so_h95', text: 'Name a word starting with sub', difficulty: 'hard' },
  { id: 'so_h96', text: 'Name a word ending with ful', difficulty: 'hard' },
  { id: 'so_h97', text: 'Name a word containing oo', difficulty: 'hard' },
  { id: 'so_h98', text: 'Name a word containing ea', difficulty: 'hard' },
  { id: 'so_h99', text: 'Name a word with exactly 8 letters', difficulty: 'hard' },
  { id: 'so_h100', text: 'Name a number divisible by 6', difficulty: 'hard' },
  { id: 'so_h101', text: 'Name a number between 500 and 510', difficulty: 'hard' },
  { id: 'so_h102', text: 'Name a word starting with over', difficulty: 'hard' },
  { id: 'so_h103', text: 'Name a word ending with less', difficulty: 'hard' },
  { id: 'so_h104', text: 'Name a word with exactly 9 letters', difficulty: 'hard' },
  { id: 'so_h105', text: 'Name a word starting with mis', difficulty: 'hard' },
  { id: 'so_h106', text: 'Name a number divisible by 12', difficulty: 'hard' },
  { id: 'so_h107', text: 'Name a number between 1000 and 1010', difficulty: 'hard' },
  { id: 'so_h108', text: 'Name a word with exactly 10 letters', difficulty: 'hard' },
  { id: 'so_h109', text: 'Name a word containing str', difficulty: 'hard' },
  { id: 'so_h110', text: 'Name a word containing ght', difficulty: 'hard' },
  { id: 'so_h111', text: 'Name a word ending with ship', difficulty: 'hard' },
  { id: 'so_h112', text: 'Name a word starting with auto', difficulty: 'hard' },
  { id: 'so_h113', text: 'Name a word ending with ward', difficulty: 'hard' },
  { id: 'so_h114', text: 'Name a word starting with inter', difficulty: 'hard' },
  { id: 'so_h115', text: 'Name a word ending with ology', difficulty: 'hard' },
  { id: 'so_h116', text: 'Name a word containing scr', difficulty: 'hard' },
  { id: 'so_h117', text: 'Name a word with exactly 11 letters', difficulty: 'hard' },
  { id: 'so_h118', text: 'Name a word starting with trans', difficulty: 'hard' },
  { id: 'so_h119', text: 'Name a word ending with able', difficulty: 'hard' },
  { id: 'so_h120', text: 'Name a word containing kn', difficulty: 'hard' },
  { id: 'so_h121', text: 'Name a word containing wr', difficulty: 'hard' },
  { id: 'so_h122', text: 'Name a country starting with Q', difficulty: 'hard' },
  { id: 'so_h123', text: 'Name a fruit starting with G', difficulty: 'hard' },
  { id: 'so_h124', text: 'Name a U.S. state starting with W', difficulty: 'hard' },
  { id: 'so_h125', text: 'Name a word ending with ness', difficulty: 'hard' },
  { id: 'so_h126', text: 'Name a word starting with anti', difficulty: 'hard' },
  { id: 'so_h127', text: 'Name a number divisible by 13', difficulty: 'hard' },
  { id: 'so_h128', text: 'Name a number between 70 and 80', difficulty: 'hard' },
  { id: 'so_h129', text: 'Name a word containing qu', difficulty: 'hard' },
  { id: 'so_h130', text: 'Name a word containing tch', difficulty: 'hard' },
  { id: 'so_h131', text: 'Name a word ending with ive', difficulty: 'hard' },
  { id: 'so_h132', text: 'Name a planet that is not Earth or Mars', difficulty: 'hard' },
  { id: 'so_h133', text: 'Name a chemical element starting with B', difficulty: 'hard' },
  { id: 'so_h134', text: 'Name a gemstone starting with A', difficulty: 'hard' },
  { id: 'so_h135', text: 'Name a musical instrument starting with V', difficulty: 'hard' },
  { id: 'so_h136', text: 'Name a language starting with J', difficulty: 'hard' },
  { id: 'so_h137', text: 'Name a country starting with Y', difficulty: 'hard' },
  { id: 'so_h138', text: 'Name a word ending with ary', difficulty: 'hard' },
  { id: 'so_h139', text: 'Name a word starting with co', difficulty: 'hard' },
  { id: 'so_h140', text: 'Name a number divisible by 8', difficulty: 'hard' },
  { id: 'so_h141', text: 'Name a number between 400 and 410', difficulty: 'hard' },
  { id: 'so_h142', text: 'Name a word with exactly 12 letters', difficulty: 'hard' },
  { id: 'so_h143', text: 'Name a word containing pt', difficulty: 'hard' },
  { id: 'so_h144', text: 'Name a word ending with ant', difficulty: 'hard' },
  { id: 'so_h145', text: 'Name a bird starting with P', difficulty: 'hard' },
  { id: 'so_h146', text: 'Name a sea animal starting with S', difficulty: 'hard' },
  { id: 'so_h147', text: 'Name a car brand starting with F', difficulty: 'hard' },
  { id: 'so_h148', text: 'Name a U.S. state starting with O', difficulty: 'hard' },
  { id: 'so_h149', text: 'Name a word starting with dis', difficulty: 'hard' },
  { id: 'so_h150', text: 'Name a word ending with or', difficulty: 'hard' },
  { id: 'so_h151', text: 'Name a number divisible by 5 and 3', difficulty: 'hard' },
  { id: 'so_h152', text: 'Name a number between 150 and 160', difficulty: 'hard' },
  { id: 'so_h153', text: 'Name a word containing mp', difficulty: 'hard' },
  { id: 'so_h154', text: 'Name a word containing nd', difficulty: 'hard' },
  { id: 'so_h155', text: 'Name a word ending with er', difficulty: 'hard' },
  { id: 'so_h156', text: 'Name a word starting with re', difficulty: 'hard' },
  { id: 'so_h157', text: 'Name a word with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h158', text: 'Name a country starting with L', difficulty: 'hard' },
  { id: 'so_h159', text: 'Name a fruit starting with M', difficulty: 'hard' },
  { id: 'so_h160', text: 'Name a word ending with al', difficulty: 'hard' },
  { id: 'so_h161', text: 'Name a word starting with out', difficulty: 'hard' },
  { id: 'so_h162', text: 'Name a number divisible by 14', difficulty: 'hard' },
  { id: 'so_h163', text: 'Name a number between 20 and 25', difficulty: 'hard' },
  { id: 'so_h164', text: 'Name a word containing cl', difficulty: 'hard' },
  { id: 'so_h165', text: 'Name a word containing br', difficulty: 'hard' },
  { id: 'so_h166', text: 'Name a word ending with ic', difficulty: 'hard' },
  { id: 'so_h167', text: 'Name a type of cloud', difficulty: 'hard' },
  { id: 'so_h168', text: 'Name a rock type', difficulty: 'hard' },
  { id: 'so_h169', text: 'Name an energy source', difficulty: 'hard' },
  { id: 'so_h170', text: 'Name a continent that is not Asia', difficulty: 'hard' },
  { id: 'so_h171', text: 'Name a body part with 5 letters', difficulty: 'hard' },
  { id: 'so_h172', text: 'Name a word starting with non', difficulty: 'hard' },
  { id: 'so_h173', text: 'Name a word ending with ary', difficulty: 'hard' },
  { id: 'so_h174', text: 'Name a number between 250 and 260', difficulty: 'hard' },
  { id: 'so_h175', text: 'Name a word with exactly 13 letters', difficulty: 'hard' },
  { id: 'so_h176', text: 'Name a word containing gl', difficulty: 'hard' },
  { id: 'so_h177', text: 'Name a word containing ct', difficulty: 'hard' },
  { id: 'so_h178', text: 'Name a word ending with dom', difficulty: 'hard' },
  { id: 'so_h179', text: 'Name a word starting with post', difficulty: 'hard' },
  { id: 'so_h180', text: 'Name a country starting with K', difficulty: 'hard' },
  { id: 'so_h181', text: 'Name a fruit starting with C', difficulty: 'hard' },
  { id: 'so_h182', text: 'Name a word ending with age', difficulty: 'hard' },
  { id: 'so_h183', text: 'Name a word starting with micro', difficulty: 'hard' },
  { id: 'so_h184', text: 'Name a number divisible by 15', difficulty: 'hard' },
  { id: 'so_h185', text: 'Name a number between 800 and 810', difficulty: 'hard' },
  { id: 'so_h186', text: 'Name a word containing fr', difficulty: 'hard' },
  { id: 'so_h187', text: 'Name a word containing sw', difficulty: 'hard' },
  { id: 'so_h188', text: 'Name a word ending with hood', difficulty: 'hard' },
  { id: 'so_h189', text: 'Name a moon of a planet', difficulty: 'hard' },
  { id: 'so_h190', text: 'Name a unit of time', difficulty: 'hard' },
  { id: 'so_h191', text: 'Name a programming language starting with R', difficulty: 'hard' },
  { id: 'so_h192', text: 'Name a metal starting with S', difficulty: 'hard' },
  { id: 'so_h193', text: 'Name a country starting with U', difficulty: 'hard' },
  { id: 'so_h194', text: 'Name a word starting with under', difficulty: 'hard' },
  { id: 'so_h195', text: 'Name a word ending with some', difficulty: 'hard' },
  { id: 'so_h196', text: 'Name a number between 11 and 19', difficulty: 'hard' },
  { id: 'so_h197', text: 'Name a word with exactly 14 letters', difficulty: 'hard' },
  { id: 'so_h198', text: 'Name a word containing sp', difficulty: 'hard' },
  { id: 'so_h199', text: 'Name a word containing lk', difficulty: 'hard' },
  { id: 'so_h200', text: 'Name a word ending with ity', difficulty: 'hard' },
  { id: 'so_h201', text: 'Name a word starting with mega', difficulty: 'hard' },
  { id: 'so_h202', text: 'Name a country starting with E', difficulty: 'hard' },
  { id: 'so_h203', text: 'Name a fruit starting with T', difficulty: 'hard' },
  { id: 'so_h204', text: 'Name a U.S. state starting with I', difficulty: 'hard' },
  { id: 'so_h205', text: 'Name a word ending with ism', difficulty: 'hard' },
  { id: 'so_h206', text: 'Name a word starting with hyper', difficulty: 'hard' },
  { id: 'so_h207', text: 'Name a number divisible by 16', difficulty: 'hard' },
  { id: 'so_h208', text: 'Name a number between 320 and 330', difficulty: 'hard' },
  { id: 'so_h209', text: 'Name a word containing dr', difficulty: 'hard' },
  { id: 'so_h210', text: 'Name a word containing fl', difficulty: 'hard' },
  { id: 'so_h211', text: 'Name a word ending with ence', difficulty: 'hard' },
  { id: 'so_h212', text: 'Name a chess piece starting with K', difficulty: 'hard' },
  { id: 'so_h213', text: 'Name a Greek letter starting with O', difficulty: 'hard' },
  { id: 'so_h214', text: 'Name a country ending with stan', difficulty: 'hard' },
  { id: 'so_h215', text: 'Name a word starting with multi', difficulty: 'hard' },
  { id: 'so_h216', text: 'Name a number between 42 and 48', difficulty: 'hard' },
  { id: 'so_h217', text: 'Name a word with exactly 15 letters', difficulty: 'hard' },
  { id: 'so_h218', text: 'Name a word containing bl', difficulty: 'hard' },
  { id: 'so_h219', text: 'Name a word containing rk', difficulty: 'hard' },
  { id: 'so_h220', text: 'Name a word ending with ive', difficulty: 'hard' },
  { id: 'so_h221', text: 'Name a fruit with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h222', text: 'Name a country with exactly 7 letters', difficulty: 'hard' },
  { id: 'so_h223', text: 'Name a U.S. state with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h224', text: 'Name a word ending with en', difficulty: 'hard' },
  { id: 'so_h225', text: 'Name a word starting with semi', difficulty: 'hard' },
  { id: 'so_h226', text: 'Name a number divisible by 18', difficulty: 'hard' },
  { id: 'so_h227', text: 'Name a number between 610 and 620', difficulty: 'hard' },
  { id: 'so_h228', text: 'Name a word containing gr', difficulty: 'hard' },
  { id: 'so_h229', text: 'Name a word containing sk', difficulty: 'hard' },
  { id: 'so_h230', text: 'Name a word ending with ous', difficulty: 'hard' },
  { id: 'so_h231', text: 'Name a color with exactly 4 letters', difficulty: 'hard' },
  { id: 'so_h232', text: 'Name a gemstone ending with ite', difficulty: 'hard' },
  { id: 'so_h233', text: 'Name a unit of temperature', difficulty: 'hard' },
  { id: 'so_h234', text: 'Name a word starting with neo', difficulty: 'hard' },
  { id: 'so_h235', text: 'Name a number between 44 and 54', difficulty: 'hard' },
  { id: 'so_h236', text: 'Name a word with exactly 16 letters', difficulty: 'hard' },
  { id: 'so_h237', text: 'Name a word containing cr', difficulty: 'hard' },
  { id: 'so_h238', text: 'Name a word containing tw', difficulty: 'hard' },
  { id: 'so_h239', text: 'Name a word ending with ian', difficulty: 'hard' },
  { id: 'so_h240', text: 'Name a country starting with R', difficulty: 'hard' },
  { id: 'so_h241', text: 'Name a fruit starting with A', difficulty: 'hard' },
  { id: 'so_h242', text: 'Name a U.S. state starting with H', difficulty: 'hard' },
  { id: 'so_h243', text: 'Name a word ending with ure', difficulty: 'hard' },
  { id: 'so_h244', text: 'Name a word starting with super', difficulty: 'hard' },
  { id: 'so_h245', text: 'Name a number divisible by 10', difficulty: 'hard' },
  { id: 'so_h246', text: 'Name a number between 710 and 720', difficulty: 'hard' },
  { id: 'so_h247', text: 'Name a word containing pr', difficulty: 'hard' },
  { id: 'so_h248', text: 'Name a word containing sm', difficulty: 'hard' },
  { id: 'so_h249', text: 'Name a word ending with ent', difficulty: 'hard' },
];

// Number Guessor trivia prompts — keep in sync with src/prompts/numberGuessor.ts
// Edit questions and correctAnswer values here (or in the TS file above).
const NUMBER_GUESSOR_PROMPTS = [
  // Geography
  { id: 'ng_1',  text: 'How many countries are in Europe?',                              correctAnswer: 44, category: 'geography' },
  { id: 'ng_2',  text: 'How many countries are in Africa?',                              correctAnswer: 54, category: 'geography' },
  { id: 'ng_3',  text: 'How many countries are in South America?',                       correctAnswer: 12, category: 'geography' },
  { id: 'ng_4',  text: 'How many countries share a border with Russia?',                 correctAnswer: 14, category: 'geography' },
  { id: 'ng_5',  text: 'How many countries border China?',                               correctAnswer: 14, category: 'geography' },
  { id: 'ng_6',  text: 'How many stars are on the US flag?',                             correctAnswer: 50, category: 'geography' },
  { id: 'ng_7',  text: 'How many stripes are on the US flag?',                           correctAnswer: 13, category: 'geography' },
  { id: 'ng_8',  text: 'How many provinces does Canada have?',                           correctAnswer: 10, category: 'geography' },
  // Sports & Games
  { id: 'ng_9',  text: 'How many squares are on a standard chessboard?',                correctAnswer: 64, category: 'sports' },
  { id: 'ng_10', text: 'How many cards are in a standard deck (no jokers)?',             correctAnswer: 52, category: 'sports' },
  { id: 'ng_11', text: 'How many holes are on a standard golf course?',                  correctAnswer: 18, category: 'sports' },
  { id: 'ng_12', text: 'How many innings are in a standard baseball game?',              correctAnswer:  9, category: 'sports' },
  { id: 'ng_13', text: 'How many seconds are on the NBA shot clock?',                    correctAnswer: 24, category: 'sports' },
  { id: 'ng_14', text: 'How many points is a bullseye worth in darts?',                  correctAnswer: 50, category: 'sports' },
  { id: 'ng_15', text: 'How many players are on the field per team in soccer?',          correctAnswer: 11, category: 'sports' },
  { id: 'ng_16', text: 'How many pins are set up in bowling?',                           correctAnswer: 10, category: 'sports' },
  { id: 'ng_17', text: 'How many events were in the first modern Olympic Games (1896)?', correctAnswer: 43, category: 'sports' },
  { id: 'ng_18', text: 'How many minutes are in a college (NCAA) basketball game?',      correctAnswer: 40, category: 'sports' },
  { id: 'ng_19', text: 'How many countries have won the FIFA World Cup?',                correctAnswer:  8, category: 'sports' },
  // Science
  { id: 'ng_20', text: "What percentage of Earth's surface is covered by water?",        correctAnswer: 71, category: 'science' },
  { id: 'ng_21', text: 'How many days does the Moon take to orbit Earth?',               correctAnswer: 27, category: 'science' },
  { id: 'ng_22', text: 'How many days does Mercury take to orbit the Sun?',              correctAnswer: 88, category: 'science' },
  { id: 'ng_23', text: 'What is the atomic number of gold?',                             correctAnswer: 79, category: 'science' },
  { id: 'ng_24', text: 'How many teeth does a healthy adult human have?',                correctAnswer: 32, category: 'science' },
  { id: 'ng_25', text: 'How many ribs does a human have in total?',                      correctAnswer: 24, category: 'science' },
  { id: 'ng_26', text: 'How many bones are in a human hand?',                            correctAnswer: 27, category: 'science' },
  { id: 'ng_27', text: 'How many bones are in the human spine?',                         correctAnswer: 33, category: 'science' },
  // History & Culture
  { id: 'ng_28', text: 'How many symphonies did Beethoven complete?',                    correctAnswer:  9, category: 'history' },
  { id: 'ng_29', text: 'How many Oscars did Titanic win at the 1998 Academy Awards?',    correctAnswer: 11, category: 'history' },
  { id: 'ng_30', text: 'How many books are in the Harry Potter series?',                 correctAnswer:  7, category: 'history' },
  { id: 'ng_31', text: 'How many seasons did Friends run?',                              correctAnswer: 10, category: 'history' },
  { id: 'ng_32', text: 'How many books are in the New Testament?',                       correctAnswer: 27, category: 'history' },
  { id: 'ng_33', text: 'How many films are in the main Star Wars saga (Episodes I-IX)?', correctAnswer:  9, category: 'history' },
  { id: 'ng_34', text: 'How many seasons did The Office (US) run?',                      correctAnswer:  9, category: 'history' },
  { id: 'ng_35', text: 'How many countries competed in the 1896 Olympic Games?',         correctAnswer: 14, category: 'history' },
  // Math & Misc
  { id: 'ng_36', text: 'How many degrees are in a right angle?',                         correctAnswer: 90, category: 'math' },
  { id: 'ng_37', text: 'How many letters are in the English alphabet?',                  correctAnswer: 26, category: 'math' },
  { id: 'ng_38', text: 'How many weeks are in a year?',                                  correctAnswer: 52, category: 'math' },
  { id: 'ng_39', text: 'How many days are in February during a leap year?',              correctAnswer: 29, category: 'math' },
  { id: 'ng_40', text: 'How many white keys are on a standard piano?',                   correctAnswer: 52, category: 'math' },
];

const PIE_CHARTS_PROMPTS = [
  { id: 'pc1',  text: 'Who is most likely to go viral?' },
  { id: 'pc2',  text: 'Who is most likely to ghost someone?' },
  { id: 'pc3',  text: 'Who is most likely to get rich?' },
  { id: 'pc4',  text: 'Who is most likely to embarrass themselves in public?' },
  { id: 'pc5',  text: 'Who is most likely to survive a zombie apocalypse?' },
  { id: 'pc6',  text: 'Who is most likely to forget their own birthday plans?' },
  { id: 'pc7',  text: 'Who is most likely to become famous for something weird?' },
  { id: 'pc8',  text: 'Who is most likely to start drama by accident?' },
  { id: 'pc9',  text: 'Who is most likely to end up on reality TV?' },
  { id: 'pc10', text: 'Who is most likely to get canceled first?' },
  { id: 'pc11', text: 'Who is most likely to cry at a movie?' },
  { id: 'pc12', text: 'Who is most likely to be the last one to know something?' },
  { id: 'pc13', text: 'Who is most likely to accidentally text the wrong person?' },
  { id: 'pc14', text: 'Who is most likely to show up late to their own event?' },
  { id: 'pc15', text: 'Who is most likely to spend their savings in one weekend?' },
  { id: 'pc16', text: 'Who is most likely to start a cult?' },
  { id: 'pc17', text: 'Who is most likely to be on a podcast?' },
  { id: 'pc18', text: 'Who is most likely to get into an argument with a stranger?' },
  { id: 'pc19', text: 'Who is most likely to forget your birthday?' },
  { id: 'pc20', text: 'Who is most likely to move to another country?' },
  { id: 'pc21', text: 'Who is most likely to invent something?' },
  { id: 'pc22', text: 'Who is most likely to go skydiving?' },
  { id: 'pc23', text: 'Who is most likely to have a secret second life?' },
  { id: 'pc24', text: 'Who is most likely to say something they immediately regret?' },
  { id: 'pc25', text: 'Who is most likely to be the group parent?' },
  { id: 'pc26', text: 'Who is most likely to become a hermit?' },
  { id: 'pc27', text: 'Who is most likely to date someone they met online?' },
  { id: 'pc28', text: 'Who is most likely to quit their job on the spot?' },
  { id: 'pc29', text: 'Who is most likely to win a random game show?' },
  { id: 'pc30', text: 'Who is most likely to be overly dramatic about nothing?' },
];

const POTLUCK_QUESTIONS = [
  // ── EASY (startingPot: 1) ──────────────────────────────────────────────────
  { text: "Which planet is closest to the Sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What sport is Wimbledon associated with?", choices: ["Cricket", "Tennis", "Badminton", "Squash"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "What currency does Japan use?", choices: ["Won", "Yuan", "Baht", "Yen"], correctIndex: 3, difficulty: 'easy', startingPot: 1 },
  { text: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "How many sides does a hexagon have?", choices: ["4", "6", "8", "10"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "Who wrote Romeo and Juliet?", choices: ["Shakespeare", "Dickens", "Chaucer", "Marlowe"], correctIndex: 0, difficulty: 'easy', startingPot: 1 },
  { text: "What is the largest ocean on Earth?", choices: ["Pacific", "Atlantic", "Indian", "Arctic"], correctIndex: 0, difficulty: 'easy', startingPot: 1 },
  { text: "How many planets are in our solar system?", choices: ["7", "8", "9", "10"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "How many days are in a leap year?", choices: ["354", "364", "365", "366"], correctIndex: 3, difficulty: 'easy', startingPot: 1 },
  { text: "What element does 'O' represent on the periodic table?", choices: ["Gold", "Osmium", "Oxygen", "Oxide"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What is the capital of France?", choices: ["London", "Paris", "Madrid", "Rome"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "How many legs does a spider have?", choices: ["4", "6", "8", "10"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What is the largest planet in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "How many sides does a triangle have?", choices: ["2", "3", "4", "5"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What is the capital of the USA?", choices: ["New York", "Boston", "Washington D.C.", "Los Angeles"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "Which country invented pizza?", choices: ["Greece", "France", "Italy", "Spain"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "How many players are on a basketball team on the court?", choices: ["4", "5", "6", "7"], correctIndex: 1, difficulty: 'easy', startingPot: 1 },
  { text: "What year did World War II end?", choices: ["1943", "1944", "1945", "1946"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What is the chemical symbol for gold?", choices: ["Au", "Ag", "Go", "Gd"], correctIndex: 0, difficulty: 'easy', startingPot: 1 },
  { text: "What is the boiling point of water in Celsius?", choices: ["75°C", "90°C", "100°C", "120°C"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "How many players are on a soccer team on the field?", choices: ["9", "10", "11", "13"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What is the capital of Japan?", choices: ["Beijing", "Seoul", "Bangkok", "Tokyo"], correctIndex: 3, difficulty: 'easy', startingPot: 1 },
  { text: "How many months are in a year?", choices: ["10", "11", "12", "13"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },
  { text: "What color is chlorophyll, the pigment in plants?", choices: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, difficulty: 'easy', startingPot: 1 },

  // ── MEDIUM (startingPot: 2) ────────────────────────────────────────────────
  { text: "What's the only mammal that can't jump?", choices: ["Sloth", "Elephant", "Rhino", "Hippo"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "How many hearts does an octopus have?", choices: ["1", "2", "3", "5"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "What year was the first iPhone released?", choices: ["2005", "2007", "2009", "2010"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "Which planet spins on its side?", choices: ["Venus", "Neptune", "Uranus", "Saturn"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "Most abundant gas in Earth's atmosphere?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "A group of flamingos is called a what?", choices: ["Flock", "Flamboyance", "Pride", "Murder"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "What's the smallest country in the world?", choices: ["Monaco", "Nauru", "Vatican City", "San Marino"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "How many strings does a standard violin have?", choices: ["4", "5", "6", "7"], correctIndex: 0, difficulty: 'medium', startingPot: 2 },
  { text: "What is the hardest natural substance on Earth?", choices: ["Quartz", "Diamond", "Titanium", "Graphene"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "How many bones are in the adult human body?", choices: ["180", "206", "230", "256"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "What language has the most native speakers?", choices: ["Mandarin Chinese", "Spanish", "English", "Hindi"], correctIndex: 0, difficulty: 'medium', startingPot: 2 },
  { text: "What is the capital city of Australia?", choices: ["Sydney", "Melbourne", "Adelaide", "Canberra"], correctIndex: 3, difficulty: 'medium', startingPot: 2 },
  { text: "How many teeth do adult humans typically have?", choices: ["28", "30", "32", "36"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "What gas do plants absorb during photosynthesis?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "What is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "Who invented the telephone?", choices: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Samuel Morse"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "How many valves does the human heart have?", choices: ["2", "3", "4", "6"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "What is the largest organ in the human body?", choices: ["Heart", "Brain", "Liver", "Skin"], correctIndex: 3, difficulty: 'medium', startingPot: 2 },
  { text: "What year did the Berlin Wall fall?", choices: ["1985", "1987", "1989", "1991"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "Which planet has the most moons?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "What does DNA stand for?", choices: ["Deoxyribonucleic Acid", "Dynamic Nucleic Array", "Dual Nitrogen Acid", "Dextro Nucleic Acid"], correctIndex: 0, difficulty: 'medium', startingPot: 2 },
  { text: "In which country is the Amazon rainforest mostly located?", choices: ["Colombia", "Peru", "Brazil", "Venezuela"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "What is the most-visited country in the world?", choices: ["USA", "France", "Spain", "China"], correctIndex: 1, difficulty: 'medium', startingPot: 2 },
  { text: "Which country is the largest by land area?", choices: ["China", "Canada", "Russia", "USA"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },
  { text: "How many chambers does the human heart have?", choices: ["2", "3", "4", "6"], correctIndex: 2, difficulty: 'medium', startingPot: 2 },

  // ── HARD (startingPot: 3) ──────────────────────────────────────────────────
  { text: "Which country has the most time zones?", choices: ["Russia", "USA", "France", "China"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "What is the most abundant element in the universe?", choices: ["Helium", "Hydrogen", "Carbon", "Oxygen"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "What is the smallest bone in the human body?", choices: ["Malleus", "Incus", "Stapes", "Pisiform"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "How many chromosomes do humans have?", choices: ["23", "44", "46", "48"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "In what year did the French Revolution begin?", choices: ["1776", "1789", "1799", "1804"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "How many bones does a shark have?", choices: ["0", "12", "50", "200"], correctIndex: 0, difficulty: 'hard', startingPot: 3 },
  { text: "What element has the highest melting point?", choices: ["Carbon", "Platinum", "Titanium", "Tungsten"], correctIndex: 3, difficulty: 'hard', startingPot: 3 },
  { text: "What is the atomic number of carbon?", choices: ["4", "6", "8", "12"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "Which planet has a day longer than its year?", choices: ["Mercury", "Venus", "Mars", "Jupiter"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "How many moons does Mars have?", choices: ["0", "1", "2", "4"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "What is the longest bone in the human body?", choices: ["Tibia", "Humerus", "Femur", "Radius"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "How many letters are in the Hawaiian alphabet?", choices: ["10", "13", "18", "26"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "What is the rarest blood type?", choices: ["O positive", "B negative", "AB negative", "A negative"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "What is the capital of Kazakhstan?", choices: ["Almaty", "Astana", "Bishkek", "Tashkent"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "What is the most common element in the Earth's crust?", choices: ["Silicon", "Oxygen", "Iron", "Aluminum"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "In what year was the Eiffel Tower completed?", choices: ["1879", "1889", "1899", "1909"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "What is the chemical symbol for silver?", choices: ["Si", "Ag", "Au", "Fe"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "How many eyes does a bee have?", choices: ["2", "3", "5", "8"], correctIndex: 2, difficulty: 'hard', startingPot: 3 },
  { text: "What is the name for the fear of long words?", choices: ["Logophobia", "Hippopotomonstrosesquipedaliophobia", "Verbaphobia", "Megalophobia"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
  { text: "What is the only naturally occurring liquid metal at room temperature?", choices: ["Lead", "Mercury", "Gallium", "Cesium"], correctIndex: 1, difficulty: 'hard', startingPot: 3 },
];

module.exports = {
  LIE_DETECTOR_PROMPTS,
  TALENT_SHOW_PROMPTS,
  TALENT_SHOW_TIEBREAK_PROMPTS,
  TALENT_SHOW_FINAL_PROMPTS,
  STAND_OUT_PROMPTS,
  NUMBER_GUESSOR_PROMPTS,
  PIE_CHARTS_PROMPTS,
  POTLUCK_QUESTIONS,
};
