// All game prompts mirrored from src/constants/

const LIE_DETECTOR_PROMPTS = [
  'What is your biggest fear?',
  'What is your most embarrassing moment?',
  "What is something you've never told anyone?",
  'What is your worst habit?',
  'What is a weird thing you secretly like?',
  "What is the worst lie you've told?",
  'What is your biggest red flag?',
  'What is something you regret?',
  'What is the most childish thing you still do?',
  "What is something you've pretended to like but actually hate?",
  "What is the pettiest thing you've ever done?",
  "What is the weirdest thing you do when you're alone?",
];

const TALENT_SHOW_PROMPTS = [
  'Do a stand-up joke about lettuce',
  'Imitate a celebrity accepting an award',
  'Act like you just won the lottery',
  'Pretend you are a dramatic weather reporter',
  'Perform a fake commercial for toothpaste',
  'Make up a song about socks',
  'Do your best evil villain laugh',
  'Pretend you are a magician whose trick just failed',
  'Act out your morning routine in 20 seconds',
  'Narrate your life like a nature documentary',
  'Do an impression of a robot learning to dance',
  'Pretend you are a chef describing plain water',
];

const STAND_OUT_PROMPTS = [
  // Easy
  { id: 'so_e1',  text: 'Name a fruit',                            difficulty: 'easy' },
  { id: 'so_e2',  text: 'Name a color',                            difficulty: 'easy' },
  { id: 'so_e3',  text: 'Name a fast food chain',                  difficulty: 'easy' },
  { id: 'so_e4',  text: 'Name a pet',                              difficulty: 'easy' },
  { id: 'so_e5',  text: 'Name a movie genre',                      difficulty: 'easy' },
  { id: 'so_e6',  text: 'Name a sport',                            difficulty: 'easy' },
  { id: 'so_e7',  text: 'Name a country',                          difficulty: 'easy' },
  { id: 'so_e8',  text: 'Name a superhero',                        difficulty: 'easy' },
  { id: 'so_e9',  text: 'Name a school subject',                   difficulty: 'easy' },
  { id: 'so_e10', text: 'Name a breakfast food',                   difficulty: 'easy' },
  { id: 'so_e11', text: 'Name a soft drink',                       difficulty: 'easy' },
  { id: 'so_e12', text: 'Name a social media app',                 difficulty: 'easy' },
  { id: 'so_e13', text: 'Name a pizza topping',                    difficulty: 'easy' },
  { id: 'so_e14', text: 'Name a type of music',                    difficulty: 'easy' },
  { id: 'so_e15', text: 'Name a type of car',                      difficulty: 'easy' },
  // Medium
  { id: 'so_m1',  text: 'Name something you bring to a party',            difficulty: 'medium' },
  { id: 'so_m2',  text: 'Name something people lose all the time',        difficulty: 'medium' },
  { id: 'so_m3',  text: 'Name a reason someone would be late',            difficulty: 'medium' },
  { id: 'so_m4',  text: 'Name something you should not forget on vacation', difficulty: 'medium' },
  { id: 'so_m5',  text: 'Name something people do when they are nervous',  difficulty: 'medium' },
  { id: 'so_m6',  text: 'Name something you always find at a birthday party', difficulty: 'medium' },
  { id: 'so_m7',  text: 'Name something you check before leaving the house', difficulty: 'medium' },
  { id: 'so_m8',  text: 'Name something that always ends up on the floor', difficulty: 'medium' },
  { id: 'so_m9',  text: 'Name something you do when you are bored',       difficulty: 'medium' },
  { id: 'so_m10', text: 'Name a reason someone would cancel plans',       difficulty: 'medium' },
  { id: 'so_m11', text: 'Name something you eat when you are sad',        difficulty: 'medium' },
  { id: 'so_m12', text: 'Name something people say they will do but never do', difficulty: 'medium' },
  { id: 'so_m13', text: 'Name something you would bring to a deserted island', difficulty: 'medium' },
  { id: 'so_m14', text: 'Name something people argue about at family dinners', difficulty: 'medium' },
  { id: 'so_m15', text: 'Name something you do right before bed',         difficulty: 'medium' },
  // Hard
  { id: 'so_h1',  text: 'Name something people lie about',                difficulty: 'hard' },
  { id: 'so_h2',  text: 'Name a reason someone gets ghosted',             difficulty: 'hard' },
  { id: 'so_h3',  text: 'Name something awkward to say on a first date',  difficulty: 'hard' },
  { id: 'so_h4',  text: 'Name something people pretend to understand',    difficulty: 'hard' },
  { id: 'so_h5',  text: "Name something you would not want your parents to find", difficulty: 'hard' },
  { id: 'so_h6',  text: 'Name a red flag in a new friend',                difficulty: 'hard' },
  { id: 'so_h7',  text: 'Name something people do but will not admit',    difficulty: 'hard' },
  { id: 'so_h8',  text: 'Name a reason someone unfollows you',            difficulty: 'hard' },
  { id: 'so_h9',  text: 'Name something people judge you for silently',   difficulty: 'hard' },
  { id: 'so_h10', text: 'Name something that ruins a first impression',   difficulty: 'hard' },
  { id: 'so_h11', text: 'Name a lie you tell yourself',                   difficulty: 'hard' },
  { id: 'so_h12', text: 'Name something people fake laugh at',            difficulty: 'hard' },
  { id: 'so_h13', text: 'Name something you hide from your friends',      difficulty: 'hard' },
  { id: 'so_h14', text: 'Name a personality trait people deny having',    difficulty: 'hard' },
  { id: 'so_h15', text: 'Name something you do that would surprise people', difficulty: 'hard' },
];

// Number Guessor trivia prompts — keep in sync with src/prompts/numberGuessor.ts
// Edit questions and correctAnswer values here (or in the TS file above).
const NUMBER_GUESSOR_PROMPTS = [
  // Geography
  { id: 'ng_1',  text: 'How many countries are in Europe?',                              correctAnswer: 44, category: 'geography' },
  { id: 'ng_2',  text: 'How many countries are in Africa?',                              correctAnswer: 54, category: 'geography' },
  { id: 'ng_3',  text: 'How many countries are in South America?',                       correctAnswer: 12, category: 'geography' },
  { id: 'ng_4',  text: 'How many countries share a border with Russia?',                 correctAnswer: 14, category: 'geography' },
  { id: 'ng_5',  text: 'How many countries border China?',                               correctAnswer: 14, category: 'geography' },
  { id: 'ng_6',  text: 'How many stars are on the US flag?',                             correctAnswer: 50, category: 'geography' },
  { id: 'ng_7',  text: 'How many stripes are on the US flag?',                           correctAnswer: 13, category: 'geography' },
  { id: 'ng_8',  text: 'How many provinces does Canada have?',                           correctAnswer: 10, category: 'geography' },
  // Sports & Games
  { id: 'ng_9',  text: 'How many squares are on a standard chessboard?',                correctAnswer: 64, category: 'sports' },
  { id: 'ng_10', text: 'How many cards are in a standard deck (no jokers)?',             correctAnswer: 52, category: 'sports' },
  { id: 'ng_11', text: 'How many holes are on a standard golf course?',                  correctAnswer: 18, category: 'sports' },
  { id: 'ng_12', text: 'How many innings are in a standard baseball game?',              correctAnswer:  9, category: 'sports' },
  { id: 'ng_13', text: 'How many seconds are on the NBA shot clock?',                    correctAnswer: 24, category: 'sports' },
  { id: 'ng_14', text: 'How many points is a bullseye worth in darts?',                  correctAnswer: 50, category: 'sports' },
  { id: 'ng_15', text: 'How many players are on the field per team in soccer?',          correctAnswer: 11, category: 'sports' },
  { id: 'ng_16', text: 'How many pins are set up in bowling?',                           correctAnswer: 10, category: 'sports' },
  { id: 'ng_17', text: 'How many events were in the first modern Olympic Games (1896)?', correctAnswer: 43, category: 'sports' },
  { id: 'ng_18', text: 'How many minutes are in a college (NCAA) basketball game?',      correctAnswer: 40, category: 'sports' },
  { id: 'ng_19', text: 'How many countries have won the FIFA World Cup?',                correctAnswer:  8, category: 'sports' },
  // Science
  { id: 'ng_20', text: "What percentage of Earth's surface is covered by water?",        correctAnswer: 71, category: 'science' },
  { id: 'ng_21', text: 'How many days does the Moon take to orbit Earth?',               correctAnswer: 27, category: 'science' },
  { id: 'ng_22', text: 'How many days does Mercury take to orbit the Sun?',              correctAnswer: 88, category: 'science' },
  { id: 'ng_23', text: 'What is the atomic number of gold?',                             correctAnswer: 79, category: 'science' },
  { id: 'ng_24', text: 'How many teeth does a healthy adult human have?',                correctAnswer: 32, category: 'science' },
  { id: 'ng_25', text: 'How many ribs does a human have in total?',                      correctAnswer: 24, category: 'science' },
  { id: 'ng_26', text: 'How many bones are in a human hand?',                            correctAnswer: 27, category: 'science' },
  { id: 'ng_27', text: 'How many bones are in the human spine?',                         correctAnswer: 33, category: 'science' },
  // History & Culture
  { id: 'ng_28', text: 'How many symphonies did Beethoven complete?',                    correctAnswer:  9, category: 'history' },
  { id: 'ng_29', text: 'How many Oscars did Titanic win at the 1998 Academy Awards?',    correctAnswer: 11, category: 'history' },
  { id: 'ng_30', text: 'How many books are in the Harry Potter series?',                 correctAnswer:  7, category: 'history' },
  { id: 'ng_31', text: 'How many seasons did Friends run?',                              correctAnswer: 10, category: 'history' },
  { id: 'ng_32', text: 'How many books are in the New Testament?',                       correctAnswer: 27, category: 'history' },
  { id: 'ng_33', text: 'How many films are in the main Star Wars saga (Episodes I-IX)?', correctAnswer:  9, category: 'history' },
  { id: 'ng_34', text: 'How many seasons did The Office (US) run?',                      correctAnswer:  9, category: 'history' },
  { id: 'ng_35', text: 'How many countries competed in the 1896 Olympic Games?',         correctAnswer: 14, category: 'history' },
  // Math & Misc
  { id: 'ng_36', text: 'How many degrees are in a right angle?',                         correctAnswer: 90, category: 'math' },
  { id: 'ng_37', text: 'How many letters are in the English alphabet?',                  correctAnswer: 26, category: 'math' },
  { id: 'ng_38', text: 'How many weeks are in a year?',                                  correctAnswer: 52, category: 'math' },
  { id: 'ng_39', text: 'How many days are in February during a leap year?',              correctAnswer: 29, category: 'math' },
  { id: 'ng_40', text: 'How many white keys are on a standard piano?',                   correctAnswer: 52, category: 'math' },
];

const PIE_CHARTS_PROMPTS = [
  { id: 'pc1',  text: 'Who is most likely to go viral?' },
  { id: 'pc2',  text: 'Who is most likely to ghost someone?' },
  { id: 'pc3',  text: 'Who is most likely to get rich?' },
  { id: 'pc4',  text: 'Who is most likely to embarrass themselves in public?' },
  { id: 'pc5',  text: 'Who is most likely to survive a zombie apocalypse?' },
  { id: 'pc6',  text: 'Who is most likely to forget their own birthday plans?' },
  { id: 'pc7',  text: 'Who is most likely to become famous for something weird?' },
  { id: 'pc8',  text: 'Who is most likely to start drama by accident?' },
  { id: 'pc9',  text: 'Who is most likely to end up on reality TV?' },
  { id: 'pc10', text: 'Who is most likely to get canceled first?' },
  { id: 'pc11', text: 'Who is most likely to cry at a movie?' },
  { id: 'pc12', text: 'Who is most likely to be the last one to know something?' },
  { id: 'pc13', text: 'Who is most likely to accidentally text the wrong person?' },
  { id: 'pc14', text: 'Who is most likely to show up late to their own event?' },
  { id: 'pc15', text: 'Who is most likely to spend their savings in one weekend?' },
  { id: 'pc16', text: 'Who is most likely to start a cult?' },
  { id: 'pc17', text: 'Who is most likely to be on a podcast?' },
  { id: 'pc18', text: 'Who is most likely to get into an argument with a stranger?' },
  { id: 'pc19', text: 'Who is most likely to forget your birthday?' },
  { id: 'pc20', text: 'Who is most likely to move to another country?' },
  { id: 'pc21', text: 'Who is most likely to invent something?' },
  { id: 'pc22', text: 'Who is most likely to go skydiving?' },
  { id: 'pc23', text: 'Who is most likely to have a secret second life?' },
  { id: 'pc24', text: 'Who is most likely to say something they immediately regret?' },
  { id: 'pc25', text: 'Who is most likely to be the group parent?' },
  { id: 'pc26', text: 'Who is most likely to become a hermit?' },
  { id: 'pc27', text: 'Who is most likely to date someone they met online?' },
  { id: 'pc28', text: 'Who is most likely to quit their job on the spot?' },
  { id: 'pc29', text: 'Who is most likely to win a random game show?' },
  { id: 'pc30', text: 'Who is most likely to be overly dramatic about nothing?' },
];

module.exports = {
  LIE_DETECTOR_PROMPTS,
  TALENT_SHOW_PROMPTS,
  STAND_OUT_PROMPTS,
  NUMBER_GUESSOR_PROMPTS,
  PIE_CHARTS_PROMPTS,
};
