// ─────────────────────────────────────────────────────────────────────────────
// Lie Detector — Prompt Bank
// Each prompt asks the speaker to give TWO statements. One is true, one is a
// lie. The group votes to find which statement is the lie.
// ─────────────────────────────────────────────────────────────────────────────

export const LIE_DETECTOR_PROMPTS: string[] = [
  "Two favorite foods",
  "Two favorite snacks",
  "Two favorite drinks",
  "Two favorite desserts",
  "Two favorite restaurants",
  "Two favorite fast food places",
  "Two favorite cuisines",
  "Two favorite meals you eat often",
  "Two favorite things to cook",
  "Two foods you hate",

  "Two favorite music artists",
  "Two favorite songs",
  "Two songs you know all the lyrics to",
  "Two songs you had on repeat",
  "Two favorite albums",
  "Two artists you’ve seen live",
  "Two concerts you’ve been to",
  "Two artists you don’t like",
  "Two songs that make you emotional",
  "Two songs that hype you up",

  "Two favorite movies",
  "Two favorite TV shows",
  "Two shows you binged",
  "Two movies you’ve watched multiple times",
  "Two favorite actors",
  "Two favorite actresses",
  "Two favorite characters",
  "Two movies you didn’t like",
  "Two shows you stopped watching",
  "Two movies that made you emotional",

  "Two favorite cities",
  "Two places you’ve traveled to",
  "Two places you want to visit",
  "Two favorite vacation spots",
  "Two countries you’ve been to",
  "Two places you didn’t like",
  "Two trips you remember well",
  "Two road trips you’ve taken",
  "Two places you’d move to",
  "Two places you miss",

  "Two favorite classes you’ve taken",
  "Two classes you didn’t like",
  "Two teachers you remember",
  "Two subjects you’re good at",
  "Two subjects you struggled with",
  "Two school memories",
  "Two embarrassing moments in school",
  "Two times you got in trouble at school",
  "Two classes you skipped",
  "Two projects you worked on",

  "Two pets you’ve had",
  "Two pets you want",
  "Two animals you like",
  "Two animals you’re scared of",
  "Two animals you’ve seen in real life",
  "Two unusual animals you like",
  "Two pets you remember well",
  "Two animals you’d never want",
  "Two animals you’ve interacted with",
  "Two animals you think are overrated",

  "Two favorite colors",
  "Two colors you wear often",
  "Two colors you don’t like",
  "Two colors you associate with yourself",
  "Two colors you use a lot",
  "Two color combinations you like",
  "Two colors you avoid",
  "Two colors in your room",
  "Two colors you notice often",
  "Two colors you think look good together",

  "Two favorite childhood memories",
  "Two memories with friends",
  "Two memories with family",
  "Two times you laughed a lot",
  "Two times you felt embarrassed",
  "Two times you got in big trouble",
  "Two times you were really happy",
  "Two times you were stressed",
  "Two times you were surprised",
  "Two memories you think about a lot",

  "Two times you did something you regretted",
  "Two mistakes you made",
  "Two things you wish you did differently",
  "Two times you got caught doing something",
  "Two times you lied",
  "Two awkward situations you were in",
  "Two times things didn’t go as planned",
  "Two things you messed up",
  "Two times you said the wrong thing",
  "Two times you misunderstood something",

  "Two things you bought recently",
  "Two things you want to buy",
  "Two things you regret buying",
  "Two things you use every day",
  "Two things you always carry",
  "Two things in your room",
  "Two things on your desk",
  "Two things in your bag",
  "Two things in your fridge",
  "Two things you lost recently",

  "Two hobbies you have",
  "Two things you do in your free time",
  "Two things you’re good at",
  "Two things you’re bad at",
  "Two things you enjoy doing",
  "Two things you don’t enjoy",
  "Two things you’ve tried",
  "Two things you want to try",
  "Two skills you have",
  "Two skills you want",

  "Two apps you use the most",
  "Two apps you waste time on",
  "Two apps you check daily",
  "Two things you search online often",
  "Two things you watch on your phone",
  "Two things in your camera roll",
  "Two things you screenshot",
  "Two things you posted",
  "Two things you almost posted",
  "Two things you deleted",

  "Two people you talk to often",
  "Two people you text regularly",
  "Two types of people you like",
  "Two types of people you don’t like",
  "Two traits you like in people",
  "Two traits you don’t like",
  "Two things you talk about a lot",
  "Two things you avoid talking about",
  "Two conversations you remember",
  "Two things someone said to you",

  "Two things that make you laugh",
  "Two things that annoy you",
  "Two things that stress you out",
  "Two things that relax you",
  "Two things that make you happy",
  "Two things that make you nervous",
  "Two things that excite you",
  "Two things that frustrate you",
  "Two things that calm you down",
  "Two things that motivate you",

  "Two things you did today",
  "Two things you did yesterday",
  "Two things you did this week",
  "Two things you forgot recently",
  "Two things you realized recently",
  "Two things you learned recently",
  "Two things you tried recently",
  "Two things you started recently",
  "Two things you finished recently",
  "Two things you avoided recently",

  "Two outfits you like",
  "Two things you wore recently",
  "Two clothing items you wear often",
  "Two brands you like",
  "Two brands you don’t like",
  "Two shoes you wear often",
  "Two things in your closet",
  "Two outfits you remember wearing",
  "Two things you wouldn’t wear",
  "Two styles you like",

  "Two games you’ve played",
  "Two favorite games",
  "Two games you’re good at",
  "Two games you’re bad at",
  "Two games you played recently",
  "Two games you stopped playing",
  "Two games you enjoy",
  "Two games you don’t like",
  "Two games you used to play",
  "Two games you want to try",
  "Two things you’re very picky about",
"Two things you don’t care about at all",
"Two things you always notice about a place",
"Two things you ignore most of the time",
"Two things you’re surprisingly good at",
"Two things people assume about you",
"Two things people get wrong about you",
"Two things you take seriously",
"Two things you don’t take seriously",
"Two things you’re particular about",

"Two habits you have that others notice",
"Two habits you wish you didn’t have",
"Two habits you’ve had for a long time",
"Two things you do without realizing",
"Two things you do when you’re alone",
"Two things you do when no one’s watching",
"Two things you always do the same way",
"Two small things that bother you",
"Two small things you enjoy",
"Two things you always fix or adjust",

"Two things you always notice about people",
"Two things that make someone likable to you",
"Two things that make someone annoying to you",
"Two types of humor you like",
"Two types of humor you don’t like",
"Two things that make a conversation interesting",
"Two things that make a conversation awkward",
"Two things you tend to remember about people",
"Two things you forget about people",
"Two things you judge quickly",

"Two things you’re competitive about",
"Two things you don’t care about winning",
"Two things you take pride in",
"Two things you’re insecure about",
"Two things you’re confident in",
"Two things you avoid doing in front of people",
"Two things you don’t mind doing in front of people",
"Two things you’d rather not admit",
"Two things you don’t mind admitting",
"Two things you’ve changed your mind about",

"Two things you think are overrated",
"Two things you think are underrated",
"Two trends you don’t understand",
"Two trends you like",
"Two things you think people overdo",
"Two things you think people underdo",
"Two things you think are unnecessary",
"Two things you think are essential",
"Two things you think are overhyped",
"Two things you think deserve more attention",

"Two things you like about mornings",
"Two things you like about nights",
"Two things you dislike about mornings",
"Two things you dislike about nights",
"Two things you do when you can’t sleep",
"Two things you think about before sleeping",
"Two things you notice when you wake up",
"Two things you do first in the morning",
"Two things you do last before bed",
"Two things that affect your mood quickly",

"Two things you do when you’re bored alone",
"Two things you do when you’re bored with friends",
"Two things you do to pass time",
"Two things you do to avoid being bored",
"Two things you do when plans fall through",
"Two things you do when you have nothing to do",
"Two things you do to stay entertained",
"Two things you do to distract yourself",
"Two things you do when you don’t feel like doing anything",
"Two things you do when you want to reset",

"Two things you’re bad at explaining",
"Two things you’re good at explaining",
"Two things you overexplain",
"Two things you keep short",
"Two things you talk about easily",
"Two things you struggle to talk about",
"Two things you say often without thinking",
"Two things you rarely say",
"Two things you hesitate before saying",
"Two things you say confidently",

"Two things you notice about yourself",
"Two things you’ve improved about yourself",
"Two things you still want to improve",
"Two things you like about your personality",
"Two things you don’t like about your personality",
"Two things that make you feel like yourself",
"Two things that feel out of character for you",
"Two things you’ve realized about yourself",
"Two things you’ve learned about yourself",
"Two things that define your personality",

"Two things you always think about before deciding",
"Two things you decide quickly on",
"Two things you overthink",
"Two things you don’t think twice about",
"Two things you regret overthinking",
"Two things you act on immediately",
"Two things you delay deciding on",
"Two things you trust your instincts on",
"Two things you second guess",
"Two things you feel sure about"
];