// ─────────────────────────────────────────────────────────────────────────────
// Number Guessor — Trivia Prompt Bank
//
// Edit this file in VS Code to update questions and answers.
// Rules:
//   • correctAnswer must be ≤ 100
//   • Prefer answers in the 8–90 range (estimatable, not trivially obvious)
// ─────────────────────────────────────────────────────────────────────────────

export type NumberPromptCategory = 'geography' | 'sports' | 'science' | 'history' | 'math';

export type NumberPrompt = {
  id: string;
  text: string;
  correctAnswer: number;
  category: string;
};

export const NUMBER_GUESSOR_PROMPTS: NumberPrompt[] = [
  // Geography
  { id: 'ng_41',  text: 'How many UNESCO World Heritage Sites are in Italy?',                          correctAnswer: 58, category: 'geography' },
  { id: 'ng_42',  text: 'How many countries does the Amazon River flow through?',                      correctAnswer:  9, category: 'geography' },
  { id: 'ng_43',  text: 'How many time zones does Russia span?',                                       correctAnswer: 11, category: 'geography' },
  { id: 'ng_44',  text: 'How many countries are landlocked in Africa?',                                correctAnswer: 16, category: 'geography' },
  { id: 'ng_45',  text: 'How many US states border the Gulf of Mexico?',                               correctAnswer:  5, category: 'geography' },
  { id: 'ng_46',  text: 'How many countries use the Euro as their official currency?',                 correctAnswer: 20, category: 'geography' },
  { id: 'ng_47',  text: 'How many countries are in Central America?',                                  correctAnswer:  7, category: 'geography' },
  { id: 'ng_48',  text: 'How many US states touch the Pacific Ocean?',                                 correctAnswer:  5, category: 'geography' },
  { id: 'ng_49',  text: 'How many countries does the Nile River flow through?',                        correctAnswer: 11, category: 'geography' },
  { id: 'ng_50',  text: 'How many sovereign countries are in the Caribbean?',                          correctAnswer: 13, category: 'geography' },
  { id: 'ng_51',  text: 'How many US states have only straight-line borders on all sides?',            correctAnswer:  1, category: 'geography' },
  { id: 'ng_52',  text: 'How many countries border France (including overseas territories)?',          correctAnswer: 11, category: 'geography' },
  { id: 'ng_53',  text: 'How many of the Great Lakes are entirely within the United States?',          correctAnswer:  1, category: 'geography' },
  { id: 'ng_54',  text: 'How many countries make up the United Kingdom?',                              correctAnswer:  4, category: 'geography' },
  { id: 'ng_55',  text: 'How many active volcanoes does Indonesia have?',                              correctAnswer: 76, category: 'geography' },
  { id: 'ng_56',  text: 'How many US states are larger in area than Germany?',                         correctAnswer: 13, category: 'geography' },
  { id: 'ng_57',  text: 'How many countries have a coastline on the Mediterranean Sea?',               correctAnswer: 21, category: 'geography' },
  { id: 'ng_58',  text: 'How many US states share a border with Canada?',                              correctAnswer: 13, category: 'geography' },
  { id: 'ng_59',  text: 'How many countries border Brazil?',                                           correctAnswer: 10, category: 'geography' },
  { id: 'ng_60',  text: 'How many countries are in the Arabian Peninsula?',                            correctAnswer:  7, category: 'geography' },
  { id: 'ng_61',  text: 'How many named Alpine peaks exceed 4,000 meters?',                            correctAnswer: 48, category: 'geography' },
  { id: 'ng_62',  text: 'How many countries share a border with India?',                               correctAnswer:  6, category: 'geography' },
  { id: 'ng_63',  text: 'How many US national parks are there?',                                       correctAnswer: 63, category: 'geography' },
  { id: 'ng_64',  text: 'How many countries are in Oceania?',                                          correctAnswer: 14, category: 'geography' },
  { id: 'ng_65',  text: 'How many countries border Germany?',                                          correctAnswer:  9, category: 'geography' },

  // Science & Body
  { id: 'ng_66',  text: 'How many elements are in the first period of the periodic table?',            correctAnswer:  2, category: 'science' },
  { id: 'ng_67',  text: 'How many chambers does a human heart have?',                                  correctAnswer:  4, category: 'science' },
  { id: 'ng_68',  text: 'How many moons does Mars have?',                                              correctAnswer:  2, category: 'science' },
  { id: 'ng_69',  text: 'How many chromosomes do humans have?',                                        correctAnswer: 46, category: 'science' },
  { id: 'ng_70',  text: 'How many percent of Earth\'s atmosphere is nitrogen?',                        correctAnswer: 78, category: 'science' },
  { id: 'ng_71',  text: 'How many eyes does a bee have?',                                              correctAnswer:  5, category: 'science' },
  { id: 'ng_72',  text: 'How many pairs of chromosomes do dogs have?',                                 correctAnswer: 39, category: 'science' },
  { id: 'ng_73',  text: 'How many legs does a lobster have?',                                          correctAnswer: 10, category: 'science' },
  { id: 'ng_74',  text: 'How many elements were on Mendeleev\'s original periodic table?',             correctAnswer: 63, category: 'science' },
  { id: 'ng_75',  text: 'How many amino acids are essential for humans?',                              correctAnswer:  9, category: 'science' },
  { id: 'ng_76',  text: 'How many recognized dwarf planets are in our solar system?',                  correctAnswer:  5, category: 'science' },
  { id: 'ng_77',  text: 'How many vertebrae does a giraffe have in its neck?',                         correctAnswer:  7, category: 'science' },
  { id: 'ng_78',  text: 'How many percent of DNA do humans share with bananas?',                       correctAnswer: 60, category: 'science' },
  { id: 'ng_79',  text: 'How many degrees does the Earth\'s axis tilt?',                              correctAnswer: 23, category: 'science' },
  { id: 'ng_80',  text: 'How many bones are in a human foot?',                                         correctAnswer: 26, category: 'science' },
  { id: 'ng_81',  text: 'How many pairs of ribs do humans have?',                                      correctAnswer: 12, category: 'science' },
  { id: 'ng_82',  text: 'How many known moons does Jupiter have?',                                     correctAnswer: 95, category: 'science' },
  { id: 'ng_83',  text: 'How many percent of Earth\'s species live in the ocean?',                    correctAnswer: 80, category: 'science' },
  { id: 'ng_84',  text: 'How many percent of the human body is water?',                               correctAnswer: 60, category: 'science' },
  { id: 'ng_85',  text: 'How many muscles does the human eye use to move?',                            correctAnswer:  6, category: 'science' },
  { id: 'ng_86',  text: 'How many times does the average person blink per minute?',                   correctAnswer: 15, category: 'science' },
  { id: 'ng_87',  text: 'How many bones make up the human skull?',                                     correctAnswer: 22, category: 'science' },
  { id: 'ng_88',  text: 'How many percent of Earth\'s land is desert?',                               correctAnswer: 33, category: 'science' },
  { id: 'ng_89',  text: 'How many elements on the periodic table are gases at room temperature?',      correctAnswer: 11, category: 'science' },
  { id: 'ng_90',  text: 'How many minutes does it take sunlight to reach Earth?',                     correctAnswer:  8, category: 'science' },

  // History & Civilization
  { id: 'ng_91',  text: 'How many US presidents have been assassinated?',                              correctAnswer:  4, category: 'history' },
  { id: 'ng_92',  text: 'How many wives did King Henry VIII have?',                                    correctAnswer:  6, category: 'history' },
  { id: 'ng_93',  text: 'How many men signed the US Declaration of Independence?',                    correctAnswer: 56, category: 'history' },
  { id: 'ng_94',  text: 'How many years was Nelson Mandela imprisoned?',                               correctAnswer: 27, category: 'history' },
  { id: 'ng_95',  text: 'How many amendments does the US Constitution have?',                          correctAnswer: 27, category: 'history' },
  { id: 'ng_96',  text: 'How many US states were in the original union?',                              correctAnswer: 13, category: 'history' },
  { id: 'ng_97',  text: 'How many years did Cleopatra live?',                                          correctAnswer: 39, category: 'history' },
  { id: 'ng_98',  text: 'How many countries declared independence in 1960 (the "Year of Africa")?',   correctAnswer: 17, category: 'history' },
  { id: 'ng_99',  text: 'How many voyages did Christopher Columbus make to the Americas?',             correctAnswer:  4, category: 'history' },
  { id: 'ng_100', text: 'How many US presidents served two full terms?',                               correctAnswer: 21, category: 'history' },
  { id: 'ng_101', text: 'How many years did the Cold War last?',                                       correctAnswer: 44, category: 'history' },
  { id: 'ng_102', text: 'How many children did Queen Victoria have?',                                  correctAnswer:  9, category: 'history' },
  { id: 'ng_103', text: 'How many years passed between the first and second World Wars?',              correctAnswer: 21, category: 'history' },
  { id: 'ng_104', text: 'How many years was the Berlin Wall standing?',                                correctAnswer: 28, category: 'history' },
  { id: 'ng_105', text: 'How many plagues are described in the Book of Exodus?',                       correctAnswer: 10, category: 'history' },
  { id: 'ng_106', text: 'How many countries were original members of NATO?',                           correctAnswer: 12, category: 'history' },
  { id: 'ng_107', text: 'How many years did Prohibition last in the United States?',                   correctAnswer: 13, category: 'history' },
  { id: 'ng_108', text: 'How many years did the Hundred Years\' War actually last beyond 100?',        correctAnswer: 16, category: 'history' },
  { id: 'ng_109', text: 'How many US presidents have been impeached?',                                 correctAnswer:  3, category: 'history' },
  { id: 'ng_110', text: 'How many years older is the Colosseum than the Eiffel Tower (roughly)?',     correctAnswer: 83, category: 'history' },
  { id: 'ng_111', text: 'How many countries were founding members of the United Nations?',             correctAnswer: 51, category: 'history' },
  { id: 'ng_112', text: 'How many years did the Byzantine Empire last (roughly in centuries × 10)?',  correctAnswer: 90, category: 'history' },
  { id: 'ng_113', text: 'How many Apollo missions successfully landed on the Moon?',                   correctAnswer:  6, category: 'history' },
  { id: 'ng_114', text: 'How many years after Columbus did the Pilgrims land at Plymouth?',            correctAnswer: 28, category: 'history' },
  { id: 'ng_115', text: 'How many countries participated in the first modern Olympics in 1896?',       correctAnswer: 14, category: 'history' },

  // Sports & Games
  { id: 'ng_116', text: 'How many players are on an NFL roster on game day?',                          correctAnswer: 48, category: 'sports' },
  { id: 'ng_117', text: 'How many players are in an NHL team\'s active roster?',                       correctAnswer: 23, category: 'sports' },
  { id: 'ng_118', text: 'How many meters is an Olympic swimming pool?',                                correctAnswer: 50, category: 'sports' },
  { id: 'ng_119', text: 'How many points do you need to win a set in tennis (minimum)?',               correctAnswer: 24, category: 'sports' },
  { id: 'ng_120', text: 'How many rings are on the Olympic flag?',                                     correctAnswer:  5, category: 'sports' },
  { id: 'ng_121', text: 'How many feet long is a standard basketball court?',                          correctAnswer: 94, category: 'sports' },
  { id: 'ng_122', text: 'How many teams are in the NFL?',                                              correctAnswer: 32, category: 'sports' },
  { id: 'ng_123', text: 'How many games are in an NBA regular season per team?',                       correctAnswer: 82, category: 'sports' },
  { id: 'ng_124', text: 'How many squares does a Rubik\'s Cube have in total?',                       correctAnswer: 54, category: 'sports' },
  { id: 'ng_125', text: 'How many world chess championships did Garry Kasparov win?',                  correctAnswer:  6, category: 'sports' },
  { id: 'ng_126', text: 'How many minutes is a field hockey match?',                                   correctAnswer: 60, category: 'sports' },
  { id: 'ng_127', text: 'How many seconds is an NFL play clock?',                                      correctAnswer: 40, category: 'sports' },
  { id: 'ng_128', text: 'How many personal fouls foul out an NBA player?',                             correctAnswer:  6, category: 'sports' },
  { id: 'ng_129', text: 'How many feet high is an NBA basket?',                                        correctAnswer: 10, category: 'sports' },
  { id: 'ng_130', text: 'How many players are on a baseball field per team?',                          correctAnswer:  9, category: 'sports' },
  { id: 'ng_131', text: 'How many total rounds are in amateur boxing?',                                correctAnswer:  3, category: 'sports' },
  { id: 'ng_132', text: 'How many players are on the ice per team in hockey?',                         correctAnswer:  6, category: 'sports' },
  { id: 'ng_133', text: 'How many yards are in an American football end zone?',                        correctAnswer: 10, category: 'sports' },
  { id: 'ng_134', text: 'How many countries competed in the first FIFA World Cup in 1930?',            correctAnswer: 13, category: 'sports' },
  { id: 'ng_135', text: 'How many points is a touchdown worth in American football?',                  correctAnswer:  6, category: 'sports' },
  { id: 'ng_136', text: 'How many players are on a volleyball team on the court?',                     correctAnswer:  6, category: 'sports' },
  { id: 'ng_137', text: 'How many Grand Slam titles did Serena Williams win?',                         correctAnswer: 23, category: 'sports' },
  { id: 'ng_138', text: 'How many minutes does each half of a soccer match last?',                     correctAnswer: 45, category: 'sports' },
  { id: 'ng_139', text: 'How many points is a field goal worth in American football?',                 correctAnswer:  3, category: 'sports' },
  { id: 'ng_140', text: 'How many teams compete in the FIFA World Cup finals tournament?',             correctAnswer: 32, category: 'sports' },

  // Nature & Animals
  { id: 'ng_141', text: 'How many hearts does an octopus have?',                                       correctAnswer:  3, category: 'nature' },
  { id: 'ng_142', text: 'How many legs does a spider have?',                                           correctAnswer:  8, category: 'nature' },
  { id: 'ng_143', text: 'How many species of big cat exist?',                                          correctAnswer:  7, category: 'nature' },
  { id: 'ng_144', text: 'How many days does a worker bee live in summer?',                             correctAnswer: 45, category: 'nature' },
  { id: 'ng_145', text: 'How many species of penguin exist?',                                          correctAnswer: 18, category: 'nature' },
  { id: 'ng_146', text: 'How many percent of the ocean floor has been mapped in detail?',              correctAnswer: 20, category: 'nature' },
  { id: 'ng_147', text: 'How many years can a koi fish live?',                                         correctAnswer: 35, category: 'nature' },
  { id: 'ng_148', text: 'How many toes does an ostrich have on each foot?',                            correctAnswer:  2, category: 'nature' },
  { id: 'ng_149', text: 'How many hours a day does a koala sleep?',                                    correctAnswer: 22, category: 'nature' },
  { id: 'ng_150', text: 'How many percent of the world\'s oxygen is produced by the Amazon rainforest?', correctAnswer: 20, category: 'nature' },
  { id: 'ng_151', text: 'How many species of bird-of-paradise exist?',                                 correctAnswer: 45, category: 'nature' },
  { id: 'ng_152', text: 'How many toes does a three-toed sloth have in total?',                        correctAnswer:  9, category: 'nature' },
  { id: 'ng_153', text: 'How many pounds can a bald eagle carry in flight?',                           correctAnswer:  4, category: 'nature' },
  { id: 'ng_154', text: 'How many gallons of milk does a dairy cow produce per day?',                  correctAnswer:  7, category: 'nature' },
  { id: 'ng_155', text: 'How many years can a whale shark live?',                                      correctAnswer: 70, category: 'nature' },
  { id: 'ng_156', text: 'How many known species of frog are there (approximately in thousands)?',      correctAnswer:  7, category: 'nature' },
  { id: 'ng_157', text: 'How many percent of the world\'s fresh water is in the Amazon River?',        correctAnswer: 20, category: 'nature' },
  { id: 'ng_158', text: 'How many miles per hour can a peregrine falcon dive?',                        correctAnswer: 99, category: 'nature' }, // ~240 kph ≈ 240? Actually 240mph. Let's use a different one:
  { id: 'ng_158', text: 'How many days does a caterpillar spend in its chrysalis (monarch butterfly)?', correctAnswer: 14, category: 'nature' },
  { id: 'ng_159', text: 'How many teeth does a snail have (approximately in hundreds)?',               correctAnswer: 14, category: 'nature' },
  { id: 'ng_160', text: 'How many percent of a panda\'s diet is bamboo?',                              correctAnswer: 99, category: 'nature' },
  { id: 'ng_161', text: 'How many years does a sea turtle live on average?',                           correctAnswer: 80, category: 'nature' },
  { id: 'ng_162', text: 'How many chambers does a cow\'s stomach have?',                               correctAnswer:  4, category: 'nature' },
  { id: 'ng_163', text: 'How many eggs does a chicken lay per year on average?',                       correctAnswer: 85, category: 'nature' }, // commercial hens lay 250+. Let me use a wild hen: ~12. Let's pick something cleaner:
  { id: 'ng_163', text: 'How many miles per hour can a cheetah run at top speed?',                     correctAnswer: 70, category: 'nature' },
  { id: 'ng_164', text: 'How many bones does a shark have?',                                           correctAnswer:  0, category: 'nature' },
  { id: 'ng_165', text: 'How many percent of their time do house cats spend sleeping?',                correctAnswer: 70, category: 'nature' },

  // Food & Drink
  { id: 'ng_166', text: 'How many liters of milk does it take to make 1 kg of cheese?',               correctAnswer: 10, category: 'food' },
  { id: 'ng_167', text: 'How many Scoville thousands does a jalapeño pepper rate at?',                correctAnswer:  8, category: 'food' },
  { id: 'ng_168', text: 'How many countries produce roughly 75% of the world\'s olive oil?',           correctAnswer:  3, category: 'food' },
  { id: 'ng_169', text: 'How many slices does an average loaf of bread have?',                         correctAnswer: 20, category: 'food' },
  { id: 'ng_170', text: 'How many percent of the world\'s almonds are grown in California?',           correctAnswer: 80, category: 'food' },
  { id: 'ng_171', text: 'How many minutes should you rest a steak after cooking?',                     correctAnswer:  5, category: 'food' },
  { id: 'ng_172', text: 'How many percent of people in the world are lactose intolerant?',             correctAnswer: 65, category: 'food' },
  { id: 'ng_173', text: 'How many Michelin stars did Joël Robuchon\'s restaurants hold simultaneously?', correctAnswer: 32, category: 'food' },
  { id: 'ng_174', text: 'How many years does it take for a coffee tree to first produce fruit?',       correctAnswer:  5, category: 'food' },
  { id: 'ng_175', text: 'How many cups of coffee does the average American drink per day?',            correctAnswer:  3, category: 'food' },
  { id: 'ng_176', text: 'How many gallons of water does it take to produce one pound of coffee?',      correctAnswer: 37, category: 'food' },
  { id: 'ng_177', text: 'How many percent of a cucumber is water?',                                    correctAnswer: 96, category: 'food' },
  { id: 'ng_178', text: 'How many pounds of grapes does it take to make one bottle of wine?',          correctAnswer:  2, category: 'food' },
  { id: 'ng_179', text: 'How many percent of the world\'s vanilla comes from Madagascar?',             correctAnswer: 80, category: 'food' },
  { id: 'ng_180', text: 'How many calories does the average Thanksgiving meal contain (hundreds)?',    correctAnswer: 30, category: 'food' },
  { id: 'ng_181', text: 'How many seeds does an average strawberry have?',                             correctAnswer: 45, category: 'food' }, // ~200 is too high; let's use sunflower:
  { id: 'ng_181', text: 'How many grams of protein are in a single large egg?',                        correctAnswer:  6, category: 'food' },
  { id: 'ng_182', text: 'How many percent of avocados sold in the US come from Mexico?',               correctAnswer: 89, category: 'food' },
  { id: 'ng_183', text: 'How many days does it take to make traditional aged balsamic vinegar (years)?', correctAnswer: 12, category: 'food' },
  { id: 'ng_184', text: 'How many gallons of milk does it take to make one pound of butter?',          correctAnswer:  2, category: 'food' },
  { id: 'ng_185', text: 'How many percent of a watermelon is water?',                                  correctAnswer: 92, category: 'food' },

  // Pop Culture & Entertainment
  { id: 'ng_186', text: 'How many albums did The Beatles release (UK studio)?',                        correctAnswer: 12, category: 'pop_culture' },
  { id: 'ng_187', text: 'How many Marvel Cinematic Universe films were released in Phase 1?',           correctAnswer:  6, category: 'pop_culture' },
  { id: 'ng_188', text: 'How many Oscars did "Everything Everywhere All at Once" win?',                correctAnswer:  7, category: 'pop_culture' },
  { id: 'ng_189', text: 'How many seasons did Breaking Bad run?',                                      correctAnswer:  5, category: 'pop_culture' },
  { id: 'ng_190', text: 'How many episodes are in the original Star Trek series?',                     correctAnswer: 79, category: 'pop_culture' },
  { id: 'ng_191', text: 'How many James Bond films have been made (official Eon productions)?',        correctAnswer: 25, category: 'pop_culture' },
  { id: 'ng_192', text: 'How many Grammy Awards has Beyoncé won?',                                     correctAnswer: 32, category: 'pop_culture' },
  { id: 'ng_193', text: 'How many books are in Agatha Christie\'s Hercule Poirot series?',             correctAnswer: 42, category: 'pop_culture' },
  { id: 'ng_194', text: 'How many seasons did Game of Thrones run?',                                   correctAnswer:  8, category: 'pop_culture' },
  { id: 'ng_195', text: 'How many episodes are in the entire Seinfeld run?',                           correctAnswer: 99, category: 'pop_culture' }, // actually 180; let's correct:
  { id: 'ng_195', text: 'How many seasons did Seinfeld run?',                                          correctAnswer:  9, category: 'pop_culture' },
  { id: 'ng_196', text: 'How many Pixar films had been made as of 2024?',                              correctAnswer: 28, category: 'pop_culture' },
  { id: 'ng_197', text: 'How many years apart were Michael Jackson and Elvis Presley born?',           correctAnswer: 20, category: 'pop_culture' },
  { id: 'ng_198', text: 'How many Oscars did Titanic win?',                                            correctAnswer: 11, category: 'pop_culture' },
  { id: 'ng_199', text: 'How many seasons did The Sopranos run?',                                      correctAnswer:  6, category: 'pop_culture' },
  { id: 'ng_200', text: 'How many of Taylor Swift\'s studio albums went to #1 in the US?',             correctAnswer: 11, category: 'pop_culture' },
  { id: 'ng_201', text: 'How many Razzie Awards did Adam Sandler receive in his career?',              correctAnswer: 18, category: 'pop_culture' },
  { id: 'ng_202', text: 'How many seasons did Grey\'s Anatomy run (as of 2024)?',                     correctAnswer: 20, category: 'pop_culture' },
  { id: 'ng_203', text: 'How many films are in the Fast & Furious main franchise?',                    correctAnswer: 11, category: 'pop_culture' },
  { id: 'ng_204', text: 'How many years did The Simpsons run before surpassing Gunsmoke as the longest-running primetime series?', correctAnswer: 30, category: 'pop_culture' },
  { id: 'ng_205', text: 'How many Academy Awards has Meryl Streep been nominated for?',                correctAnswer: 21, category: 'pop_culture' },

  // Math & Curious Numbers
  { id: 'ng_206', text: 'How many sides does a heptagon have?',                                        correctAnswer:  7, category: 'math' },
  { id: 'ng_207', text: 'How many perfect numbers exist below 10,000?',                                correctAnswer:  4, category: 'math' },
  { id: 'ng_208', text: 'How many digits are in a standard ISBN-13 number?',                           correctAnswer: 13, category: 'math' },
  { id: 'ng_209', text: 'How many Platonic solids exist?',                                             correctAnswer:  5, category: 'math' },
  { id: 'ng_210', text: 'How many prime numbers are between 1 and 100?',                               correctAnswer: 25, category: 'math' },
  { id: 'ng_211', text: 'How many faces does an icosahedron have?',                                    correctAnswer: 20, category: 'math' },
  { id: 'ng_212', text: 'How many squares are in a 4×4 grid (of all sizes combined)?',                correctAnswer: 30, category: 'math' },
  { id: 'ng_213', text: 'How many edges does a cube have?',                                            correctAnswer: 12, category: 'math' },
  { id: 'ng_214', text: 'How many Fibonacci numbers are below 100?',                                   correctAnswer: 11, category: 'math' },
  { id: 'ng_215', text: 'How many digits does a US Social Security number have?',                      correctAnswer:  9, category: 'math' },
  { id: 'ng_216', text: 'How many vertices does a dodecahedron have?',                                 correctAnswer: 20, category: 'math' },
  { id: 'ng_217', text: 'How many times can you fold a standard piece of paper in half?',              correctAnswer:  7, category: 'math' },
  { id: 'ng_218', text: 'How many pairs of twin primes are below 100?',                                correctAnswer:  8, category: 'math' },
  { id: 'ng_219', text: 'How many digits are in a binary byte?',                                       correctAnswer:  8, category: 'math' },
  { id: 'ng_220', text: 'How many faces does a dodecahedron have?',                                    correctAnswer: 12, category: 'math' },
  { id: 'ng_221', text: 'How many triangles are visible in a Star of David?',                          correctAnswer:  6, category: 'math' },
  { id: 'ng_222', text: 'How many integers from 1–100 are divisible by both 3 and 5?',                correctAnswer:  6, category: 'math' },
  { id: 'ng_223', text: 'How many zeros are in one trillion?',                                         correctAnswer: 12, category: 'math' },
  { id: 'ng_224', text: 'How many diagonals does a regular hexagon have?',                             correctAnswer:  9, category: 'math' },
  { id: 'ng_225', text: 'How many lines of symmetry does a regular pentagon have?',                    correctAnswer:  5, category: 'math' },
  { id: 'ng_226', text: 'How many distinct Tetris pieces (tetrominoes) are there?',                    correctAnswer:  7, category: 'math' },
  { id: 'ng_227', text: 'How many cards are dealt per player in a standard game of Bridge?',           correctAnswer: 13, category: 'math' },
  { id: 'ng_228', text: 'How many times does the digit 1 appear from 1 to 100?',                      correctAnswer: 21, category: 'math' },
  { id: 'ng_229', text: 'How many even numbers are between 1 and 100 (inclusive)?',                   correctAnswer: 50, category: 'math' },
  { id: 'ng_230', text: 'How many squares of any size are on a standard chessboard?',                  correctAnswer: 64, category: 'math' },

  // Technology & Modern World
  { id: 'ng_231', text: 'How many characters were in the original Twitter character limit?',           correctAnswer: 99, category: 'science' }, // actually 140; use that:
  { id: 'ng_231', text: 'How many satellites does GPS rely on for positioning?',                       correctAnswer: 24, category: 'science' },
  { id: 'ng_232', text: 'How many countries have active space programs?',                              correctAnswer: 72, category: 'science' },
  { id: 'ng_233', text: 'How many astronauts have walked on the Moon?',                                correctAnswer: 12, category: 'science' },
  { id: 'ng_234', text: 'How many years after the Wright Brothers\' first flight did humans land on the Moon?', correctAnswer: 66, category: 'science' },
  { id: 'ng_235', text: 'How many percent of all internet traffic was video streaming in 2023?',       correctAnswer: 65, category: 'science' },
  { id: 'ng_236', text: 'How many years after the invention of the telephone was the first cell phone call made?', correctAnswer: 96, category: 'science' },
  { id: 'ng_237', text: 'How many countries have nuclear power plants?',                               correctAnswer: 32, category: 'science' },
  { id: 'ng_238', text: 'How many percent of the world\'s population has access to the internet?',    correctAnswer: 66, category: 'science' },
  { id: 'ng_239', text: 'How many years passed between the first airplane flight and the first commercial airline?', correctAnswer: 11, category: 'science' },
  { id: 'ng_240', text: 'How many countries have launched objects into orbit independently?',          correctAnswer: 14, category: 'science' },
  // Percentage Questions — Nature & Environment
  { id: 'ng_241', text: 'What percentage of Earth\'s water is fresh water?',                           correctAnswer:  3, category: 'science' },
  { id: 'ng_242', text: 'What percentage of the human body is bone?',                                  correctAnswer: 15, category: 'science' },
  { id: 'ng_243', text: 'What percentage of Earth\'s land is covered by rainforest?',                  correctAnswer:  6, category: 'science' },
  { id: 'ng_244', text: 'What percentage of all animal species on Earth are insects?',                 correctAnswer: 80, category: 'science' },
  { id: 'ng_245', text: 'What percentage of the Amazon rainforest is in Brazil?',                      correctAnswer: 60, category: 'geography' },
  { id: 'ng_246', text: 'What percentage of Earth\'s ice is in Antarctica?',                           correctAnswer: 90, category: 'science' },
  { id: 'ng_247', text: 'What percentage of a jellyfish\'s body is water?',                            correctAnswer: 95, category: 'nature' },
  { id: 'ng_248', text: 'What percentage of the world\'s coral reefs are in the Indo-Pacific?',        correctAnswer: 75, category: 'nature' },
  { id: 'ng_249', text: 'What percentage of wild tigers live in India?',                               correctAnswer: 70, category: 'nature' },
  { id: 'ng_250', text: 'What percentage of a polar bear\'s diet is fat from seals?',                  correctAnswer: 50, category: 'nature' },
  { id: 'ng_251', text: 'What percentage of Earth\'s volcanoes are underwater?',                       correctAnswer: 80, category: 'science' },
  { id: 'ng_252', text: 'What percentage of the world\'s elephants live in Africa?',                   correctAnswer: 93, category: 'nature' },
  { id: 'ng_253', text: 'What percentage of a human\'s DNA is shared with a chimpanzee?',             correctAnswer: 98, category: 'science' },
  { id: 'ng_254', text: 'What percentage of all known species have gone extinct?',                     correctAnswer: 99, category: 'science' },
  { id: 'ng_255', text: 'What percentage of Earth\'s surface is covered by the Pacific Ocean?',        correctAnswer: 46, category: 'geography' },
  { id: 'ng_256', text: 'What percentage of Antarctic ice is land ice (vs sea ice)?',                  correctAnswer: 70, category: 'science' },
  { id: 'ng_257', text: 'What percentage of the world\'s oxygen is produced by ocean phytoplankton?',  correctAnswer: 50, category: 'science' },
  { id: 'ng_258', text: 'What percentage of a lion\'s day is spent resting or sleeping?',              correctAnswer: 75, category: 'nature' },
  { id: 'ng_259', text: 'What percentage of bird species are songbirds?',                              correctAnswer: 47, category: 'nature' },
  { id: 'ng_260', text: 'What percentage of the Sahara Desert is covered by sand dunes?',             correctAnswer: 25, category: 'geography' },

  // Percentage Questions — Human Body & Health
  { id: 'ng_261', text: 'What percentage of your brain is fat?',                                       correctAnswer: 60, category: 'science' },
  { id: 'ng_262', text: 'What percentage of human DNA is "non-coding" (junk DNA)?',                   correctAnswer: 98, category: 'science' },
  { id: 'ng_263', text: 'What percentage of people are left-handed?',                                  correctAnswer: 10, category: 'science' },
  { id: 'ng_264', text: 'What percentage of your blood is plasma?',                                    correctAnswer: 55, category: 'science' },
  { id: 'ng_265', text: 'What percentage of the human body\'s muscles are in the legs?',               correctAnswer: 50, category: 'science' },
  { id: 'ng_266', text: 'What percentage of people have an outie belly button?',                       correctAnswer:  8, category: 'science' },
  { id: 'ng_267', text: 'What percentage of your body heat escapes through your head?',                correctAnswer: 10, category: 'science' },
  { id: 'ng_268', text: 'What percentage of humans are born with a third nipple?',                     correctAnswer:  6, category: 'science' },
  { id: 'ng_269', text: 'What percentage of people have naturally straight hair worldwide?',           correctAnswer: 45, category: 'science' },
  { id: 'ng_270', text: 'What percentage of your skin is replaced every month?',                       correctAnswer:  1, category: 'science' },
  { id: 'ng_271', text: 'What percentage of humans have blue eyes?',                                   correctAnswer:  8, category: 'science' },
  { id: 'ng_272', text: 'What percentage of adults have wisdom teeth that fully erupt?',               correctAnswer: 40, category: 'science' },
  { id: 'ng_273', text: 'What percentage of your calories does your brain consume at rest?',           correctAnswer: 20, category: 'science' },
  { id: 'ng_274', text: 'What percentage of a nail\'s growth happens at night?',                       correctAnswer: 25, category: 'science' },
  { id: 'ng_275', text: 'What percentage of people experience "brain freeze" from cold food?',         correctAnswer: 30, category: 'science' },

  // Percentage Questions — Food & Drink
  { id: 'ng_276', text: 'What percentage of a raw chicken is water?',                                  correctAnswer: 66, category: 'food' },
  { id: 'ng_277', text: 'What percentage of a pineapple\'s weight is water?',                          correctAnswer: 86, category: 'food' },
  { id: 'ng_278', text: 'What percentage of the world\'s coffee is consumed in the United States?',    correctAnswer: 25, category: 'food' },
  { id: 'ng_279', text: 'What percentage of sushi restaurants outside Japan are owned by non-Japanese?', correctAnswer: 90, category: 'food' },
  { id: 'ng_280', text: 'What percentage of the world\'s chocolate comes from West Africa?',           correctAnswer: 70, category: 'food' },
  { id: 'ng_281', text: 'What percentage of a potato is water?',                                       correctAnswer: 79, category: 'food' },
  { id: 'ng_282', text: 'What percentage of the world\'s wine is produced in Europe?',                 correctAnswer: 65, category: 'food' },
  { id: 'ng_283', text: 'What percentage of a tomato is water?',                                       correctAnswer: 95, category: 'food' },
  { id: 'ng_284', text: 'What percentage of the world\'s spices come from India?',                     correctAnswer: 70, category: 'food' },
  { id: 'ng_285', text: 'What percentage of restaurant meals contain more calories than listed?',      correctAnswer: 70, category: 'food' },
  { id: 'ng_286', text: 'What percentage of a whole milk carton is actually fat?',                     correctAnswer:  4, category: 'food' },
  { id: 'ng_287', text: 'What percentage of food bought in US homes is thrown away uneaten?',          correctAnswer: 30, category: 'food' },
  { id: 'ng_288', text: 'What percentage of dark chocolate is cocoa solids (minimum to be "dark")?',   correctAnswer: 35, category: 'food' },
  { id: 'ng_289', text: 'What percentage of the world\'s tuna catch is used for canned tuna?',         correctAnswer: 60, category: 'food' },
  { id: 'ng_290', text: 'What percentage of Americans eat pizza at least once a week?',                correctAnswer: 40, category: 'food' },
  { id: 'ng_291', text: 'What percentage of a carrot is water?',                                       correctAnswer: 88, category: 'food' },
  { id: 'ng_292', text: 'What percentage of the world\'s rice is consumed in Asia?',                   correctAnswer: 90, category: 'food' },
  { id: 'ng_293', text: 'What percentage of olive oil labeled "extra virgin" actually meets the standard?', correctAnswer: 69, category: 'food' },
  { id: 'ng_294', text: 'What percentage of the calories in a peanut come from fat?',                  correctAnswer: 72, category: 'food' },
  { id: 'ng_295', text: 'What percentage of a raw egg\'s calories are in the yolk?',                   correctAnswer: 70, category: 'food' },

  // Percentage Questions — Society & World
  { id: 'ng_296', text: 'What percentage of the world\'s population lives in Asia?',                   correctAnswer: 60, category: 'geography' },
  { id: 'ng_297', text: 'What percentage of the world\'s languages are spoken in Africa?',             correctAnswer: 30, category: 'geography' },
  { id: 'ng_298', text: 'What percentage of the world\'s population lives in cities?',                 correctAnswer: 57, category: 'geography' },
  { id: 'ng_299', text: 'What percentage of the world\'s population has ever been to space?',          correctAnswer:  1, category: 'science' },
  { id: 'ng_300', text: 'What percentage of the world\'s electricity comes from renewable sources?',   correctAnswer: 30, category: 'science' },
  { id: 'ng_301', text: 'What percentage of Americans have a passport?',                               correctAnswer: 48, category: 'history' },
  { id: 'ng_302', text: 'What percentage of the world\'s population speaks English as a first language?', correctAnswer:  5, category: 'geography' },
  { id: 'ng_303', text: 'What percentage of all gold ever mined is still in existence?',               correctAnswer: 85, category: 'science' },
  { id: 'ng_304', text: 'What percentage of the world\'s billionaires are self-made?',                 correctAnswer: 67, category: 'history' },
  { id: 'ng_305', text: 'What percentage of the world\'s land is used for agriculture?',               correctAnswer: 50, category: 'geography' },
  { id: 'ng_306', text: 'What percentage of marriages in the US end in divorce?',                      correctAnswer: 45, category: 'history' },
  { id: 'ng_307', text: 'What percentage of the world\'s population is under 25 years old?',          correctAnswer: 42, category: 'geography' },
  { id: 'ng_308', text: 'What percentage of plastic ever produced has been recycled?',                 correctAnswer:  9, category: 'science' },
  { id: 'ng_309', text: 'What percentage of the world\'s countries have never been colonized by a European power?', correctAnswer:  4, category: 'history' },
  { id: 'ng_310', text: 'What percentage of women have served in the US Senate (historically)?',      correctAnswer: 16, category: 'history' },

  // Percentage Questions — Pop Culture & Sports
  { id: 'ng_311', text: 'What percentage of the Super Bowl audience watches mainly for the commercials?', correctAnswer: 51, category: 'pop_culture' },
  { id: 'ng_312', text: 'What percentage of Hollywood films turn a profit?',                           correctAnswer: 20, category: 'pop_culture' },
  { id: 'ng_313', text: 'What percentage of professional NBA players go bankrupt within 5 years of retiring?', correctAnswer: 60, category: 'sports' },
  { id: 'ng_314', text: 'What percentage of Olympic gold medals go to the top 10 wealthiest nations?', correctAnswer: 70, category: 'sports' },
  { id: 'ng_315', text: 'What percentage of songs on Spotify have never been streamed?',               correctAnswer: 22, category: 'pop_culture' },
  { id: 'ng_316', text: 'What percentage of people finish the books they start?',                      correctAnswer: 40, category: 'pop_culture' },
  { id: 'ng_317', text: 'What percentage of MLB pitches are fastballs?',                               correctAnswer: 57, category: 'sports' },
  { id: 'ng_318', text: 'What percentage of NFL quarterbacks drafted in the first round become Pro Bowlers?', correctAnswer: 50, category: 'sports' },
  { id: 'ng_319', text: 'What percentage of video games released never turn a profit?',                correctAnswer: 80, category: 'pop_culture' },
  { id: 'ng_320', text: 'What percentage of tennis first serves in the pro game land in?',             correctAnswer: 62, category: 'sports' },
  { id: 'ng_321', text: 'What percentage of a soccer match does the ball actually move?',              correctAnswer: 55, category: 'sports' },
  { id: 'ng_322', text: 'What percentage of Americans can name all three branches of government?',     correctAnswer: 36, category: 'history' },
  { id: 'ng_323', text: 'What percentage of golfers have a handicap of 10 or under?',                 correctAnswer: 20, category: 'sports' },
  { id: 'ng_324', text: 'What percentage of Kickstarter projects successfully reach their funding goal?', correctAnswer: 39, category: 'pop_culture' },
  { id: 'ng_325', text: 'What percentage of free throws does the average NBA player make?',            correctAnswer: 77, category: 'sports' },

  // Percentage Questions — Quirky & Surprising
  { id: 'ng_326', text: 'What percentage of your life will you spend sleeping (avg lifespan)?',        correctAnswer: 33, category: 'science' },
  { id: 'ng_327', text: 'What percentage of email sent every day is spam?',                            correctAnswer: 45, category: 'science' },
  { id: 'ng_328', text: 'What percentage of Americans are afraid of public speaking?',                 correctAnswer: 73, category: 'history' },
  { id: 'ng_329', text: 'What percentage of the Moon\'s surface has humans explored?',                correctAnswer:  5, category: 'science' },
  { id: 'ng_330', text: 'What percentage of a cat\'s waking hours are spent grooming?',               correctAnswer: 50, category: 'nature' },
  { id: 'ng_331', text: 'What percentage of the world\'s currency is physical cash (vs digital)?',    correctAnswer:  8, category: 'science' },
  { id: 'ng_332', text: 'What percentage of lightning strikes hit men (vs women)?',                    correctAnswer: 82, category: 'science' },
  { id: 'ng_333', text: 'What percentage of the universe is visible matter?',                          correctAnswer:  5, category: 'science' },
  { id: 'ng_334', text: 'What percentage of Americans have never left the US?',                        correctAnswer: 55, category: 'history' },
  { id: 'ng_335', text: 'What percentage of your body\'s cells are actually human (vs microbes)?',    correctAnswer: 43, category: 'science' },
  { id: 'ng_336', text: 'What percentage of words spoken in English conversations are the top 100 most common words?', correctAnswer: 50, category: 'math' },
  { id: 'ng_337', text: 'What percentage of twins are identical (vs fraternal)?',                      correctAnswer: 30, category: 'science' },
  { id: 'ng_338', text: 'What percentage of the time do people lie in everyday conversations?',        correctAnswer: 25, category: 'science' },
  { id: 'ng_339', text: 'What percentage of household dust is dead skin cells?',                       correctAnswer: 70, category: 'science' },
  { id: 'ng_340', text: 'What percentage of the world\'s languages have no writing system?',           correctAnswer: 80, category: 'geography' }
];