// ─────────────────────────────────────────────────────────────────────────────
// Pie Charts — Prompt Bank
// "Who is most likely to…" questions. Players vote for a group member.
// isCustom marks prompts added by players in the setup phase.
// ─────────────────────────────────────────────────────────────────────────────

export interface PieChartPrompt {
  id: string;
  text: string;
  isCustom?: boolean;
}

export const PIE_CHARTS_PROMPTS: PieChartPrompt[] = [
  { id: 'pc1',  text: 'Who is most likely to go viral?' },
  { id: 'pc2',  text: 'Who is most likely to ghost someone?' },
  { id: 'pc3',  text: 'Who is most likely to get rich?' },
  { id: 'pc4',  text: 'Who is most likely to embarrass themselves in public?' },
  { id: 'pc5',  text: 'Who is most likely to survive a zombie apocalypse?' },
  { id: 'pc6',  text: 'Who is most likely to forget their own birthday plans?' },
  { id: 'pc7',  text: 'Who is most likely to become famous for something weird?' },
  { id: 'pc8',  text: 'Who is most likely to start drama by accident?' },
  { id: 'pc9',  text: 'Who is most likely to end up on reality TV?' },
  { id: 'pc10', text: 'Who is most likely to get canceled first?' },
  { id: 'pc11', text: 'Who is most likely to cry at a movie?' },
  { id: 'pc12', text: 'Who is most likely to be the last one to know something?' },
  { id: 'pc13', text: 'Who is most likely to accidentally text the wrong person?' },
  { id: 'pc14', text: 'Who is most likely to show up late to their own event?' },
  { id: 'pc15', text: 'Who is most likely to spend their savings in one weekend?' },
  { id: 'pc16', text: 'Who is most likely to start a cult?' },
  { id: 'pc17', text: 'Who is most likely to be on a podcast?' },
  { id: 'pc18', text: 'Who is most likely to get into an argument with a stranger?' },
  { id: 'pc19', text: 'Who is most likely to forget your birthday?' },
  { id: 'pc20', text: 'Who is most likely to move to another country?' },
  { id: 'pc21', text: 'Who is most likely to invent something?' },
  { id: 'pc22', text: 'Who is most likely to go skydiving?' },
  { id: 'pc23', text: 'Who is most likely to have a secret second life?' },
  { id: 'pc24', text: 'Who is most likely to say something they immediately regret?' },
  { id: 'pc25', text: 'Who is most likely to be the group parent?' },
  { id: 'pc26', text: 'Who is most likely to become a hermit?' },
  { id: 'pc27', text: 'Who is most likely to date someone they met online?' },
  { id: 'pc28', text: 'Who is most likely to quit their job on the spot?' },
  { id: 'pc29', text: 'Who is most likely to win a random game show?' },
  { id: 'pc30', text: 'Who is most likely to be overly dramatic about nothing?' },
  { id: 'pc31', text: 'Who is most likely to get lost in their own neighborhood?' },
  { id: 'pc32', text: 'Who is most likely to trip going up the stairs?' },
  { id: 'pc33', text: 'Who is most likely to lose their phone while talking on it?' },
  { id: 'pc34', text: 'Who is most likely to start a fire trying to cook something simple?' },
  { id: 'pc35', text: 'Who is most likely to laugh at the worst possible moment?' },
  { id: 'pc36', text: 'Who is most likely to get banned from a group chat?' },
  { id: 'pc37', text: 'Who is most likely to argue with a self-checkout machine?' },
  { id: 'pc38', text: 'Who is most likely to fall asleep at a concert?' },
  { id: 'pc39', text: 'Who is most likely to get hurt doing absolutely nothing?' },
  { id: 'pc40', text: 'Who is most likely to name their car?' },
  { id: 'pc41', text: 'Who is most likely to talk to animals like they understand?' },
  { id: 'pc42', text: 'Who is most likely to wear the same outfit three days in a row?' },
  { id: 'pc43', text: 'Who is most likely to get scammed by an obvious scam?' },
  { id: 'pc44', text: 'Who is most likely to lose a fight with a door?' },
  { id: 'pc45', text: 'Who is most likely to set off the fire alarm cooking?' },
  { id: 'pc46', text: 'Who is most likely to bring up a random fact nobody asked for?' },
  { id: 'pc47', text: 'Who is most likely to get distracted mid-sentence?' },
  { id: 'pc48', text: 'Who is most likely to win an award for being chronically online?' },
  { id: 'pc49', text: 'Who is most likely to have 200 unread texts right now?' },
  { id: 'pc50', text: 'Who is most likely to reply "lol" to serious news?' },
  { id: 'pc51', text: 'Who is most likely to send a voice memo longer than a movie?' },
  { id: 'pc52', text: 'Who is most likely to leave you on read for three days?' },
  { id: 'pc53', text: 'Who is most likely to fake a phone call to escape a conversation?' },
  { id: 'pc54', text: 'Who is most likely to clog a toilet at a party?' },
  { id: 'pc55', text: 'Who is most likely to wear sunglasses indoors?' },
  { id: 'pc56', text: 'Who is most likely to overshare with a stranger on a plane?' },
  { id: 'pc57', text: 'Who is most likely to get a tattoo they regret immediately?' },
  { id: 'pc58', text: 'Who is most likely to lie about reading a book?' },
  { id: 'pc59', text: 'Who is most likely to cause a scene at a wedding?' },
  { id: 'pc60', text: 'Who is most likely to forget where they parked every single time?' },
 
  // ── Juicy / spicy ────────────────────────────────────────────────────────
  { id: 'pc61', text: 'Who is most likely to text their ex at 2am?' },
  { id: 'pc62', text: 'Who is most likely to have a crush nobody knows about?' },
  { id: 'pc63', text: 'Who is most likely to date two people at once?' },
  { id: 'pc64', text: 'Who is most likely to keep a secret the longest?' },
  { id: 'pc65', text: 'Who is most likely to spill a secret the fastest?' },
  { id: 'pc66', text: 'Who is most likely to stalk a crush on social media?' },
  { id: 'pc67', text: 'Who is most likely to get back with an ex they swore off?' },
  { id: 'pc68', text: 'Who is most likely to have the wildest dating app stories?' },
  { id: 'pc69', text: 'Who is most likely to fall in love on vacation?' },
  { id: 'pc70', text: 'Who is most likely to flirt to get out of trouble?' },
  { id: 'pc71', text: 'Who is most likely to have a situationship right now?' },
  { id: 'pc72', text: 'Who is most likely to ghost and then act surprised?' },
  { id: 'pc73', text: 'Who is most likely to lie about their "type"?' },
  { id: 'pc74', text: 'Who is most likely to have screenshots saved for evidence?' },
  { id: 'pc75', text: 'Who is most likely to slide into someone\u2019s DMs?' },
  { id: 'pc76', text: 'Who is most likely to date a friend\u2019s ex?' },
  { id: 'pc77', text: 'Who is most likely to overthink a single text for hours?' },
  { id: 'pc78', text: 'Who is most likely to pretend they\u2019re over someone when they\u2019re not?' },
  { id: 'pc79', text: 'Who is most likely to have a celebrity hall pass list ready?' },
  { id: 'pc80', text: 'Who is most likely to keep their relationship a secret?' },
  { id: 'pc81', text: 'Who is most likely to be caught lying about where they were?' },
  { id: 'pc82', text: 'Who is most likely to start dating someone way too fast?' },
  { id: 'pc83', text: 'Who is most likely to have the most dramatic breakup?' },
  { id: 'pc84', text: 'Who is most likely to be everyone\u2019s "it\u2019s complicated"?' },
  { id: 'pc85', text: 'Who is most likely to confess feelings at the worst time?' },
 
  // ── Group dynamics / "callout" ─────────────────────────────────────────────
  { id: 'pc86', text: 'Who is most likely to plan the whole trip and complain about it?' },
  { id: 'pc87', text: 'Who is most likely to never text back but always show up?' },
  { id: 'pc88', text: 'Who is most likely to be the group\u2019s therapist?' },
  { id: 'pc89', text: 'Who is most likely to start the group chat drama?' },
  { id: 'pc90', text: 'Who is most likely to never split the bill fairly?' },
  { id: 'pc91', text: 'Who is most likely to be late to everything?' },
  { id: 'pc92', text: 'Who is most likely to bail at the last minute?' },
  { id: 'pc93', text: 'Who is most likely to be the loudest in the group?' },
  { id: 'pc94', text: 'Who is most likely to be the designated driver?' },
  { id: 'pc95', text: 'Who is most likely to remember everyone\u2019s birthday?' },
  { id: 'pc96', text: 'Who is most likely to give unsolicited life advice?' },
  { id: 'pc97', text: 'Who is most likely to take a group photo 40 times?' },
  { id: 'pc98', text: 'Who is most likely to be the peacemaker in an argument?' },
  { id: 'pc99', text: 'Who is most likely to start a fight in the group chat?' },
  { id: 'pc100', text: 'Who is most likely to know the most gossip?' },
  { id: 'pc101', text: 'Who is most likely to be the mom friend?' },
  { id: 'pc102', text: 'Who is most likely to be the bad influence?' },
  { id: 'pc103', text: 'Who is most likely to third-wheel on purpose?' },
  { id: 'pc104', text: 'Who is most likely to leave a party without saying goodbye?' },
  { id: 'pc105', text: 'Who is most likely to be the first to fall asleep at a sleepover?' },
  { id: 'pc106', text: 'Who is most likely to keep the receipts on everyone?' },
  { id: 'pc107', text: 'Who is most likely to be the reason the group is banned somewhere?' },
  { id: 'pc108', text: 'Who is most likely to turn a small plan into a whole event?' },
  { id: 'pc109', text: 'Who is most likely to be everyone\u2019s emergency contact?' },
  { id: 'pc110', text: 'Who is most likely to keep an argument going for a week?' },
  { id: 'pc111', text: 'Who is most likely to defend the group no matter what?' },
  { id: 'pc112', text: 'Who is most likely to forget to invite someone?' },
  { id: 'pc113', text: 'Who is most likely to "just check one thing" and disappear for an hour?' },
  { id: 'pc114', text: 'Who is most likely to suggest the restaurant nobody wants?' },
  { id: 'pc115', text: 'Who is most likely to be voted group leader?' },
 
  // ── Career / future / ambition ─────────────────────────────────────────────
  { id: 'pc116', text: 'Who is most likely to become a CEO?' },
  { id: 'pc117', text: 'Who is most likely to start their own company?' },
  { id: 'pc118', text: 'Who is most likely to become a millionaire by 30?' },
  { id: 'pc119', text: 'Who is most likely to retire early?' },
  { id: 'pc120', text: 'Who is most likely to win a Nobel Prize?' },
  { id: 'pc121', text: 'Who is most likely to run for office?' },
  { id: 'pc122', text: 'Who is most likely to become an influencer?' },
  { id: 'pc123', text: 'Who is most likely to write a bestselling book?' },
  { id: 'pc124', text: 'Who is most likely to drop everything and travel the world?' },
  { id: 'pc125', text: 'Who is most likely to become a professor?' },
  { id: 'pc126', text: 'Who is most likely to change careers five times?' },
  { id: 'pc127', text: 'Who is most likely to work the same job for 40 years?' },
  { id: 'pc128', text: 'Who is most likely to become internet famous overnight?' },
  { id: 'pc129', text: 'Who is most likely to get a job through pure charm?' },
  { id: 'pc130', text: 'Who is most likely to invent an app everyone uses?' },
  { id: 'pc131', text: 'Who is most likely to be on a magazine cover?' },
  { id: 'pc132', text: 'Who is most likely to become a famous chef?' },
  { id: 'pc133', text: 'Who is most likely to win an Oscar one day?' },
  { id: 'pc134', text: 'Who is most likely to become a doctor?' },
  { id: 'pc135', text: 'Who is most likely to go viral for a business idea?' },
  { id: 'pc136', text: 'Who is most likely to become a motivational speaker?' },
  { id: 'pc137', text: 'Who is most likely to be their own boss?' },
  { id: 'pc138', text: 'Who is most likely to fail upward into success?' },
  { id: 'pc139', text: 'Who is most likely to be headhunted for a dream job?' },
  { id: 'pc140', text: 'Who is most likely to make a fortune off something random?' },
 
  // ── Hypotheticals / "if" scenarios ─────────────────────────────────────────
  { id: 'pc141', text: 'Who is most likely to survive being stranded on an island?' },
  { id: 'pc142', text: 'Who is most likely to panic in an emergency?' },
  { id: 'pc143', text: 'Who is most likely to befriend an alien?' },
  { id: 'pc144', text: 'Who is most likely to become a supervillain?' },
  { id: 'pc145', text: 'Who is most likely to be the first to volunteer for a space mission?' },
  { id: 'pc146', text: 'Who is most likely to survive a horror movie?' },
  { id: 'pc147', text: 'Who is most likely to die first in a horror movie?' },
  { id: 'pc148', text: 'Who is most likely to talk their way out of an arrest?' },
  { id: 'pc149', text: 'Who is most likely to accidentally start a revolution?' },
  { id: 'pc150', text: 'Who is most likely to win the lottery and lose it all?' },
  { id: 'pc151', text: 'Who is most likely to befriend a celebrity in real life?' },
  { id: 'pc152', text: 'Who is most likely to be recruited by a secret agency?' },
  { id: 'pc153', text: 'Who is most likely to survive the longest without their phone?' },
  { id: 'pc154', text: 'Who is most likely to lead the group if society collapsed?' },
  { id: 'pc155', text: 'Who is most likely to get adopted by a rich stranger?' },
  { id: 'pc156', text: 'Who is most likely to fake their own disappearance?' },
  { id: 'pc157', text: 'Who is most likely to win a fight against a goose?' },
  { id: 'pc158', text: 'Who is most likely to be the chosen one in a prophecy?' },
  { id: 'pc159', text: 'Who is most likely to negotiate with a kidnapper successfully?' },
  { id: 'pc160', text: 'Who is most likely to accidentally time travel?' },
  { id: 'pc161', text: 'Who is most likely to get abducted and talk the aliens to death?' },
  { id: 'pc162', text: 'Who is most likely to start a new civilization?' },
  { id: 'pc163', text: 'Who is most likely to survive a week in the wilderness?' },
  { id: 'pc164', text: 'Who is most likely to be unbothered during the apocalypse?' },
  { id: 'pc165', text: 'Who is most likely to become a meme after one bad moment?' },
 
  // ── Habits / quirks / personality ──────────────────────────────────────────
  { id: 'pc166', text: 'Who is most likely to have 47 tabs open right now?' },
  { id: 'pc167', text: 'Who is most likely to reread the same texts over and over?' },
  { id: 'pc168', text: 'Who is most likely to have a color-coded calendar?' },
  { id: 'pc169', text: 'Who is most likely to never finish a TV series?' },
  { id: 'pc170', text: 'Who is most likely to have a secret snack stash?' },
  { id: 'pc171', text: 'Who is most likely to talk in their sleep?' },
  { id: 'pc172', text: 'Who is most likely to cry from happiness?' },
  { id: 'pc173', text: 'Who is most likely to hold a grudge forever?' },
  { id: 'pc174', text: 'Who is most likely to forgive anyone instantly?' },
  { id: 'pc175', text: 'Who is most likely to overpack for a one-night trip?' },
  { id: 'pc176', text: 'Who is most likely to have a weird collection?' },
  { id: 'pc177', text: 'Who is most likely to romanticize their own life?' },
  { id: 'pc178', text: 'Who is most likely to narrate their day out loud?' },
  { id: 'pc179', text: 'Who is most likely to buy something just because it\u2019s on sale?' },
  { id: 'pc180', text: 'Who is most likely to have an emotional support water bottle?' },
  { id: 'pc181', text: 'Who is most likely to apologize to furniture they bump into?' },
  { id: 'pc182', text: 'Who is most likely to keep New Year\u2019s resolutions?' },
  { id: 'pc183', text: 'Who is most likely to break a resolution by January 2nd?' },
  { id: 'pc184', text: 'Who is most likely to talk during a movie?' },
  { id: 'pc185', text: 'Who is most likely to fall down a Wikipedia rabbit hole at 3am?' },
  { id: 'pc186', text: 'Who is most likely to be weirdly competitive about board games?' },
  { id: 'pc187', text: 'Who is most likely to have a podcast no one listens to?' },
  { id: 'pc188', text: 'Who is most likely to overthink everything?' },
  { id: 'pc189', text: 'Who is most likely to act first and think later?' },
  { id: 'pc190', text: 'Who is most likely to have the messiest room?' },
  { id: 'pc191', text: 'Who is most likely to alphabetize their spice rack?' },
  { id: 'pc192', text: 'Who is most likely to cry over a commercial?' },
  { id: 'pc193', text: 'Who is most likely to have a comfort show they\u2019ve seen ten times?' },
  { id: 'pc194', text: 'Who is most likely to be the pickiest eater?' },
  { id: 'pc195', text: 'Who is most likely to try any food once?' },
 
  // ── Money / lifestyle ──────────────────────────────────────────────────────
  { id: 'pc196', text: 'Who is most likely to splurge on something useless?' },
  { id: 'pc197', text: 'Who is most likely to be the cheapest in the group?' },
  { id: 'pc198', text: 'Who is most likely to tip way too much?' },
  { id: 'pc199', text: 'Who is most likely to have a secret luxury obsession?' },
  { id: 'pc200', text: 'Who is most likely to go broke buying coffee?' },
  { id: 'pc201', text: 'Who is most likely to never check their bank balance?' },
  { id: 'pc202', text: 'Who is most likely to budget down to the penny?' },
  { id: 'pc203', text: 'Who is most likely to fall for a "limited time offer"?' },
  { id: 'pc204', text: 'Who is most likely to own way too many gadgets?' },
  { id: 'pc205', text: 'Who is most likely to drive the fanciest car someday?' },
  { id: 'pc206', text: 'Who is most likely to live in a tiny house by choice?' },
  { id: 'pc207', text: 'Who is most likely to spend rent money on concert tickets?' },
  { id: 'pc208', text: 'Who is most likely to keep every receipt "just in case"?' },
  { id: 'pc209', text: 'Who is most likely to get rich and stay humble?' },
  { id: 'pc210', text: 'Who is most likely to get rich and change completely?' },
 
  // ── Wholesome / sweet ──────────────────────────────────────────────────────
  { id: 'pc211', text: 'Who is most likely to adopt every stray animal?' },
  { id: 'pc212', text: 'Who is most likely to text you "thinking of you" out of nowhere?' },
  { id: 'pc213', text: 'Who is most likely to be the best parent someday?' },
  { id: 'pc214', text: 'Who is most likely to remember the tiny details about you?' },
  { id: 'pc215', text: 'Who is most likely to give the best advice?' },
  { id: 'pc216', text: 'Who is most likely to drop everything to help a friend?' },
  { id: 'pc217', text: 'Who is most likely to be friends with everyone they meet?' },
  { id: 'pc218', text: 'Who is most likely to write you a heartfelt letter?' },
  { id: 'pc219', text: 'Who is most likely to make a stranger\u2019s day better?' },
  { id: 'pc220', text: 'Who is most likely to host the holidays for everyone?' },
  { id: 'pc221', text: 'Who is most likely to keep a friendship going for 50 years?' },
  { id: 'pc222', text: 'Who is most likely to be the first to say sorry?' },
  { id: 'pc223', text: 'Who is most likely to cheer you up no matter what?' },
  { id: 'pc224', text: 'Who is most likely to give the best hugs?' },
  { id: 'pc225', text: 'Who is most likely to volunteer for a good cause?' },
 
  // ── Skills / talents (or lack thereof) ─────────────────────────────────────
  { id: 'pc226', text: 'Who is most likely to win a karaoke night?' },
  { id: 'pc227', text: 'Who is most likely to be terrible at karaoke but love it?' },
  { id: 'pc228', text: 'Who is most likely to beat everyone at video games?' },
  { id: 'pc229', text: 'Who is most likely to be secretly amazing at something random?' },
  { id: 'pc230', text: 'Who is most likely to win a dance-off?' },
  { id: 'pc231', text: 'Who is most likely to lose at every game and stay mad?' },
  { id: 'pc232', text: 'Who is most likely to be a hidden cooking genius?' },
  { id: 'pc233', text: 'Who is most likely to learn a language in a month?' },
  { id: 'pc234', text: 'Who is most likely to be the best public speaker?' },
  { id: 'pc235', text: 'Who is most likely to have a hidden artistic talent?' },
  { id: 'pc236', text: 'Who is most likely to win a trivia night single-handedly?' },
  { id: 'pc237', text: 'Who is most likely to be unexpectedly good at sports?' },
  { id: 'pc238', text: 'Who is most likely to fix anything with duct tape?' },
  { id: 'pc239', text: 'Who is most likely to nail an impression of someone?' },
  { id: 'pc240', text: 'Who is most likely to remember every song lyric ever?' },
 
  // ── Embarrassing / "we don't talk about it" ────────────────────────────────
  { id: 'pc241', text: 'Who is most likely to call a teacher "mom" or "dad"?' },
  { id: 'pc242', text: 'Who is most likely to wave back at someone not waving at them?' },
  { id: 'pc243', text: 'Who is most likely to walk into a glass door?' },
  { id: 'pc244', text: 'Who is most likely to send a screenshot to the person it\u2019s about?' },
  { id: 'pc245', text: 'Who is most likely to forget someone\u2019s name mid-introduction?' },
  { id: 'pc246', text: 'Who is most likely to laugh-snort in public?' },
  { id: 'pc247', text: 'Who is most likely to trip and play it off as a dance move?' },
  { id: 'pc248', text: 'Who is most likely to reply-all by accident?' },
  { id: 'pc249', text: 'Who is most likely to get caught singing in the car?' },
  { id: 'pc250', text: 'Who is most likely to mispronounce a word for years?' },
  { id: 'pc251', text: 'Who is most likely to say "you too" at the wrong moment?' },
  { id: 'pc252', text: 'Who is most likely to like an old photo while stalking someone?' },
  { id: 'pc253', text: 'Who is most likely to autocorrect themselves into trouble?' },
  { id: 'pc254', text: 'Who is most likely to forget what they were saying mid-story?' },
  { id: 'pc255', text: 'Who is most likely to overshare in a group setting?' },
 
  // ── Travel / adventure ─────────────────────────────────────────────────────
  { id: 'pc256', text: 'Who is most likely to miss their flight?' },
  { id: 'pc257', text: 'Who is most likely to book a trip on a whim?' },
  { id: 'pc258', text: 'Who is most likely to get lost in a new city and love it?' },
  { id: 'pc259', text: 'Who is most likely to try the weirdest local food abroad?' },
  { id: 'pc260', text: 'Who is most likely to make friends with locals everywhere?' },
  { id: 'pc261', text: 'Who is most likely to forget their passport?' },
  { id: 'pc262', text: 'Who is most likely to plan a trip and never actually go?' },
  { id: 'pc263', text: 'Who is most likely to live out of a backpack for a year?' },
  { id: 'pc264', text: 'Who is most likely to take the most photos on a trip?' },
  { id: 'pc265', text: 'Who is most likely to wander off from the tour group?' },
 
  // ── Random / wildcard ──────────────────────────────────────────────────────
  { id: 'pc266', text: 'Who is most likely to believe a conspiracy theory?' },
  { id: 'pc267', text: 'Who is most likely to start a conspiracy theory?' },
  { id: 'pc268', text: 'Who is most likely to win an argument they\u2019re wrong about?' },
  { id: 'pc269', text: 'Who is most likely to befriend their Uber driver?' },
  { id: 'pc270', text: 'Who is most likely to get a weird nickname that sticks?' },
  { id: 'pc271', text: 'Who is most likely to become a legend at their old school?' },
  { id: 'pc272', text: 'Who is most likely to have a story that sounds made up but isn\u2019t?' },
  { id: 'pc273', text: 'Who is most likely to know a guy for everything?' },
  { id: 'pc274', text: 'Who is most likely to end up in a random viral video?' },
  { id: 'pc275', text: 'Who is most likely to talk their way into a VIP section?' },
  { id: 'pc276', text: 'Who is most likely to get a free upgrade just by asking?' },
  { id: 'pc277', text: 'Who is most likely to be unbothered by literally anything?' },
  { id: 'pc278', text: 'Who is most likely to make a dramatic life change overnight?' },
  { id: 'pc279', text: 'Who is most likely to peak later in life and crush it?' },
  { id: 'pc280', text: 'Who is most likely to be the subject of a future documentary?' },
];
