// ─────────────────────────────────────────────────────────────────────────────
// Stand Out — Prompt Bank
// Edit here. Prompts are picked by difficulty tier; see promptUtils.pickStandOutPrompt.
// ─────────────────────────────────────────────────────────────────────────────

export type StandOutDifficulty = 'easy' | 'medium' | 'hard';

export interface StandOutPrompt {
  id: string;
  text: string;
  difficulty: StandOutDifficulty;
}

export const STAND_OUT_PROMPTS: StandOutPrompt[] = [
  // Easy — common, high-overlap expected (tests uniqueness with simple categories)
  { id: 'so_e1',  text: 'Name a fruit',                            difficulty: 'easy' },
  { id: 'so_e2',  text: 'Name a color of the rainbow',                            difficulty: 'easy' },
  { id: 'so_e3',  text: 'Name a fast food chain',                  difficulty: 'easy' },
  { id: 'so_e4',  text: 'Name a common house pet',                              difficulty: 'easy' },
  { id: 'so_e5',  text: 'Name a movie genre',                      difficulty: 'easy' },
  { id: 'so_e6',  text: 'Name a winter sport',                            difficulty: 'easy' },
  { id: 'so_e7',  text: 'Name a country in Europe',                          difficulty: 'easy' },
  { id: 'so_e8',  text: 'Name a notable superhero',                        difficulty: 'easy' },
  { id: 'so_e9',  text: 'Name a school subject',                   difficulty: 'easy' },
  { id: 'so_e10', text: 'Name a breakfast food',                   difficulty: 'easy' },
  { id: 'so_e11', text: 'Name a soft drink brand',                       difficulty: 'easy' },
  { id: 'so_e12', text: 'Name a social media app',                 difficulty: 'easy' },
  { id: 'so_e13', text: 'Name a pizza topping',                    difficulty: 'easy' },
  { id: 'so_e14', text: 'Name a music genre',                    difficulty: 'easy' },
  { id: 'so_e15', text: 'Name a car brand',                      difficulty: 'easy' },
  { id: 'so_e16', text: 'Name a vegetable', difficulty: 'easy' },
  { id: 'so_e17', text: 'Name a candy', difficulty: 'easy' },
  { id: 'so_e18', text: 'Name a popular ice cream flavor', difficulty: 'easy' },
  { id: 'so_e19', text: 'Name a type of drink', difficulty: 'easy' },
  { id: 'so_e20', text: 'Name a pizza chain', difficulty: 'easy' },
  { id: 'so_e21', text: 'Name a sport', difficulty: 'easy' },
  { id: 'so_e22', text: 'Name a board game', difficulty: 'easy' },
  { id: 'so_e23', text: 'Name a video game', difficulty: 'easy' },
  { id: 'so_e24', text: 'Name a superhero team', difficulty: 'easy' },
  { id: 'so_e25', text: 'Name a holiday', difficulty: 'easy' },
  { id: 'so_e26', text: 'Name a month', difficulty: 'easy' },
  { id: 'so_e27', text: 'Name a day of the week', difficulty: 'easy' },
  { id: 'so_e28', text: 'Name a flower', difficulty: 'easy' },
  { id: 'so_e29', text: 'Name a tree', difficulty: 'easy' },
  { id: 'so_e30', text: 'Name a bird', difficulty: 'easy' },
  { id: 'so_e31', text: 'Name a fish', difficulty: 'easy' },
  { id: 'so_e32', text: 'Name a dessert', difficulty: 'easy' },
  { id: 'so_e33', text: 'Name a sandwich', difficulty: 'easy' },
  { id: 'so_e34', text: 'Name a phone app', difficulty: 'easy' },
  { id: 'so_e35', text: 'Name a clothing item', difficulty: 'easy' },
  { id: 'so_e36', text: 'Name a shoe type', difficulty: 'easy' },
  { id: 'so_e37', text: 'Name a kitchen appliance', difficulty: 'easy' },
  { id: 'so_e38', text: 'Name a piece of furniture', difficulty: 'easy' },
  { id: 'so_e39', text: 'Name a weather condition', difficulty: 'easy' },
  { id: 'so_e40', text: 'Name a natural disaster', difficulty: 'easy' },
  { id: 'so_e41', text: 'Name a school supply', difficulty: 'easy' },
  { id: 'so_e42', text: 'Name a body part', difficulty: 'easy' },
  { id: 'so_e43', text: 'Name a job', difficulty: 'easy' },
  { id: 'so_e44', text: 'Name a musical instrument', difficulty: 'easy' },
  { id: 'so_e45', text: 'Name a dance style', difficulty: 'easy' },
  { id: 'so_e46', text: 'Name a language', difficulty: 'easy' },
  { id: 'so_e47', text: 'Name a continent', difficulty: 'easy' },
  { id: 'so_e48', text: 'Name a planet', difficulty: 'easy' },
  { id: 'so_e49', text: 'Name a famous landmark', difficulty: 'easy' },
  { id: 'so_e50', text: 'Name a common phobia', difficulty: 'easy' },

  // Medium — more personal, fewer obvious answers
  // Medium — moderate overlap, requires smarter picks
  { id: 'so_m1',  text: 'Name a mobile phone brand',                difficulty: 'medium' },
  { id: 'so_m2',  text: 'Name a laptop brand',                      difficulty: 'medium' },
  { id: 'so_m3',  text: 'Name a shoe brand',                        difficulty: 'medium' },
  { id: 'so_m4',  text: 'Name a streaming service',                 difficulty: 'medium' },
  { id: 'so_m5',  text: 'Name a video game console',                difficulty: 'medium' },
  { id: 'so_m6',  text: 'Name a cereal brand',                      difficulty: 'medium' },
  { id: 'so_m7',  text: 'Name a chocolate brand',                   difficulty: 'medium' },
  { id: 'so_m8',  text: 'Name a clothing brand',                    difficulty: 'medium' },
  { id: 'so_m9',  text: 'Name a U.S. state',                        difficulty: 'medium' },
  { id: 'so_m10', text: 'Name a country in Asia',                   difficulty: 'medium' },
  { id: 'so_m11', text: 'Name a Disney movie',                      difficulty: 'medium' },
  { id: 'so_m12', text: 'Name a Marvel villain',                    difficulty: 'medium' },
  { id: 'so_m13', text: 'Name a sport played with a ball',          difficulty: 'medium' },
  { id: 'so_m14', text: 'Name a board game',                        difficulty: 'medium' },
  { id: 'so_m15', text: 'Name a popular mobile app (non-social)',   difficulty: 'medium' },
  { id: 'so_m16', text: 'Name a smartphone feature', difficulty: 'medium' },
  { id: 'so_m17', text: 'Name a car brand from Japan', difficulty: 'medium' },
  { id: 'so_m18', text: 'Name a country in Africa', difficulty: 'medium' },
  { id: 'so_m19', text: 'Name a type of coffee drink', difficulty: 'medium' },
  { id: 'so_m20', text: 'Name a sneaker brand', difficulty: 'medium' },
  { id: 'so_m21', text: 'Name a fast food menu item', difficulty: 'medium' },
  { id: 'so_m22', text: 'Name a Disney villain', difficulty: 'medium' },
  { id: 'so_m23', text: 'Name a Pixar movie', difficulty: 'medium' },
  { id: 'so_m24', text: 'Name a popular YouTuber', difficulty: 'medium' },
  { id: 'so_m25', text: 'Name a streaming show', difficulty: 'medium' },
  { id: 'so_m26', text: 'Name a card game', difficulty: 'medium' },
  { id: 'so_m27', text: 'Name a board game piece', difficulty: 'medium' },
  { id: 'so_m28', text: 'Name a type of pasta', difficulty: 'medium' },
  { id: 'so_m29', text: 'Name a type of cheese', difficulty: 'medium' },
  { id: 'so_m30', text: 'Name a soda flavor', difficulty: 'medium' },
  { id: 'so_m31', text: 'Name a type of hat', difficulty: 'medium' },
  { id: 'so_m32', text: 'Name a type of jacket', difficulty: 'medium' },
  { id: 'so_m33', text: 'Name a phone accessory', difficulty: 'medium' },
  { id: 'so_m34', text: 'Name a sport played indoors', difficulty: 'medium' },
  { id: 'so_m35', text: 'Name a sport played outdoors', difficulty: 'medium' },
  { id: 'so_m36', text: 'Name a type of workout', difficulty: 'medium' },
  { id: 'so_m37', text: 'Name a type of dance', difficulty: 'medium' },
  { id: 'so_m38', text: 'Name a type of art', difficulty: 'medium' },
  { id: 'so_m39', text: 'Name a type of music instrument', difficulty: 'medium' },
  { id: 'so_m40', text: 'Name a type of dog', difficulty: 'medium' },
  { id: 'so_m41', text: 'Name a type of cat breed', difficulty: 'medium' },
  { id: 'so_m42', text: 'Name a city in the U.S.', difficulty: 'medium' },
  { id: 'so_m43', text: 'Name a European capital', difficulty: 'medium' },
  { id: 'so_m44', text: 'Name a type of currency', difficulty: 'medium' },
  { id: 'so_m45', text: 'Name a type of vehicle', difficulty: 'medium' },
  { id: 'so_m46', text: 'Name a type of airplane', difficulty: 'medium' },
  { id: 'so_m47', text: 'Name a type of boat', difficulty: 'medium' },
  { id: 'so_m48', text: 'Name a type of store', difficulty: 'medium' },
  { id: 'so_m49', text: 'Name a type of restaurant', difficulty: 'medium' },
  { id: 'so_m50', text: 'Name a type of dessert', difficulty: 'medium' },

  // Hard — spicy, social, more open-ended
  // Hard — constrained, strategic, low overlap
  { id: 'so_h1',  text: 'Name a car brand that starts with B',      difficulty: 'hard' },
  { id: 'so_h2',  text: 'Name a country that starts with S',        difficulty: 'hard' },
  { id: 'so_h3',  text: 'Name a fruit that is red',                 difficulty: 'hard' },
  { id: 'so_h4',  text: 'Name a U.S. state with no coastline',      difficulty: 'hard' },
  { id: 'so_h5',  text: 'Name a prime number under 20',             difficulty: 'hard' },
  { id: 'so_h6',  text: 'Name a planet in the solar system (not Earth)', difficulty: 'hard' },
  { id: 'so_h7',  text: 'Name a chemical element',                  difficulty: 'hard' },
  { id: 'so_h8',  text: 'Name a programming language',              difficulty: 'hard' },
  { id: 'so_h9',  text: 'Name a chess piece',                       difficulty: 'hard' },
  { id: 'so_h10', text: 'Name a letter in the Greek alphabet',      difficulty: 'hard' },
  { id: 'so_h11', text: 'Name a country with a population over 100 million', difficulty: 'hard' },
  { id: 'so_h12', text: 'Name a famous scientist',                  difficulty: 'hard' },
  { id: 'so_h13', text: 'Name a musical instrument with strings',   difficulty: 'hard' },
  { id: 'so_h14', text: 'Name a unit of measurement',               difficulty: 'hard' },
  { id: 'so_h15', text: 'Name a word that starts with “Z”',         difficulty: 'hard' },
  { id: 'so_h16', text: 'Name a country that starts with B', difficulty: 'hard' },
  { id: 'so_h17', text: 'Name a fruit that starts with P', difficulty: 'hard' },
  { id: 'so_h18', text: 'Name a car brand that starts with T', difficulty: 'hard' },
  { id: 'so_h19', text: 'Name a U.S. state that starts with M', difficulty: 'hard' },
  { id: 'so_h20', text: 'Name a word that ends with “ing”', difficulty: 'hard' },
  { id: 'so_h21', text: 'Name a prime number under 50', difficulty: 'hard' },
  { id: 'so_h22', text: 'Name an even number between 10 and 30', difficulty: 'hard' },
  { id: 'so_h23', text: 'Name a chemical element that starts with C', difficulty: 'hard' },
  { id: 'so_h24', text: 'Name a planet besides Earth and Mars', difficulty: 'hard' },
  { id: 'so_h28', text: 'Name a country with a flag that has red', difficulty: 'hard' },
  { id: 'so_h29', text: 'Name a word with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h30', text: 'Name a word that rhymes with “cat”', difficulty: 'hard' },
  { id: 'so_h31', text: 'Name a sport that uses a net', difficulty: 'hard' },
  { id: 'so_h32', text: 'Name a fruit that is yellow', difficulty: 'hard' },
  { id: 'so_h33', text: 'Name a country with more than 50 million people', difficulty: 'hard' },
  { id: 'so_h34', text: 'Name a number divisible by 3', difficulty: 'hard' },
  { id: 'so_h35', text: 'Name a number greater than 100 but less than 110', difficulty: 'hard' },
  { id: 'so_h36', text: 'Name a word that starts with “Q”', difficulty: 'hard' },
  { id: 'so_h37', text: 'Name a type of triangle', difficulty: 'hard' },
  { id: 'so_h38', text: 'Name a shape with more than 4 sides', difficulty: 'hard' },
  { id: 'so_h39', text: 'Name a unit of time', difficulty: 'hard' },
  { id: 'so_h40', text: 'Name a type of energy', difficulty: 'hard' },
  { id: 'so_h41', text: 'Name a type of cloud', difficulty: 'hard' },
  { id: 'so_h42', text: 'Name a type of rock', difficulty: 'hard' },
  { id: 'so_h43', text: 'Name a word that starts with “X”', difficulty: 'hard' },
  { id: 'so_h44', text: 'Name a word that contains “zz”', difficulty: 'hard' },
  { id: 'so_h45', text: 'Name a word that starts with a vowel', difficulty: 'hard' },
  { id: 'so_h46', text: 'Name a number between 1 and 10', difficulty: 'hard' },
  { id: 'so_h47', text: 'Name a month with 31 days', difficulty: 'hard' },
  { id: 'so_h48', text: 'Name a day that starts with T', difficulty: 'hard' },
  { id: 'so_h49', text: 'Name a country that ends with “land”', difficulty: 'hard' },
  { id: 'so_h50', text: 'Name a word that ends with “er”', difficulty: 'hard' },
];
