// ─────────────────────────────────────────────────────────────────────────────
// Stand Out — Prompt Bank
// Edit here. Prompts are picked by difficulty tier; see promptUtils.pickStandOutPrompt.
// ─────────────────────────────────────────────────────────────────────────────

export type StandOutDifficulty = 'easy' | 'medium' | 'hard';

export interface StandOutPrompt {
  id: string;
  text: string;
  difficulty: StandOutDifficulty;
}

export const STAND_OUT_PROMPTS: StandOutPrompt[] = [
  { id: 'so_e51', text: 'Name a type of sandwich bread', difficulty: 'easy' },
  { id: 'so_e52', text: 'Name a smoothie ingredient', difficulty: 'easy' },
  { id: 'so_e53', text: 'Name something you wear in winter', difficulty: 'easy' },
  { id: 'so_e54', text: 'Name something you bring to the beach', difficulty: 'easy' },
  { id: 'so_e55', text: 'Name something found in a fridge', difficulty: 'easy' },
  { id: 'so_e56', text: 'Name a type of pizza crust', difficulty: 'easy' },
  { id: 'so_e57', text: 'Name an ice cream topping', difficulty: 'easy' },
  { id: 'so_e58', text: 'Name something spicy', difficulty: 'easy' },
  { id: 'so_e59', text: 'Name a type of soup', difficulty: 'easy' },
  { id: 'so_e60', text: 'Name something crunchy', difficulty: 'easy' },
  { id: 'so_e61', text: 'Name something you do before bed', difficulty: 'easy' },
  { id: 'so_e62', text: 'Name something you do after waking up', difficulty: 'easy' },
  { id: 'so_e63', text: 'Name something in your bathroom', difficulty: 'easy' },
  { id: 'so_e64', text: 'Name something in your kitchen', difficulty: 'easy' },
  { id: 'so_e65', text: 'Name something in your living room', difficulty: 'easy' },
  { id: 'so_e66', text: 'Name something you sit on', difficulty: 'easy' },
  { id: 'so_e67', text: 'Name something you plug in', difficulty: 'easy' },
  { id: 'so_e68', text: 'Name something that lights up', difficulty: 'easy' },
  { id: 'so_e69', text: 'Name something you throw away', difficulty: 'easy' },
  { id: 'so_e70', text: 'Name something you recycle', difficulty: 'easy' },
  { id: 'so_e71', text: 'Name something you do at a party', difficulty: 'easy' },
  { id: 'so_e72', text: 'Name something you do at school', difficulty: 'easy' },
  { id: 'so_e73', text: 'Name something you do on vacation', difficulty: 'easy' },
  { id: 'so_e74', text: 'Name something you do in summer', difficulty: 'easy' },
  { id: 'so_e75', text: 'Name something you do in winter', difficulty: 'easy' },
  { id: 'so_e76', text: 'Name something you do when bored', difficulty: 'easy' },
  { id: 'so_e77', text: 'Name something you do when tired', difficulty: 'easy' },
  { id: 'so_e78', text: 'Name something you do when sick', difficulty: 'easy' },
  { id: 'so_e79', text: 'Name something you do when happy', difficulty: 'easy' },
  { id: 'so_e80', text: 'Name something you do when stressed', difficulty: 'easy' },
  { id: 'so_e81', text: 'Name something you eat with your hands', difficulty: 'easy' },
  { id: 'so_e82', text: 'Name something you drink cold', difficulty: 'easy' },
  { id: 'so_e83', text: 'Name something you drink hot', difficulty: 'easy' },
  { id: 'so_e84', text: 'Name something sweet', difficulty: 'easy' },
  { id: 'so_e85', text: 'Name something salty', difficulty: 'easy' },
  { id: 'so_e86', text: 'Name something sour', difficulty: 'easy' },
  { id: 'so_e87', text: 'Name something bitter', difficulty: 'easy' },
  { id: 'so_e88', text: 'Name something soft', difficulty: 'easy' },
  { id: 'so_e89', text: 'Name something hard', difficulty: 'easy' },
  { id: 'so_e90', text: 'Name something chewy', difficulty: 'easy' },
  { id: 'so_e91', text: 'Name something in a backpack', difficulty: 'easy' },
  { id: 'so_e92', text: 'Name something in a locker', difficulty: 'easy' },
  { id: 'so_e93', text: 'Name something in a car', difficulty: 'easy' },
  { id: 'so_e94', text: 'Name something in a garage', difficulty: 'easy' },
  { id: 'so_e95', text: 'Name something in a park', difficulty: 'easy' },
  { id: 'so_e96', text: 'Name something at a gym', difficulty: 'easy' },
  { id: 'so_e97', text: 'Name something at a restaurant', difficulty: 'easy' },
  { id: 'so_e98', text: 'Name something at a movie theater', difficulty: 'easy' },
  { id: 'so_e99', text: 'Name something at a concert', difficulty: 'easy' },
  { id: 'so_e100', text: 'Name something at a stadium', difficulty: 'easy' },
  { id: 'so_e101', text: 'Name a board game piece', difficulty: 'easy' },
  { id: 'so_e102', text: 'Name a type of bag', difficulty: 'easy' },
  { id: 'so_e103', text: 'Name a type of candy bar', difficulty: 'easy' },
  { id: 'so_e104', text: 'Name a type of chip flavor', difficulty: 'easy' },
  { id: 'so_e105', text: 'Name a breakfast drink', difficulty: 'easy' },
  { id: 'so_e106', text: 'Name a kind of taco filling', difficulty: 'easy' },
  { id: 'so_e107', text: 'Name a type of noodle', difficulty: 'easy' },
  { id: 'so_e108', text: 'Name a kind of dipping sauce', difficulty: 'easy' },
  { id: 'so_e109', text: 'Name something on a pizza', difficulty: 'easy' },
  { id: 'so_e110', text: 'Name a flavor of gum', difficulty: 'easy' },
  { id: 'so_e111', text: 'Name a type of cookie', difficulty: 'easy' },
  { id: 'so_e112', text: 'Name a type of cake', difficulty: 'easy' },
  { id: 'so_e113', text: 'Name a donut flavor', difficulty: 'easy' },
  { id: 'so_e114', text: 'Name a milkshake flavor', difficulty: 'easy' },
  { id: 'so_e115', text: 'Name a cereal topping', difficulty: 'easy' },
  { id: 'so_e116', text: 'Name something in a vending machine', difficulty: 'easy' },
  { id: 'so_e117', text: 'Name something in a lunchbox', difficulty: 'easy' },
  { id: 'so_e118', text: 'Name something served at a barbecue', difficulty: 'easy' },
  { id: 'so_e119', text: 'Name something you\'d find at a carnival', difficulty: 'easy' },
  { id: 'so_e120', text: 'Name something sold at a food truck', difficulty: 'easy' },
  { id: 'so_e121', text: 'Name an animal at a zoo', difficulty: 'easy' },
  { id: 'so_e122', text: 'Name a farm animal', difficulty: 'easy' },
  { id: 'so_e123', text: 'Name a sea creature', difficulty: 'easy' },
  { id: 'so_e124', text: 'Name a jungle animal', difficulty: 'easy' },
  { id: 'so_e125', text: 'Name a pet store animal', difficulty: 'easy' },
  { id: 'so_e126', text: 'Name something with feathers', difficulty: 'easy' },
  { id: 'so_e127', text: 'Name something with fur', difficulty: 'easy' },
  { id: 'so_e128', text: 'Name something with scales', difficulty: 'easy' },
  { id: 'so_e129', text: 'Name an animal that hops', difficulty: 'easy' },
  { id: 'so_e130', text: 'Name an animal that swims', difficulty: 'easy' },
  { id: 'so_e131', text: 'Name something in the sky', difficulty: 'easy' },
  { id: 'so_e132', text: 'Name something at the bottom of the ocean', difficulty: 'easy' },
  { id: 'so_e133', text: 'Name something in a forest', difficulty: 'easy' },
  { id: 'so_e134', text: 'Name something in the desert', difficulty: 'easy' },
  { id: 'so_e135', text: 'Name something near a river', difficulty: 'easy' },
  { id: 'so_e136', text: 'Name a kind of tree', difficulty: 'easy' },
  { id: 'so_e137', text: 'Name a flower color', difficulty: 'easy' },
  { id: 'so_e138', text: 'Name a weather condition', difficulty: 'easy' },
  { id: 'so_e139', text: 'Name something seen during a storm', difficulty: 'easy' },
  { id: 'so_e140', text: 'Name something seen at night', difficulty: 'easy' },
  { id: 'so_e141', text: 'Name a school subject', difficulty: 'easy' },
  { id: 'so_e142', text: 'Name a classroom supply', difficulty: 'easy' },
  { id: 'so_e143', text: 'Name something written with', difficulty: 'easy' },
  { id: 'so_e144', text: 'Name something erased', difficulty: 'easy' },
  { id: 'so_e145', text: 'Name something you read', difficulty: 'easy' },
  { id: 'so_e146', text: 'Name something you study for', difficulty: 'easy' },
  { id: 'so_e147', text: 'Name something on a test', difficulty: 'easy' },
  { id: 'so_e148', text: 'Name a reason to raise your hand', difficulty: 'easy' },
  { id: 'so_e149', text: 'Name something in a science lab', difficulty: 'easy' },
  { id: 'so_e150', text: 'Name something in math class', difficulty: 'easy' },
  { id: 'so_e151', text: 'Name an app on a phone', difficulty: 'easy' },
  { id: 'so_e152', text: 'Name a thing you use a charger for', difficulty: 'easy' },
  { id: 'so_e153', text: 'Name something with a screen', difficulty: 'easy' },
  { id: 'so_e154', text: 'Name something with buttons', difficulty: 'easy' },
  { id: 'so_e155', text: 'Name something with a camera', difficulty: 'easy' },
  { id: 'so_e156', text: 'Name something you can text on', difficulty: 'easy' },
  { id: 'so_e157', text: 'Name something you can game on', difficulty: 'easy' },
  { id: 'so_e158', text: 'Name something you can stream on', difficulty: 'easy' },
  { id: 'so_e159', text: 'Name something you wear on your wrist', difficulty: 'easy' },
  { id: 'so_e160', text: 'Name something that buzzes', difficulty: 'easy' },
  { id: 'so_e161', text: 'Name a sport played indoors', difficulty: 'easy' },
  { id: 'so_e162', text: 'Name a sport played outdoors', difficulty: 'easy' },
  { id: 'so_e163', text: 'Name something used in basketball', difficulty: 'easy' },
  { id: 'so_e164', text: 'Name something used in soccer', difficulty: 'easy' },
  { id: 'so_e165', text: 'Name something used in baseball', difficulty: 'easy' },
  { id: 'so_e166', text: 'Name something used in tennis', difficulty: 'easy' },
  { id: 'so_e167', text: 'Name something used in football', difficulty: 'easy' },
  { id: 'so_e168', text: 'Name something used in golf', difficulty: 'easy' },
  { id: 'so_e169', text: 'Name something worn by an athlete', difficulty: 'easy' },
  { id: 'so_e170', text: 'Name something seen in a locker room', difficulty: 'easy' },
  { id: 'so_e171', text: 'Name something at an amusement park', difficulty: 'easy' },
  { id: 'so_e172', text: 'Name something at an arcade', difficulty: 'easy' },
  { id: 'so_e173', text: 'Name something at a sleepover', difficulty: 'easy' },
  { id: 'so_e174', text: 'Name something at a birthday party', difficulty: 'easy' },
  { id: 'so_e175', text: 'Name something at a wedding', difficulty: 'easy' },
  { id: 'so_e176', text: 'Name something at a mall', difficulty: 'easy' },
  { id: 'so_e177', text: 'Name something at a grocery store', difficulty: 'easy' },
  { id: 'so_e178', text: 'Name something at a gas station', difficulty: 'easy' },
  { id: 'so_e179', text: 'Name something at an airport', difficulty: 'easy' },
  { id: 'so_e180', text: 'Name something at a hotel', difficulty: 'easy' },
  { id: 'so_e181', text: 'Name a type of shoe', difficulty: 'easy' },
  { id: 'so_e182', text: 'Name a type of jacket', difficulty: 'easy' },
  { id: 'so_e183', text: 'Name a type of hat', difficulty: 'easy' },
  { id: 'so_e184', text: 'Name a type of necklace', difficulty: 'easy' },
  { id: 'so_e185', text: 'Name a type of hairstyle', difficulty: 'easy' },
  { id: 'so_e186', text: 'Name something worn in summer', difficulty: 'easy' },
  { id: 'so_e187', text: 'Name something worn in the rain', difficulty: 'easy' },
  { id: 'so_e188', text: 'Name something worn to sleep', difficulty: 'easy' },
  { id: 'so_e189', text: 'Name something worn to a party', difficulty: 'easy' },
  { id: 'so_e190', text: 'Name something worn at the gym', difficulty: 'easy' },
  { id: 'so_e191', text: 'Name a musical instrument', difficulty: 'easy' },
  { id: 'so_e192', text: 'Name something in a band', difficulty: 'easy' },
  { id: 'so_e193', text: 'Name something on a stage', difficulty: 'easy' },
  { id: 'so_e194', text: 'Name something in a song', difficulty: 'easy' },
  { id: 'so_e195', text: 'Name something a DJ uses', difficulty: 'easy' },
  { id: 'so_e196', text: 'Name something a singer holds', difficulty: 'easy' },
  { id: 'so_e197', text: 'Name something that has strings', difficulty: 'easy' },
  { id: 'so_e198', text: 'Name something that has keys', difficulty: 'easy' },
  { id: 'so_e199', text: 'Name something that has speakers', difficulty: 'easy' },
  { id: 'so_e200', text: 'Name something that plays music', difficulty: 'easy' },
  { id: 'so_e201', text: 'Name a superhero power', difficulty: 'easy' },
  { id: 'so_e202', text: 'Name a fantasy creature', difficulty: 'easy' },
  { id: 'so_e203', text: 'Name something in outer space', difficulty: 'easy' },
  { id: 'so_e204', text: 'Name something in a video game', difficulty: 'easy' },
  { id: 'so_e205', text: 'Name something in a treasure chest', difficulty: 'easy' },
  { id: 'so_e206', text: 'Name something a pirate has', difficulty: 'easy' },
  { id: 'so_e207', text: 'Name something a wizard uses', difficulty: 'easy' },
  { id: 'so_e208', text: 'Name something a knight wears', difficulty: 'easy' },
  { id: 'so_e209', text: 'Name something a dragon could protect', difficulty: 'easy' },
  { id: 'so_e210', text: 'Name something found in a castle', difficulty: 'easy' },
  { id: 'so_e211', text: 'Name something made of wood', difficulty: 'easy' },
  { id: 'so_e212', text: 'Name something made of glass', difficulty: 'easy' },
  { id: 'so_e213', text: 'Name something made of metal', difficulty: 'easy' },
  { id: 'so_e214', text: 'Name something made of plastic', difficulty: 'easy' },
  { id: 'so_e215', text: 'Name something made of paper', difficulty: 'easy' },
  { id: 'so_e216', text: 'Name something that folds', difficulty: 'easy' },
  { id: 'so_e217', text: 'Name something that rolls', difficulty: 'easy' },
  { id: 'so_e218', text: 'Name something that bounces', difficulty: 'easy' },
  { id: 'so_e219', text: 'Name something that spins', difficulty: 'easy' },
  { id: 'so_e220', text: 'Name something that melts', difficulty: 'easy' },
  { id: 'so_e221', text: 'Name something you can win', difficulty: 'easy' },
  { id: 'so_e222', text: 'Name something you can lose', difficulty: 'easy' },
  { id: 'so_e223', text: 'Name something you can share', difficulty: 'easy' },
  { id: 'so_e224', text: 'Name something you can hide', difficulty: 'easy' },
  { id: 'so_e225', text: 'Name something you can collect', difficulty: 'easy' },
  { id: 'so_e226', text: 'Name something you can trade', difficulty: 'easy' },
  { id: 'so_e227', text: 'Name something you can upgrade', difficulty: 'easy' },
  { id: 'so_e228', text: 'Name something you can repair', difficulty: 'easy' },
  { id: 'so_e229', text: 'Name something you can customize', difficulty: 'easy' },
  { id: 'so_e230', text: 'Name something you can decorate', difficulty: 'easy' },
  { id: 'so_e231', text: 'Name something that smells good', difficulty: 'easy' },
  { id: 'so_e232', text: 'Name something that smells bad', difficulty: 'easy' },
  { id: 'so_e233', text: 'Name something that tastes fresh', difficulty: 'easy' },
  { id: 'so_e234', text: 'Name something that tastes bland', difficulty: 'easy' },
  { id: 'so_e235', text: 'Name something that feels smooth', difficulty: 'easy' },
  { id: 'so_e236', text: 'Name something that feels rough', difficulty: 'easy' },
  { id: 'so_e237', text: 'Name something that feels sticky', difficulty: 'easy' },
  { id: 'so_e238', text: 'Name something that feels slippery', difficulty: 'easy' },
  { id: 'so_e239', text: 'Name something that feels fuzzy', difficulty: 'easy' },
  { id: 'so_e240', text: 'Name something that feels sharp', difficulty: 'easy' },
  { id: 'so_e241', text: 'Name something that moves fast', difficulty: 'easy' },
  { id: 'so_e242', text: 'Name something that moves slow', difficulty: 'easy' },
  { id: 'so_e243', text: 'Name something that makes noise', difficulty: 'easy' },
  { id: 'so_e244', text: 'Name something that is silent', difficulty: 'easy' },
  { id: 'so_e245', text: 'Name something that is bright', difficulty: 'easy' },
  { id: 'so_e246', text: 'Name something that is dark', difficulty: 'easy' },
  { id: 'so_e247', text: 'Name something that is heavy', difficulty: 'easy' },
  { id: 'so_e248', text: 'Name something that is light', difficulty: 'easy' },
  { id: 'so_e249', text: 'Name something that is expensive', difficulty: 'easy' },
  { id: 'so_e250', text: 'Name something that is rare', difficulty: 'easy' },
  { id: 'so_h51', text: 'Name a fruit with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h52', text: 'Name a country with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h53', text: 'Name a U.S. state starting with A', difficulty: 'hard' },
  { id: 'so_h54', text: 'Name a word ending in ly', difficulty: 'hard' },
  { id: 'so_h55', text: 'Name a word with double letters', difficulty: 'hard' },
  { id: 'so_h56', text: 'Name a number divisible by 7', difficulty: 'hard' },
  { id: 'so_h57', text: 'Name a number between 30 and 40', difficulty: 'hard' },
  { id: 'so_h58', text: 'Name a word with 3 syllables', difficulty: 'hard' },
  { id: 'so_h59', text: 'Name a word starting with un', difficulty: 'hard' },
  { id: 'so_h60', text: 'Name a word ending in ment', difficulty: 'hard' },
  { id: 'so_h61', text: 'Name a bird that cannot fly', difficulty: 'hard' },
  { id: 'so_h62', text: 'Name a planet with rings', difficulty: 'hard' },
  { id: 'so_h63', text: 'Name a chess piece that is not a pawn', difficulty: 'hard' },
  { id: 'so_h64', text: 'Name a Greek letter after alpha', difficulty: 'hard' },
  { id: 'so_h65', text: 'Name a programming language starting with C', difficulty: 'hard' },
  { id: 'so_h66', text: 'Name a unit of length', difficulty: 'hard' },
  { id: 'so_h67', text: 'Name a unit of weight', difficulty: 'hard' },
  { id: 'so_h68', text: 'Name a type of triangle with equal sides', difficulty: 'hard' },
  { id: 'so_h69', text: 'Name a polygon with 8 sides', difficulty: 'hard' },
  { id: 'so_h70', text: 'Name a shape with 3 sides', difficulty: 'hard' },
  { id: 'so_h71', text: 'Name a country ending in ia', difficulty: 'hard' },
  { id: 'so_h72', text: 'Name a word that rhymes with blue', difficulty: 'hard' },
  { id: 'so_h73', text: 'Name a word with 4 vowels', difficulty: 'hard' },
  { id: 'so_h74', text: 'Name a number divisible by 11', difficulty: 'hard' },
  { id: 'so_h75', text: 'Name a fruit starting with B', difficulty: 'hard' },
  { id: 'so_h76', text: 'Name a country starting with D', difficulty: 'hard' },
  { id: 'so_h77', text: 'Name a U.S. state starting with N', difficulty: 'hard' },
  { id: 'so_h78', text: 'Name a word ending with tion', difficulty: 'hard' },
  { id: 'so_h79', text: 'Name a word with exactly 7 letters', difficulty: 'hard' },
  { id: 'so_h80', text: 'Name a number between 90 and 100', difficulty: 'hard' },
  { id: 'so_h81', text: 'Name a type of triangle with no equal sides', difficulty: 'hard' },
  { id: 'so_h82', text: 'Name a word starting with pre', difficulty: 'hard' },
  { id: 'so_h83', text: 'Name a word ending with est', difficulty: 'hard' },
  { id: 'so_h84', text: 'Name a number divisible by 9', difficulty: 'hard' },
  { id: 'so_h85', text: 'Name a number between 200 and 210', difficulty: 'hard' },
  { id: 'so_h86', text: 'Name a word with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h87', text: 'Name a word starting with tri', difficulty: 'hard' },
  { id: 'so_h88', text: 'Name a word containing ph', difficulty: 'hard' },
  { id: 'so_h89', text: 'Name a word ending with ize', difficulty: 'hard' },
  { id: 'so_h90', text: 'Name a word starting with ex', difficulty: 'hard' },
  { id: 'so_h91', text: 'Name a word with exactly 2 vowels', difficulty: 'hard' },
  { id: 'so_h92', text: 'Name a word with exactly 3 consonants', difficulty: 'hard' },
  { id: 'so_h93', text: 'Name a number divisible by 4', difficulty: 'hard' },
  { id: 'so_h94', text: 'Name a number between 60 and 70', difficulty: 'hard' },
  { id: 'so_h95', text: 'Name a word starting with sub', difficulty: 'hard' },
  { id: 'so_h96', text: 'Name a word ending with ful', difficulty: 'hard' },
  { id: 'so_h97', text: 'Name a word containing oo', difficulty: 'hard' },
  { id: 'so_h98', text: 'Name a word containing ea', difficulty: 'hard' },
  { id: 'so_h99', text: 'Name a word with exactly 8 letters', difficulty: 'hard' },
  { id: 'so_h100', text: 'Name a number divisible by 6', difficulty: 'hard' },
  { id: 'so_h101', text: 'Name a number between 500 and 510', difficulty: 'hard' },
  { id: 'so_h102', text: 'Name a word starting with over', difficulty: 'hard' },
  { id: 'so_h103', text: 'Name a word ending with less', difficulty: 'hard' },
  { id: 'so_h104', text: 'Name a word with exactly 9 letters', difficulty: 'hard' },
  { id: 'so_h105', text: 'Name a word starting with mis', difficulty: 'hard' },
  { id: 'so_h106', text: 'Name a number divisible by 12', difficulty: 'hard' },
  { id: 'so_h107', text: 'Name a number between 1000 and 1010', difficulty: 'hard' },
  { id: 'so_h108', text: 'Name a word with exactly 10 letters', difficulty: 'hard' },
  { id: 'so_h109', text: 'Name a word containing str', difficulty: 'hard' },
  { id: 'so_h110', text: 'Name a word containing ght', difficulty: 'hard' },
  { id: 'so_h111', text: 'Name a word ending with ship', difficulty: 'hard' },
  { id: 'so_h112', text: 'Name a word starting with auto', difficulty: 'hard' },
  { id: 'so_h113', text: 'Name a word ending with ward', difficulty: 'hard' },
  { id: 'so_h114', text: 'Name a word starting with inter', difficulty: 'hard' },
  { id: 'so_h115', text: 'Name a word ending with ology', difficulty: 'hard' },
  { id: 'so_h116', text: 'Name a word containing scr', difficulty: 'hard' },
  { id: 'so_h117', text: 'Name a word with exactly 11 letters', difficulty: 'hard' },
  { id: 'so_h118', text: 'Name a word starting with trans', difficulty: 'hard' },
  { id: 'so_h119', text: 'Name a word ending with able', difficulty: 'hard' },
  { id: 'so_h120', text: 'Name a word containing kn', difficulty: 'hard' },
  { id: 'so_h121', text: 'Name a word containing wr', difficulty: 'hard' },
  { id: 'so_h122', text: 'Name a country starting with Q', difficulty: 'hard' },
  { id: 'so_h123', text: 'Name a fruit starting with G', difficulty: 'hard' },
  { id: 'so_h124', text: 'Name a U.S. state starting with W', difficulty: 'hard' },
  { id: 'so_h125', text: 'Name a word ending with ness', difficulty: 'hard' },
  { id: 'so_h126', text: 'Name a word starting with anti', difficulty: 'hard' },
  { id: 'so_h127', text: 'Name a number divisible by 13', difficulty: 'hard' },
  { id: 'so_h128', text: 'Name a number between 70 and 80', difficulty: 'hard' },
  { id: 'so_h129', text: 'Name a word containing qu', difficulty: 'hard' },
  { id: 'so_h130', text: 'Name a word containing tch', difficulty: 'hard' },
  { id: 'so_h131', text: 'Name a word ending with ive', difficulty: 'hard' },
  { id: 'so_h132', text: 'Name a planet that is not Earth or Mars', difficulty: 'hard' },
  { id: 'so_h133', text: 'Name a chemical element starting with B', difficulty: 'hard' },
  { id: 'so_h134', text: 'Name a gemstone starting with A', difficulty: 'hard' },
  { id: 'so_h135', text: 'Name a musical instrument starting with V', difficulty: 'hard' },
  { id: 'so_h136', text: 'Name a language starting with J', difficulty: 'hard' },
  { id: 'so_h137', text: 'Name a country starting with Y', difficulty: 'hard' },
  { id: 'so_h138', text: 'Name a word ending with ary', difficulty: 'hard' },
  { id: 'so_h139', text: 'Name a word starting with co', difficulty: 'hard' },
  { id: 'so_h140', text: 'Name a number divisible by 8', difficulty: 'hard' },
  { id: 'so_h141', text: 'Name a number between 400 and 410', difficulty: 'hard' },
  { id: 'so_h142', text: 'Name a word with exactly 12 letters', difficulty: 'hard' },
  { id: 'so_h143', text: 'Name a word containing pt', difficulty: 'hard' },
  { id: 'so_h144', text: 'Name a word ending with ant', difficulty: 'hard' },
  { id: 'so_h145', text: 'Name a bird starting with P', difficulty: 'hard' },
  { id: 'so_h146', text: 'Name a sea animal starting with S', difficulty: 'hard' },
  { id: 'so_h147', text: 'Name a car brand starting with F', difficulty: 'hard' },
  { id: 'so_h148', text: 'Name a U.S. state starting with O', difficulty: 'hard' },
  { id: 'so_h149', text: 'Name a word starting with dis', difficulty: 'hard' },
  { id: 'so_h150', text: 'Name a word ending with or', difficulty: 'hard' },
  { id: 'so_h151', text: 'Name a number divisible by 5 and 3', difficulty: 'hard' },
  { id: 'so_h152', text: 'Name a number between 150 and 160', difficulty: 'hard' },
  { id: 'so_h153', text: 'Name a word containing mp', difficulty: 'hard' },
  { id: 'so_h154', text: 'Name a word containing nd', difficulty: 'hard' },
  { id: 'so_h155', text: 'Name a word ending with er', difficulty: 'hard' },
  { id: 'so_h156', text: 'Name a word starting with re', difficulty: 'hard' },
  { id: 'so_h157', text: 'Name a word with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h158', text: 'Name a country starting with L', difficulty: 'hard' },
  { id: 'so_h159', text: 'Name a fruit starting with M', difficulty: 'hard' },
  { id: 'so_h160', text: 'Name a word ending with al', difficulty: 'hard' },
  { id: 'so_h161', text: 'Name a word starting with out', difficulty: 'hard' },
  { id: 'so_h162', text: 'Name a number divisible by 14', difficulty: 'hard' },
  { id: 'so_h163', text: 'Name a number between 20 and 25', difficulty: 'hard' },
  { id: 'so_h164', text: 'Name a word containing cl', difficulty: 'hard' },
  { id: 'so_h165', text: 'Name a word containing br', difficulty: 'hard' },
  { id: 'so_h166', text: 'Name a word ending with ic', difficulty: 'hard' },
  { id: 'so_h167', text: 'Name a type of cloud', difficulty: 'hard' },
  { id: 'so_h168', text: 'Name a rock type', difficulty: 'hard' },
  { id: 'so_h169', text: 'Name an energy source', difficulty: 'hard' },
  { id: 'so_h170', text: 'Name a continent that is not Asia', difficulty: 'hard' },
  { id: 'so_h171', text: 'Name a body part with 5 letters', difficulty: 'hard' },
  { id: 'so_h172', text: 'Name a word starting with non', difficulty: 'hard' },
  { id: 'so_h173', text: 'Name a word ending with ary', difficulty: 'hard' },
  { id: 'so_h174', text: 'Name a number between 250 and 260', difficulty: 'hard' },
  { id: 'so_h175', text: 'Name a word with exactly 13 letters', difficulty: 'hard' },
  { id: 'so_h176', text: 'Name a word containing gl', difficulty: 'hard' },
  { id: 'so_h177', text: 'Name a word containing ct', difficulty: 'hard' },
  { id: 'so_h178', text: 'Name a word ending with dom', difficulty: 'hard' },
  { id: 'so_h179', text: 'Name a word starting with post', difficulty: 'hard' },
  { id: 'so_h180', text: 'Name a country starting with K', difficulty: 'hard' },
  { id: 'so_h181', text: 'Name a fruit starting with C', difficulty: 'hard' },
  { id: 'so_h182', text: 'Name a word ending with age', difficulty: 'hard' },
  { id: 'so_h183', text: 'Name a word starting with micro', difficulty: 'hard' },
  { id: 'so_h184', text: 'Name a number divisible by 15', difficulty: 'hard' },
  { id: 'so_h185', text: 'Name a number between 800 and 810', difficulty: 'hard' },
  { id: 'so_h186', text: 'Name a word containing fr', difficulty: 'hard' },
  { id: 'so_h187', text: 'Name a word containing sw', difficulty: 'hard' },
  { id: 'so_h188', text: 'Name a word ending with hood', difficulty: 'hard' },
  { id: 'so_h189', text: 'Name a moon of a planet', difficulty: 'hard' },
  { id: 'so_h190', text: 'Name a unit of time', difficulty: 'hard' },
  { id: 'so_h191', text: 'Name a programming language starting with R', difficulty: 'hard' },
  { id: 'so_h192', text: 'Name a metal starting with S', difficulty: 'hard' },
  { id: 'so_h193', text: 'Name a country starting with U', difficulty: 'hard' },
  { id: 'so_h194', text: 'Name a word starting with under', difficulty: 'hard' },
  { id: 'so_h195', text: 'Name a word ending with some', difficulty: 'hard' },
  { id: 'so_h196', text: 'Name a number between 11 and 19', difficulty: 'hard' },
  { id: 'so_h197', text: 'Name a word with exactly 14 letters', difficulty: 'hard' },
  { id: 'so_h198', text: 'Name a word containing sp', difficulty: 'hard' },
  { id: 'so_h199', text: 'Name a word containing lk', difficulty: 'hard' },
  { id: 'so_h200', text: 'Name a word ending with ity', difficulty: 'hard' },
  { id: 'so_h201', text: 'Name a word starting with mega', difficulty: 'hard' },
  { id: 'so_h202', text: 'Name a country starting with E', difficulty: 'hard' },
  { id: 'so_h203', text: 'Name a fruit starting with T', difficulty: 'hard' },
  { id: 'so_h204', text: 'Name a U.S. state starting with I', difficulty: 'hard' },
  { id: 'so_h205', text: 'Name a word ending with ism', difficulty: 'hard' },
  { id: 'so_h206', text: 'Name a word starting with hyper', difficulty: 'hard' },
  { id: 'so_h207', text: 'Name a number divisible by 16', difficulty: 'hard' },
  { id: 'so_h208', text: 'Name a number between 320 and 330', difficulty: 'hard' },
  { id: 'so_h209', text: 'Name a word containing dr', difficulty: 'hard' },
  { id: 'so_h210', text: 'Name a word containing fl', difficulty: 'hard' },
  { id: 'so_h211', text: 'Name a word ending with ence', difficulty: 'hard' },
  { id: 'so_h212', text: 'Name a chess piece starting with K', difficulty: 'hard' },
  { id: 'so_h213', text: 'Name a Greek letter starting with O', difficulty: 'hard' },
  { id: 'so_h214', text: 'Name a country ending with stan', difficulty: 'hard' },
  { id: 'so_h215', text: 'Name a word starting with multi', difficulty: 'hard' },
  { id: 'so_h216', text: 'Name a number between 42 and 48', difficulty: 'hard' },
  { id: 'so_h217', text: 'Name a word with exactly 15 letters', difficulty: 'hard' },
  { id: 'so_h218', text: 'Name a word containing bl', difficulty: 'hard' },
  { id: 'so_h219', text: 'Name a word containing rk', difficulty: 'hard' },
  { id: 'so_h220', text: 'Name a word ending with ive', difficulty: 'hard' },
  { id: 'so_h221', text: 'Name a fruit with exactly 5 letters', difficulty: 'hard' },
  { id: 'so_h222', text: 'Name a country with exactly 7 letters', difficulty: 'hard' },
  { id: 'so_h223', text: 'Name a U.S. state with exactly 6 letters', difficulty: 'hard' },
  { id: 'so_h224', text: 'Name a word ending with en', difficulty: 'hard' },
  { id: 'so_h225', text: 'Name a word starting with semi', difficulty: 'hard' },
  { id: 'so_h227', text: 'Name a number between 610 and 620', difficulty: 'hard' },
  { id: 'so_h228', text: 'Name a word containing gr', difficulty: 'hard' },
  { id: 'so_h229', text: 'Name a word containing sk', difficulty: 'hard' },
  { id: 'so_h230', text: 'Name a word ending with ous', difficulty: 'hard' },
  { id: 'so_h231', text: 'Name a color with exactly 4 letters', difficulty: 'hard' },
  { id: 'so_h232', text: 'Name a gemstone ending with ite', difficulty: 'hard' },
  { id: 'so_h233', text: 'Name a unit of temperature', difficulty: 'hard' },
  { id: 'so_h234', text: 'Name a word starting with neo', difficulty: 'hard' },
  { id: 'so_h235', text: 'Name a number between 44 and 54', difficulty: 'hard' },
  { id: 'so_h236', text: 'Name a word with exactly 16 letters', difficulty: 'hard' },
  { id: 'so_h237', text: 'Name a word containing cr', difficulty: 'hard' },
  { id: 'so_h238', text: 'Name a word containing tw', difficulty: 'hard' },
  { id: 'so_h239', text: 'Name a word ending with ian', difficulty: 'hard' },
  { id: 'so_h240', text: 'Name a country starting with R', difficulty: 'hard' },
  { id: 'so_h241', text: 'Name a fruit starting with A', difficulty: 'hard' },
  { id: 'so_h242', text: 'Name a U.S. state starting with H', difficulty: 'hard' },
  { id: 'so_h243', text: 'Name a word ending with ure', difficulty: 'hard' },
  { id: 'so_h244', text: 'Name a word starting with super', difficulty: 'hard' },
  { id: 'so_h245', text: 'Name a number divisible by 10', difficulty: 'hard' },
  { id: 'so_h246', text: 'Name a number between 710 and 720', difficulty: 'hard' },
  { id: 'so_h247', text: 'Name a word containing pr', difficulty: 'hard' },
  { id: 'so_h248', text: 'Name a word containing sm', difficulty: 'hard' },
  { id: 'so_h249', text: 'Name a word ending with ent', difficulty: 'hard' },
];