// ─────────────────────────────────────────────────────────────────────────────
// Talent Show — Prompt Banks
// ─────────────────────────────────────────────────────────────────────────────

/** Round 1 & 2 — standard 30-second performance challenges */
export const TALENT_SHOW_PROMPTS: string[] = [
  'Do a stand-up joke about lettuce',
  'Imitate a celebrity accepting an award',
  'Act like you just won the lottery',
  'Pretend you are a dramatic weather reporter',
  'Perform a fake commercial for toothpaste',
  'Make up a song about socks',
  'Do your best evil villain laugh',
  'Pretend you are a magician whose trick just failed',
  'Narrate your life like a nature documentary',
  'Do an impression of a robot learning to dance',
  'Pretend you are a chef describing plain water',
  'Act out a job interview for the position of professional napper',
  'Perform a movie trailer for the most boring film ever made',
  'Convince the group a potato is the most exciting thing on Earth',
  'Do your best impression of a toddler explaining quantum physics',
  'Act out waking up late on the most important day of your life',
  'Perform a dramatic reading of a fast food menu',
  'Do a motivational speech about tying your shoes',
  'Imitate a GPS giving directions in a haunted house',
  'Act like you are a sports commentator for someone eating a sandwich',
  'Pretend to be a pirate who is deathly afraid of water',
  'Do your best impression of a sleepwalking chef',
  'Perform a news segment about a missing sock',
  'Act out a contestant on a cooking show who accidentally made soup instead of cake',
  'Pretend you are a squirrel giving a TED Talk',
  'Act like your phone just came to life and is mad at you',
  'Do a dramatic monologue about losing WiFi',
  'Perform a cooking show using invisible ingredients',
  'Imitate a dog trying to explain taxes',
  'Act like you are stuck in slow motion',
  'Pretend you are a tour guide for your own bedroom',
  'Do an impression of a superhero with useless powers',
  'Act like you are arguing with your reflection',
  'Perform a Shakespearean speech about pizza',
  'Pretend you are a time traveler confused by modern slang',
  'Act like you just discovered gravity',
  'Do a soap opera scene about spilled milk',
  'Imitate a cat who just knocked something over',
  'Pretend you are a fitness trainer for couch potatoes',
  'Act like you are narrating a heist of cookies',
  'Perform a lullaby that becomes intense and dramatic',
  'Pretend you are a phone alarm trying to be persuasive',
  'Act like your shoes are controlling your actions',
  'Do an impression of a confused wizard',
  'Pretend you are a plant begging for water',
  'Act like you are a detective solving a missing snack case',
  'Perform a horror story about doing homework',
  'Pretend you are an AI malfunctioning mid-sentence',
  'Act like you are auditioning for a role as a rock',
  'Do a motivational speech for procrastinators',
  'Pretend you are a mirror giving life advice',
  'Act like your shadow has its own personality',
  'Perform a rap about doing laundry',
  'Pretend you are a GPS that keeps second-guessing itself',
  'Act like you are allergic to air',
  'Do an impression of a nervous astronaut',
  'Pretend you are explaining Earth to aliens',
  'Act like your hands are arguing with each other',
  'Perform a commercial for invisible glasses',
  'Pretend you are a villain whose plan makes no sense',
  'Act like you are underwater but trying to act normal',
  'Do a dramatic reading of a grocery receipt',
  'Pretend you are a teacher grading ridiculous answers',
  'Act like you are trying to open a jar that won’t budge',
  'Perform a nature documentary about your hair',
  'Pretend you are a ghost who is scared of humans',
  'Act like your chair is alive',
  'Do an impression of someone trying to whisper loudly',
  'Pretend you are a cereal mascot having an existential crisis',
  'Act like you are stuck in a loop',
  'Perform a fake TED Talk on why naps are essential',
  'Pretend you are a pirate discovering land for the first time',
  'Act like your phone battery is your life force',
  'Do an impression of someone reacting to a surprise party they hate',
  'Pretend you are a chef cooking rocks',
  'Act like you are invisible and testing it',
  'Perform a musical about brushing your teeth',
  'Pretend you are a historian explaining memes',
  'Act like your voice is delayed',
  'Do an impression of a sleepy superhero',
  'Pretend you are a couch reviewing humans',
  'Act like you are in a silent movie',
  'Perform a news report about a broken pencil',
  'Pretend you are a villain monologuing to a sandwich',
  'Act like you are trying to remember something important but can’t',
  'Do an impression of someone overreacting to a paper cut',
  'Pretend you are a magician revealing secrets accidentally',
  'Act like your reflection is lagging behind',
  'Perform a dramatic breakup with your phone',
  'Pretend you are a robot discovering emotions',
  'Act like you are narrating your own thoughts',
  'Do an impression of someone trying to act natural',
  'Pretend you are a tour guide for your fridge',
  'Act like gravity suddenly changed',
  'Perform a song about forgetting names',
  'Pretend you are a pillow giving life advice',
  'Act like your arms are too heavy',
  'Do an impression of someone trying to be sneaky but failing',
  'Pretend you are a detective interrogating a chair',
  'Act like you are in zero gravity',
  'Perform a commercial for a useless invention',
  'Pretend you are a student who studied the wrong topic',
  'Act like your voice is auto-tuned',
  'Do an impression of someone talking to themselves in public',
  'Pretend you are a cat stuck in a box',
  'Act like your shoes are squeaky and embarrassing',
  'Perform a dramatic reading of a text message',
  'Pretend you are a scientist discovering socks',
  'Act like you are frozen but can still talk',
  'Do an impression of someone explaining something they don’t understand',
  'Pretend you are a haunted toaster',
  'Act like your hair has opinions',
  'Perform a cooking show gone wrong',
  'Pretend you are a comedian bombing on stage',
  'Act like you are being chased by something invisible',
  'Do an impression of someone pretending to listen',
  'Pretend you are a bored lifeguard at a kiddie pool',
  'Act like your limbs are out of sync',
  'Perform a dramatic weather forecast for indoors',
  'Pretend you are a pen running out of ink',
  'Act like you are trying to stay awake in class',
  'Do an impression of someone faking confidence',
  'Pretend you are a dog who just learned to talk',
  'Act like your reflection disagrees with you',
  'Perform a motivational speech for snacks',
  'Pretend you are a phone that doesn’t want to be used',
  'Act like your legs are jelly',
  'Do an impression of someone reacting to bad WiFi',
  'Pretend you are a sock lost in the dryer',
  'Act like you are shrinking',
  'Perform a dramatic scene about losing keys',
  'Pretend you are a robot pretending to be human',
  'Act like your arms are stuck',
  'Do an impression of someone trying to lie convincingly',
  'Pretend you are a haunted mirror',
  'Act like you are walking through molasses',
  'Perform a song about being bored',
  'Pretend you are a book narrating itself',
  'Act like your voice echoes randomly',
  'Do an impression of someone trying not to laugh',
  'Pretend you are a couch potato literally',
  'Act like your head is too heavy',
  'Perform a dramatic scene about choosing what to eat',
  'Pretend you are a confused GPS in a maze',
  'Act like your body is glitching',
  'Do an impression of someone overthinking everything',
  'Pretend you are a haunted refrigerator',
  'Act like you are stepping on hot lava',
  'Perform a commercial for air',
  'Pretend you are a teacher who forgot the lesson',
  'Act like your hands are puppets',
  'Do an impression of someone trying to act cool',
  'Pretend you are a lamp with feelings',
  'Act like your voice is backwards',
  'Perform a dramatic reading of a spam email',
  'Pretend you are a scientist discovering chairs',
  'Act like your arms are noodles',
  'Do an impression of someone reacting to a jump scare',
  'Pretend you are a nervous game show host',
  'Act like your shadow is delayed',
  'Perform a rap about homework',
  'Pretend you are a tired superhero',
  'Act like you are stuck in rewind',
  'Do an impression of someone giving bad advice',
  'Pretend you are a ghost trying to be friendly',
  'Act like your body is made of rubber',
  'Perform a dramatic monologue about socks',
  'Pretend you are a confused tourist in your own house',
  'Act like your voice is glitching',
  'Do an impression of someone trying to apologize',
  'Pretend you are a haunted vacuum',
  'Act like your feet are stuck to the floor',
  'Perform a fake documentary about your day',
  'Pretend you are a bored villain',
  'Act like you are floating',
  'Do an impression of someone reacting to a surprise test',
  'Pretend you are a toaster giving a speech',
  'Act like your arms are asleep',
  'Perform a song about being late',
  'Pretend you are a confused robot',
  'Act like your voice is tiny',
  'Do an impression of someone trying to be dramatic',
  'Pretend you are a haunted phone',
  'Act like your body is stiff',
  'Perform a dramatic reading of a menu',
  'Pretend you are a scientist explaining naps',
  'Act like your movements are delayed',
  'Do an impression of someone pretending to understand',
  'Pretend you are a chair reviewing humans',
  'Act like your body is weightless',
  'Perform a rap about snacks',
  'Pretend you are a ghost afraid of the dark',
  'Act like your voice is robotic',
  'Do an impression of someone trying to be serious',
  'Pretend you are a confused cat',
  'Act like your arms are too long',
  'Perform a dramatic scene about losing your phone',
  'Pretend you are a scientist discovering sleep',
  'Act like your body is glitching',
  'Do an impression of someone trying to act normal',
  'Pretend you are a haunted shoe',
  'Act like your voice is echoing',
  'Perform a commercial for nothing',
  'Pretend you are a detective solving nothing',
  'Act like your body is stiff and robotic',
  'Do an impression of someone trying to act cool but failing'
];

/** Tiebreaker — quick 10-second bursts */
export const TALENT_SHOW_TIEBREAK_PROMPTS: string[] = [
  'Beatbox for 10 seconds',
  'Do your best chicken impression',
  'Say the alphabet backwards as fast as you can',
  'Air guitar to a song only you can hear',
  'Do the most dramatic shocked face and hold it',
  'Pretend to be a statue slowly coming to life',
  'Do your best ninja move in slow motion',
  'Imitate a phone that just ran out of battery',
  'Act out a sneeze in extreme slow motion',
  'Make the sound of a dial-up modem connecting',
  'Do your best T-Rex impression',
  'Mime pulling an extremely heavy object across the room',
  'Clap in a rhythm and repeat it perfectly',
  'Do your best evil grin and hold it',
  'Act like you stepped on a LEGO',
  'Imitate a microwave finishing',
  'Do your best robot walk',
  'Pretend you forgot what you were doing mid-action',
  'Make the sound of popcorn popping',
  'Do a dramatic hair flip (real or imaginary)',
  'Act like you are freezing cold',
  'Imitate a car failing to start',
  'Do your best owl hoot',
  'Pretend to walk through strong wind',
  'Make the sound of a bouncing ball',
  'Do your best zombie walk',
  'Act like you just tasted something terrible',
  'Imitate a door creaking open',
  'Do your best superhero landing',
  'Pretend your shoes are stuck to the floor',
  'Make the sound of rain getting heavier',
  'Do your best frog jump',
  'Act like you are tiptoeing past someone',
  'Imitate a printer malfunctioning',
  'Do your best spy sneaking move',
  'Pretend your arms are spaghetti',
  'Make the sound of a race car zooming by',
  'Do your best dramatic faint',
  'Act like you are dodging invisible lasers',
  'Imitate a duck quacking angrily',
  'Do your best dance move in slow motion',
  'Pretend you are walking on a tightrope',
  'Make the sound of a thunderclap',
  'Do your best confused face',
  'Act like your phone is vibrating in your pocket',
  'Imitate a cat meowing dramatically',
  'Do your best karate chop sequence',
  'Pretend you are stuck in an invisible box',
  'Make the sound of a train passing',
  'Do your best villain pose',
  'Act like you are sneezing repeatedly',
  'Imitate a crowd cheering',
  'Do your best penguin waddle',
  'Pretend you are carrying something fragile',
  'Make the sound of a balloon deflating',
  'Do your best surprised gasp',
  'Act like you are being pulled by a rope',
  'Imitate a helicopter spinning up',
  'Do your best crab walk',
  'Pretend you are running in place but going nowhere',
  'Make the sound of a ticking clock',
  'Do your best dramatic slow clap',
  'Act like you are balancing something on your head',
  'Imitate a siren passing by',
  'Do your best snake slither',
  'Pretend your feet are glued together',
  'Make the sound of a bubbling potion',
  'Do your best exaggerated wink',
  'Act like you are trying not to fall asleep',
  'Imitate a horse galloping',
  'Do your best robot glitch',
  'Pretend you are dodging raindrops',
  'Make the sound of wind howling',
  'Do your best fish out of water',
  'Act like you are walking uphill',
  'Imitate a baby crying dramatically',
  'Do your best magician flourish',
  'Pretend you are being chased',
  'Make the sound of a bell ringing',
  'Do your best superhero pose',
  'Act like you are stuck in mud',
  'Imitate a monkey chattering',
  'Do your best silent scream',
  'Pretend you are holding something very hot',
  'Make the sound of waves crashing',
  'Do your best ballerina spin',
  'Act like you are avoiding puddles',
  'Imitate a crowd booing',
  'Do your best exaggerated shrug',
  'Pretend you are opening a very heavy door',
  'Make the sound of a rocket launching',
  'Do your best lion roar',
  'Act like you are slipping on ice',
  'Imitate a beep sequence (like a scanner)',
  'Do your best ninja vanish',
  'Pretend you are carrying a stack of unstable plates',
  'Make the sound of a dripping faucet',
  'Do your best exaggerated nod',
  'Act like you are bouncing on a trampoline',
  'Imitate a dog barking excitedly',
  'Do your best superhero flying motion',
  'Pretend you are walking through tall grass',
  'Make the sound of static noise',
  'Do your best surprised jump',
  'Act like you are trying to catch something falling',
  'Imitate a buzzer going off',
  'Do your best villain laugh in 3 seconds',
  'Pretend you are shrinking rapidly',
  'Make the sound of a zipper',
  'Do your best dramatic point',
  'Act like you are pulled by gravity sideways'
];

/** Final Round (Round 3) — extreme and hilarious 30-second challenges */
export const TALENT_SHOW_FINAL_PROMPTS: string[] = [
  'Attempt a breakdance routine while saying words that rhyme with "cat"',
  'Perform opera about the last meal you ate',
  'Act out a slow-motion car crash using only your body and sound effects',
  'Pretend you are fighting a giant invisible spider — for the full 30 seconds',
  'Imitate a broken robot trying to propose marriage',
  'Act out what happens when a toddler accidentally becomes president',
  'Perform a dramatic death scene from eating slightly-too-cold pizza',
  'Do your best impression of a drunk penguin trying to ice skate',
  'Pretend you are a superhero whose only power is being excessively enthusiastic',
  'Host a cooking show where the only ingredient is imaginary air',
  'Give a motivational speech as a deeply disappointed potato',
  'Act out a first-date disaster in fast forward then slow motion',
  'Imitate a fitness influencer who has never exercised before in their life',
  'Perform a Shakespearean tragedy about missing the bus',
  'Do jumping jacks while naming animals alphabetically',
  'Perform a dramatic monologue while clapping every third word',
  'Act like you are running from danger while counting backwards from 50',
  'Sing a song about pizza while doing squats',
  'Pretend to cry while explaining how to tie your shoes step by step',
  'Do a villain speech while spinning in a circle slowly',
  'Act like you are freezing cold while listing U.S. states',
  'Perform a love confession while doing push-ups (or miming them)',
  'Pretend you are being chased while reciting the days of the week backwards',
  'Do a cooking show while hopping on one foot',
  'Act out a superhero landing every time you say a word that starts with “s”',
  'Perform a rap while snapping on every beat and stomping every other beat',
  'Pretend you are underwater while naming fruits as fast as possible',
  'Do a news report while blinking exaggeratedly every 2 seconds',
  'Act like a robot glitching while counting up by 3s',
  'Perform a dramatic speech while switching emotions every 5 seconds',
  'Pretend you are late while tying imaginary shoelaces repeatedly',
  'Do a stand-up routine while pacing in a square pattern',
  'Act like you are lifting heavy weights while spelling your name repeatedly',
  'Perform a musical while clapping off-beat intentionally',
  'Pretend you are sneaking while whisper-counting to 30',
  'Do a dramatic scene while tapping your head every time you pause',
  'Act like you are stuck in mud while listing movies or shows',
  'Perform a commercial while doing exaggerated slow-motion movements',
  'Pretend you are dizzy while naming colors around you',
  'Do a villain laugh every time you finish a sentence',
  'Act like you are in zero gravity while counting down from 20',
  'Perform a motivational speech while marching in place',
  'Pretend you are arguing while doing jumping motions',
  'Do a nature documentary while crouching and standing repeatedly',
  'Act like you are on a tightrope while naming cities',
  'Perform a song while alternating between whispering and shouting',
  'Pretend you are running late while checking an imaginary watch constantly',
  'Do a dramatic reading while pointing in a new direction every sentence',
  'Act like you are freezing while rubbing your arms and counting',
  'Perform a speech while switching accents every 5 seconds',
  'Pretend you are scared while backing away slowly the entire time',
  'Do a cooking show while pretending to juggle',
  'Act like you are tired while forcing yourself to stay energetic',
  'Perform a commercial while snapping your fingers constantly',
  'Pretend you are walking uphill while explaining something simple',
  'Do a rap while bouncing in place continuously',
  'Act like your shoes are stuck while trying to move anyway',
  'Perform a dramatic scene while clapping randomly',
  'Pretend you are invisible while reacting to imaginary people',
  'Do a speech while spinning slowly in one direction',
  'Act like you are underwater while exaggerating every movement',
  'Perform a story while changing tone every sentence',
  'Pretend you are in a hurry while stopping abruptly every few seconds',
  'Do a stand-up bit while pacing back and forth nonstop',
  'Act like you are cold while naming items in your house',
  'Perform a monologue while stomping every 3rd word',
  'Pretend you are on stage while bowing after random lines',
  'Do a cooking show while pretending everything is too hot',
  'Act like you are confused while repeating questions to yourself',
  'Perform a speech while switching volume levels constantly',
  'Pretend you are being watched while acting normal',
  'Do a musical while pointing at imaginary audience members',
  'Act like you are slipping while trying to stay upright',
  'Perform a scene while reacting to imaginary interruptions',
  'Pretend you are in slow motion while talking normally',
  'Do a commercial while exaggerating every facial expression',
  'Act like you are nervous while pacing unpredictably',
  'Perform a rap while clapping irregular rhythms',
  'Pretend you are carrying something heavy while speaking normally',
  'Do a speech while making eye contact with different “people” constantly',
  'Act like you are freezing while trying to stay confident',
  'Perform a dramatic scene while switching characters mid-sentence',
  'Pretend you are sneezing but trying to hold it in',
  'Do a story while gesturing wildly every sentence',
  'Act like you are late while explaining why you are calm',
  'Perform a commercial while acting like you forgot the script',
  'Pretend you are lost while giving directions confidently',
  'Do a speech while walking in a zigzag pattern',
  'Act like you are tired while forcing enthusiasm',
  'Perform a scene while reacting to imaginary applause',
  'Pretend you are being chased while staying in place',
  'Do a musical while clapping above your head repeatedly',
  'Act like you are confused while giving confident answers',
  'Perform a rap while pointing randomly at objects',
  'Pretend you are underwater while trying to speak clearly',
  'Do a dramatic reading while changing posture constantly',
  'Act like you are cold while pretending it is hot',
  'Perform a speech while snapping every sentence',
  'Pretend you are nervous while over-smiling',
  'Do a scene while reacting to imaginary sound effects',
  'Act like you are slipping while staying upright',
  'Perform a commercial while pretending it is live and going wrong',
  'Pretend you are being interviewed while answering your own questions',
  'Do a speech while bowing slightly every sentence',
  'Act like you are in a race while standing still',
  'Perform a dramatic scene while pausing randomly',
  'Pretend you are dizzy while trying to focus',
  'Do a rap while alternating speeds every few seconds',
  'Act like you are scared while trying to appear brave',
  'Perform a speech while nodding excessively',
  'Pretend you are on stage while reacting to imaginary judges'
];
